### ISSUE TITLE
Grid menu option "showClearAllFiltersCommand" is always displayed

### ISSUE THREAD

**Issue by sabeurch** [ghiscoding/Angular-Slickgrid#10]
When I set grid menu options as follow:
```
this.gridOptions = {
    ....,
    gridMenu: {
        showClearAllFiltersCommand: false,
        showToggleFilterCommand: false
    }
    ....,
}
```
This has no effect, clear filter and toggle filter commands are alwasy displayed.

I think, it has to do with those lines of code:
```
options.gridMenu.showClearAllFiltersCommand = options.gridMenu.showClearAllFiltersCommand || true;
options.gridMenu.showRefreshDatasetCommand = options.gridMenu.showRefreshDatasetCommand || true;
options.gridMenu.showToggleFilterCommand = options.gridMenu.showToggleFilterCommand || true;
```

in file "angular-slickgrid.js", Logic of "|| true" sets values always into true.

Would you please verify ?

Note: For the moment as a workaround, we can disable those commands from option "customItems", but it keeps them displayed as disabled.

**Comment by ghiscoding** [comment]
I believe that I have fixed this behavior couple weeks ago, it works on my side. The code implementation is to use your options, if any, and if not found it will set it to true.

**Comment by sabeurch** [comment]
Yes, version 0.8.1 works fine.
Thank you !

**Comment by ghiscoding** [comment]
So we can close the issue?

**Comment by sabeurch** [comment]
Yes, please.
