### ISSUE TITLE
Filter dropdown for boolean column appear twice on page, after first click

### ISSUE THREAD

**Issue by sitsmonty** [ghiscoding/Angular-Slickgrid#1009]
### Describe the bug

I have a basic grid with just one column which is of boolean type. I set the filter to be of a single select dropdown. The implementation is identical to "Effort Driven" column in this example - https://ghiscoding.github.io/Angular-Slickgrid/#/editor.

The grid renders fine, but as soon as I click on the filter to select, the dropdown appears twice on the page simultaneously. First instance was at the expected location. Second one, right at the bottom of the screen. 

Please advice.

### Reproduction

Here is my HTML markup -

    <angular-slickgrid gridId="grid1"
                       [columnDefinitions]="columnDefinitions"
                       [gridOptions]="gridOptions"
                       [dataset]="dataset">
    </angular-slickgrid>

and here are my grid options -

this.gridOptions = {
      gridWidth: 600,
      gridHeight: 300,
      enableAutoResize: true,
      enableSorting: true,
      enablePagination: true,
      pagination: {
        pageSizes: [5, 10, 20, 25, 50],
        pageSize: 10
      },
      enableExcelExport: false,
      enableHeaderMenu: false,
      enableFiltering: true,
      showCustomFooter: true
    };

and here are my column definitions -

{
        id: 'active',
        name: 'Active',
        field: 'active',
        formatter: Formatters.checkmark,
        filterable: true,
        filter: {
          model: Filters.singleSelect,
          collection: [{ value: '', label: 'All' }, { value: true, label: 'True' }, { value: false, label: 'False' }],
          filterOptions: { autoDropWidth: true } as MultipleSelectOption
        },
        type: FieldType.boolean,
        sortable: false,
        minWidth: 100,
        maxWidth: 100
      }

The grid renders alright, as expected. But as soon as I click the filter dropdown, this is what happens -

![image](https://user-images.githubusercontent.com/5271297/193959652-6d2d2d4b-cb97-458d-87d7-329fca9ba2af.png)

### Environment Info

```shell
Angular 14.2.4
Angular-Slickgrid 4.3.1
TypeScript 4.8.4
Edge 105.0.1343.53 
Windows Server 2019 Datacenter
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Can't help without a repro, I need a stackblitz or a github repo that reproduces the issue. The only thing that I can think of quickly would be that we use the `container: 'body'` property with the multiple-select lib to append to the body, that's the only way to get the dropdown to show up over the grid. It looks like the one at the bottom isn't positioned correctly, the dropdown also uses the column id to do certain things and it should show up in the class names (something like `filter-myColumn`). 

Another thing that you could maybe try is to possibly disable `autoAdjustDropPosition` which has the name suggest will try to auto-position (top or bottom of the cell) and see if that makes any difference
```ts
filterOptions: { autoDropWidth: false, autoAdjustDropPosition: false } as MultipleSelectOption
```

Other than that I need a repro

**Comment by sitsmonty** [comment]
We figured it out. The issue was I had two 'body' tags in my HTML and that caused this multiple-select window to attach it to both of them. Thank you.

**Comment by ghiscoding** [comment]
haha yeah that would be the issue, good thing I mentioned the 'body' container then. 
Thanks for using the lib 😉 ⭐
