### ISSUE TITLE
Wiki - Typo in code for How to Load Grid with certain Columns Preset (example hide certain Column(s) on load)

### ISSUE THREAD

**Issue by taurus1900** [ghiscoding/Angular-Slickgrid#1010]
### Describe the bug

In this code [https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-State-&-Preset#component-3](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-State-&-Preset#component-3)

This line is incorrectly setting the width
return { columnId: col.id, width: col.id };

should be 
return { columnId: col.id, width: col.width };

### Reproduction

See wiki

### Environment Info

```shell
Current Wiki
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Thanks for the info, it's fixed now 😃
