### ISSUE TITLE
Filter grouped results?

### ISSUE THREAD

**Issue by Shoti2313** [ghiscoding/Angular-Slickgrid#1013]
### Clear and concise description of the problem

For example, we have a group table

```
             Group | Value
Group A
             A | Test 
             A | Test 2
             A | Test 1
Group B
             B | Test
             B | Test Again 1
Group C
             C | Test
             C | Test
             C | Test Again
```

I want to specify to filter the group with the ff for example:
- `Value` that have both `Test` and `Test Again*`. So the resulted table will show `Group B` and `Group C`. Wild card is possible
- Count filter can be specified like to return groups with less than 3 rows. in this case, only `Group B` is shown.

Is this possible?

### Suggested solution

I did a quick and minor workaround by creating a custom compare function for groupings

```
slickGridGroupComparer(a, b) { 
    let query =  "Value = test & Value = test again* ";
    let conditions = query.split('&');
    let aScore = 0;
    let bScore = 0;
    conditions.forEach(condition => {
      const formattedCondition = condition.trim();
      let key = formattedCondition.split('=')[0].trim();
      let valCondition = formattedCondition.split('=')[1].trim();

      let aSatisfied = a.rows.some((val, idx, ar) => {
        let res = this._wildcardStringRuleMatch(val[key].toLocaleLowerCase(), valCondition.toLocaleLowerCase()); //wildcard match
        return res;
      });
      if (aSatisfied) aScore++;

      let bSatisfied = b.rows.some((val, idx, ar) => {
        let res = this._wildcardStringRuleMatch(val[key].toLocaleLowerCase(), valCondition.toLocaleLowerCase()); //wildcard match
        return res;
      });
      if (bSatisfied) bScore++;
    });

    return (bScore - aScore)
  }
```

It increases the score per conditions that are satisfied. So it returns first the groups that are satisfied in the query, and at the bottom of the list are the rows that doesn't satisfy the query. It doesn't filter out :( 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
Sorry but I don't really understand what you're trying to achieve, and I never had that use that complicate filters, the grid is supposed to offer just simple filtering. If you need to filter depending on the cell data context, you can use [collection override](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Select-Filter#collection-override) (it was asked in this [SO](https://stackoverflow.com/questions/65361444/angular-slickgrid-dynamic-editor-collection-by-every-row-data/65419890#65419890)), there's a lot of other examples in the same Wiki. The dropdown filter uses [multiple-select.js](https://multiple-select.wenzhixin.net.cn/examples) and if you find any useful options from the lib, you can pass them in Angular-Slickgrid via the `filterOptions: { /* 3rd party lib options /* }`. You used a comparer, I assume you already know that you can provide a comparer to a column. 

If that doesn't help, I'm afraid that I can't provide more help than that

**Comment by Shoti2313** [comment]
Hi, thanks for responding. I just like to filter the group results by its count and values. like saying show groups that has more than 5 rows or show groups that contains these values after doing the drag-grouping feature. Will look into your suggestions maybe i can find something :D

**Comment by ghiscoding** [comment]
closing then since it's not an issue with the lib
