### ISSUE TITLE
IE 11: ReferenceError: "TextEncoder" is undefined

### ISSUE THREAD

**Issue by EfkanKnz** [ghiscoding/Angular-Slickgrid#108]
**I'm submitting a bug report**

* **Angular Version:**
Version 7

* **Library Version:**
angular-slickgrid: 1.8.0

* **Browser:**
IE 11  :-1: 

* **Language:**
TypeScript: 3.2.2

**Current behavior:**
Hello, I am getting an error on Internet Explorer 11, it says:
`ERROR Error: Uncaught (in promise): ReferenceError: « TextEncoder » is undefined`
`ReferenceError: « TextEncoder » is undefined`

**Others Information**
I know that you updated slickgrid to version 2.x with Angular 7 and I tried to update it, but I couldn't get it to work.
-->[https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.0.3](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.0.3)
**Angular 7 support**
Breaking Changes
- updated RxJs to version 6.3.x
- updated @ngx-translate/core to 11.x.x
- updated @ngx-translate/http-loader to 4.x.x
- updated all Angular libs to 7.x.x
- updated ng-packagr to 4.4.x

So I'm still using slickgrid 1.8, but with Angular 7.

**IE 11 error**
It might come from the libs versions I use, I can show you my package.json file:

>  "dependencies": {
    "@angular/animations": "^7.2.1",
    "@angular/common": "^7.2.1",
    "@angular/compiler": "^7.2.1",
    "@angular/core": "^7.2.1",
    "@angular/forms": "^7.2.1",
    "@angular/http": "^7.2.1",
    "@angular/platform-browser": "^7.2.1",
    "@angular/platform-browser-dynamic": "^7.2.1",
    "@angular/router": "^7.2.1",
    "@auth0/angular-jwt": "^2.0.0",
    "@ng-select/ng-select": "^2.9.1",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.0",
    "@stomp/stompjs": "^5.0.2",
    "@swimlane/ngx-charts": "^10.0.0",
    "@types/fullcalendar": "^3.8.0",
    "@types/jquery": "^3.3.22",
    "angular-archwizard": "^3.0.0",
    "angular-slickgrid": "^1.8.0",
    "awesome-bootstrap-checkbox": "^1.0.1",
    "bootstrap": "^4.1.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "flatpickr": "^4.5.0",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^3.9.0",
    "jquery": "^3.3.1",
    "ng-fullcalendar": "^1.7.1",
    "ng2-flatpickr": "^5.0.2",
    "ngx-toastr": "^9.0.2",
    "node-sass": "^4.10.0",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.3",
    "slickgrid": "^2.3.21",
    "sockjs-client": "^1.3.0",
    "tslib": "^1.9.0",
    "zone.js": "^0.8.28"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/cli": "^7.2.2",
    "@angular/compiler-cli": "^7.2.1",
    "@angular/language-service": "^7.2.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.1",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "^3.2.2"
  }

By the way, it's working fine on Chrome :+1:

**Comment by ghiscoding** [comment]
The grid is working fine in my current App developed at work. Make sure to add all necessary polyfills as they are definitely required.

**Comment by EfkanKnz** [comment]
Hi @ghiscoding! I found out that it was not related to slickgrid, its working fine on IE. I think my error comes from SockJS (the lib I use for websocket) and I'm still working on it...

My apologies, you can close this issue :open_mouth:

**Comment by ghiscoding** [comment]
Thanks for the feedback, good luck with IE11, I know it's the mast annoying part but we still have a few more years to support it 😐

**Comment by cancelcraft** [comment]
@ghiscoding - I see you have stompjs in your package.json. Stompjs makes use of TextEncoder which isn't available on IE11. Perhaps that's your issue?

**Comment by ghiscoding** [comment]
@cancelcraft 
Thanks but it's not my `package.json`, I don't use that package in my lib and I also mentioned in earlier [post](https://github.com/ghiscoding/Angular-Slickgrid/issues/108#issuecomment-455575577) that it's not an issue on my side. Side note, I use `text-encoding-utf-8` for the CSV Export, which does work in IE11. 

The lib works just fine with IE11, as long as you have the proper polyfill installed. This is not an issue.
