### ISSUE TITLE
Is there some event when columns are hiding?

### ISSUE THREAD

**Issue by audrys** [ghiscoding/Angular-Slickgrid#109]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Angular Version:**
major.minor.patch

* **Library Version:**
major.minor.patch

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript X.X

**Expected/desired behavior:**
I need some event how to save the hidden columns by user.
Thanks

**Comment by ghiscoding** [comment]
The answer is somewhere in this [Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-&-DataView-Events)

**Comment by ghiscoding** [comment]
I'll close the issue since it was answered in previous comment
