### ISSUE TITLE
Uncaught (in promise): Error: StaticInjectorError  in version 0.8.1

### ISSUE THREAD

**Issue by ctung** [ghiscoding/Angular-Slickgrid#11]
core.js:1440 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[AngularSlickgridComponent -> TranslateService]: 
  StaticInjectorError(Platform: core)[AngularSlickgridComponent -> TranslateService]: 
    NullInjectorError: No provider for TranslateService!
Error: StaticInjectorError(AppModule)[AngularSlickgridComponent -> TranslateService]: 
  StaticInjectorError(Platform: core)[AngularSlickgridComponent -> TranslateService]: 
    NullInjectorError: No provider for TranslateService!

**Comment by ghiscoding** [comment]
We really don't have this error anywhere, have you followed the [Localization installation wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Localization)? You need to do a certain minimum of `ngx-translate` installation

**Comment by sabeurch** [comment]
I got the same error as ctung from the beginning (missed Step : 5. Install/Setup ngx-translate for Localization), but after correctly setting the localisation it works.

**Comment by ctung** [comment]
Yes, ngx-translate was my problem.  Working great now.  Thanks!

**Comment by ghiscoding** [comment]
Great, thanks for the feedback... closing it then
