### ISSUE TITLE
Grouped rows disrupt row details pane if row details pane size is more than the grouped rows

### ISSUE THREAD

**Issue by ptatoChi** [ghiscoding/Angular-Slickgrid#1128]
### Describe the bug

Hello. Thanks for this awesome library!

I have a table that contains both draggable grouping and row detail feature. here is a sample output
![image](https://user-images.githubusercontent.com/11557985/233012886-f9ec6db3-c97e-49c8-bdf8-afd63c0756cf.png)

Expanding it while in group that has less than the number of panelRows for expansion will show undefined rows.
![image](https://user-images.githubusercontent.com/11557985/233013619-00e01897-e29d-4986-89d4-9e66e607fef4.png)

Expanding works normally if the group is greater than the panelRows or when they are not grouped at all

### Reproduction

Have both draggable grouping and row detail feature and have the row detail panelRow configured to a bigger number than the grouped row

### Environment Info

```shell
Angular 15
angular-slickgrid 5.6.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Yes as you can see, these 2 addons should not be used together for exactly that reason since they both use some form of row grouping. Sorry but I don't think it's feasible to support them when used together, I'm afraid I'm going to mark this as "won't fix".
