### ISSUE TITLE
How to add Hover/Click to select row(Change color) in Slick Grid Angular 14

### ISSUE THREAD

**Issue by ngdevnilesh** [ghiscoding/Angular-Slickgrid#1131]
### Describe the bug

How to hover and click to select the row in Slick Grid Angular 14. I have tried by adding enableRowSelection: true in grid option. It is working when we click on any perticular row but in console it is throwing following error
**_this5._dataView.mapRowsToIds is not a function**

![image](https://user-images.githubusercontent.com/62214358/234214257-95922152-51f1-4d83-bcbf-7789cb8dda59.png)

### Reproduction

add enableRowSelection: true in gridoption. it will throw error in console

### Expectation

it should select perticular row also hover color change not working

### Environment Info

```shell
"angular-slickgrid": "^4.3.1",
"@angular/core": "^14.2.12",
"typescript": "~4.6.4"
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Please provide more code to reproduce the issue. Also note that I don't support older version, I currently only support 5.x and it looks like you are under 4.x
