### ISSUE TITLE
Excel Export: Negative values converted to positive

### ISSUE THREAD

**Issue by ptatoChi** [ghiscoding/Angular-Slickgrid#1135]
### Describe the bug

I've been trying to export a table that contains a fieldtype of number. 

This is how it's displayed to the UI table
![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/11557985/f16fa24e-c274-4788-8421-91449fd94230)

When i tried to export using ExcelExportService, I get this 
![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/11557985/6c718981-4d83-47d8-8160-7eba1f3269c7)

I tried the CSV export, and i got it correctly.
![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/11557985/66444400-291a-4903-a147-892a935e21e6)

### Reproduction

Have a dataset that contains negative numbers, and set it to fieldtype.number

export using ExcelExportService

### Environment Info

```shell
Angular 15
angular-slickgrid 5.6.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ptatoChi** [comment]
I removed the `exportWithFormatter` from the excel options and it works now.. It's weird. In the UI, it was formatted correctly tho.
This will do for now on my end. Thanks @ghiscoding !

**Comment by ghiscoding** [comment]
I was able to reproduce, will do a bug fix shortly

**Comment by ghiscoding** [comment]
fixed in Angular-Slickgrid [v5.6.4](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v5.6.4) and Slickgrid-Universal `v2.6.4`, you can also test it with the live demo [Example 19](https://ghiscoding.github.io/Angular-Slickgrid/#/draggrouping)

Also note this is the last version before the next upcoming Angular-Slickgrid v6 major version
Cheers ⭐
