### ISSUE TITLE
tree-data-parent-child insert at position 'top' not working

### ISSUE THREAD

**Issue by kiranbangar5946** [ghiscoding/Angular-Slickgrid#1167]
### Describe the bug

Hi,

Need to understand 
`this.angularGrid.gridService.addItem(newItem, { position: 'top' })`; 
it adds the new fresh parent item at the **bottom** of the list no matter position is top or bottom , is this the expected behaviour ??
As GridInsertOptions defaults to position top but it no working in case of tree-data-parent-child.

Please help me to understand.

### Reproduction

Note to reproduce it 
You can add this `this.angularGrid.gridService.addItem(newItem, { position: 'top' })`; 
in addNewRow() in grid-tree-data-parent-child.component with 

 const newItem = {
        id: newId,
        parentId: null, // a new parent item to reproduce
        title: `Task 35454`,
        duration: '1 day',
        percentComplete: 99,
        start: new Date(),
        finish: new Date(),
        effortDriven: false
      };

### Environment Info

```shell
@angular/cli@^15.0.4
angular-slickgrid@^5.4.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
I would say that it is a normal behavior when used in a Tree Structure because it has to rebuild the tree and make sure the sort is working with all the tree level that it finds when building the tree. This process is already very complex and I do not want to make it every more complex just to support that. So I'm marking this as "working as expected", the only thing I could possibly do would be to maybe show a console warning when the user tries to use `position` which is not possible in a tree structure like this

**Comment by ghiscoding** [comment]
closing by Slickgrid-Universal PR [1003](https://github.com/ghiscoding/slickgrid-universal/pull/1003) that will now throw an error when user tries to use `position: 'top'`. It's simply not supported because of the extra complexity of Tree Data
