### ISSUE TITLE
Couldn't find way to show Row detailed view. 

### ISSUE THREAD

**Issue by venkateshrajen** [ghiscoding/Angular-Slickgrid#118]
Same feature i can see in aurelia-slickgrid. Kindly direct me how to reproduce same feature in angular slick grid. Great work 👍 and thanks for providing this feature for angular

**Comment by ghiscoding** [comment]
It's not available in this repo yet, just don't have the time to look into it. It might take a while

**Comment by ghiscoding** [comment]
@venkateshrajen 
I did the PR for the feature, if you could give a quick review before I merge it tomorrow that would be nice. If you have suggestions, then please write them directly in the PR #125

**Comment by ghiscoding** [comment]
See the new [Row Detail View - Example](https://ghiscoding.github.io/angular-slickgrid-bs4-demo/#/rowdetail)
