### ISSUE TITLE
How to remove default sorting In Slick Grid

### ISSUE THREAD

**Issue by vikas21thakur** [ghiscoding/Angular-Slickgrid#120]
I'm submitting a bug report

Operating System:
Windows [7|8|8.1|10]

Browser:
Chrome XX

Language:
TypeScript, Angular 6

Current behavior:
I'm using Angular-SlickGrid and trying to implement the below funcationality.

On a particular event i am resetting data in slick grid (based on my prefrence). And i am selecting rows by passing array of indexes

this.gridObjCust.getGridObjRef().resetActiveCell();                             
this.gridObjCust.getGridObjRef().setSortColumns([])
this.gridObjCust.getGridObjRef().setData(newDataSet);
this.gridObjCust.getGridObjRef().render();
this.newSelectedRow = [0,1,2,3] -- Example
this.gridObjCust.getGridObjRef().setSelectedRows(this.newSelectedRow);

This code is working fine until i used default soting of grid . After sorting till render() it will populate data propely . But when i called below method 

this.newSelectedRow = [0,1,2,3] -- Example
this.gridObjCust.getGridObjRef().setSelectedRows(this.newSelectedRow);

it reset the grid to old sorting condition . 
 
Please help me on this issue.

Expected/desired behavior:

With or with out sorting it should not reset to its old sorting order. All previous sorting should me removed if exist.

**Comment by ghiscoding** [comment]
To use default sorting/filters, you can use the `presets` Grid Options, see the [Presets Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-State-&-Preset)

**Comment by ghiscoding** [comment]
@vikas21thakur 
Did my previous post helped with your situation?

**Comment by vikas21thakur** [comment]
HI , 
Thanks , Your solution worked for me .

Regards,
Prajjwal Khonde

**Comment by ghiscoding** [comment]
@vikas21thakur 
Great, if you could up vote ⭐️  I would be happy as well 😄 
Cheers
