### ISSUE TITLE
Update Step By Step Install Wiki page

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/Angular-Slickgrid#1266]
### Describe the bug

Given a fresh new Angular 16 project, I've tried to follow along with the wiki (https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step) and once done it failed to compile due to:

* missing typings (sortablejs and dompurify)
* warnings due to dependencies on commonjs distributions of both of those and additionally autocompleter
* requiring allowSyntheticDefaultImports flag for SortableJS

### Reproduction

Create a new Angular 16 project and follow the wiki step by step guide

### Expectation

Add info about:

* `npm i -d @types/sortablejs @types/dompurify` to get proper typings and silence the typings errors
* adding `"allowedCommonJsDependencies": [
              "angular-slickgrid",
              "autocompleter",
              "moment-mini",
              "dompurify"
            ],"` as additional allowedCommonJsDependencies to silence those warnings
* adding `"allowSyntheticDefaultImports": true` to `tsconfig.app.json` to resolve the final compile issue

### Environment Info

```shell
Angular 16.2.6
Angular-SlickGrid 6.2.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zewa666** [comment]
hmm the issues go on once I fixed those as mentioned above.

Now the app goes south with an console error
```
main.ts:8 ERROR ReferenceError: Sortable is not defined
```

so as a workaround, inside main.ts I've added

```
import Sortable from 'sortablejs';

(window as any)['Sortable'] = Sortable;
```

Now the error is gone, but also no grid to be seen :(

**Comment by ghiscoding** [comment]
Hey nice to see you here too, I'm actually working on migrating Aurelia-Slickgrid to Au2

Anyway, for this project, you should download the [Angular-Slickgrid-Demos](https://github.com/ghiscoding/angular-slickgrid-demos) and compare with your setup. Any changes to the Wiki would be welcomed, I created them years ago and many things can changed between each Angular versions so yeah there could be some missed steps compare to when I started it with Angular 4 at the time

**Comment by ghiscoding** [comment]
> so as a workaround, inside main.ts I've added
> 
> ```
> import Sortable from 'sortablejs';
> 
> (window as any)['Sortable'] = Sortable;
> ```

~That already exists in Angular-Slickgrid itself, you shouldn't need to do this~
Oops you're right, it looks like I forgot to do it in this project, though I did do it in Aurelia-Slickgrid

https://github.com/ghiscoding/aurelia-slickgrid/blob/a3567d6c6d24603cefafa4b61f87c09df4207841/src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.ts#L83-L84

we should definitely do this change in here too to avoid having the user to do it himself

**Comment by zewa666** [comment]
Hey, yeah I tried to figure out how to propose a change to the Wiki but haven't seen an edit button. Hence my issue :)

With regards to the samples repo. I've tried building the bootstrap5-demo-with-translate folder but got several ERESOLVE issues. So I resorted to `npm i --force`.

After looking at it I found that part of not seeing anything is when registering the Module the Wiki says to do it without options whereas your samples do:

```AngularSlickgridModule.forRoot({
            // add any Global Grid Options/Config you might want
            // to avoid passing the same options over and over in each grids of your App
            enableAutoResize: true,
            autoResize: {
                container: '#demo-container',
                rightPadding: 10
            }
        })
```

and that was the missing piece to it

**Comment by ghiscoding** [comment]
I've done a few changes in the HOWTO, you can see if it fixes your problem, you should definitely load SortableJS through the `scripts` section in the `angular.json` config instead of in code like you did. 

If you still have problem, I would again suggest that you look at the Angular-Slickgrid-Demos and compare with your project, the demos are updated on every new release

**Comment by ghiscoding** [comment]
> After looking at it I found that part of not seeing anything is when registering the Module the Wiki says to do it without options whereas your samples do:

hmm that is strange, the demo only has them for demo purpose and it should work without any but you might still need the `.forRoot()` (or `forRoot({})`, I'm not 100% sure which one should work, the HOWTO should be updated if it's a problem.

Also for the Wiki, I've locked public editing because I didn't want garbage to come in, but I'm surprise that removes the editing part though. I've removed the checkbox "Restrict editing to collaborators only ", so you should be able to edit or provide PR for changes now

**Comment by ghiscoding** [comment]
> With regards to the samples repo. I've tried building the bootstrap5-demo-with-translate folder but got several ERESOLVE issues. So I resorted to `npm i --force`.

I use Yarn classic, it might be why I don't see these errors...

**Comment by zewa666** [comment]
I've updated the wiki with a couple of minors.

But now I've also experimented with the autoResize thingy: all thats necessary is

```
autoResize: {
        container: 'whatever_it_is_as_long_as_its_a_valid_css_selector',
      },
```

allthough funny enough really doesn't matter whether an element is found or not with the provided selector

**Comment by zewa666** [comment]
I think the issue might be over at Slickgrid-Universal and how the initial Grid size is calculated, or in this case not if no container element is found

https://github.com/ghiscoding/slickgrid-universal/blob/c6a095702a672e14b442e71be492942c07d6f1e6/packages/common/src/services/resizer.service.ts#L217

**Comment by ghiscoding** [comment]
@zewa666 latest release `v6.2.2` includes the PR you created on Slickgrid-Universal, thanks again for your contributions. Cheers
