### ISSUE TITLE
cell highlighted stays on the same position even when filtered

### ISSUE THREAD

**Issue by ptatoChi** [ghiscoding/Angular-Slickgrid#1289]
### Describe the bug

I have a dataset with hundreds of rows. I used `slickGrid.setCellCssStyles(`highlight_${[columnId]}${row}`, hash);` to highlight some cells
![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/11557985/32357afb-be07-4b5a-b750-d331c5258ec8)

now when i filter them using the column filter, the highlight remains at the same position regardless of the data
![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/11557985/444c2ee0-5447-4ac7-a497-801fc7f75584)

### Reproduction

1. Have angular 16 and the latest angular-slickgrid installed
2.  Have a sample dataset with filters enabled
3. Highlight using `setCellCssStyles` function to one of the cell
4. Filter the dataset

### Environment Info

```shell
Angular 16
Angular-slickgrid 6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
That's not an issue, that is how it was implemented in SlickGrid core library and for that reason I'm closing this "as designed". There's no logic at all for the cell styling, you have to deal with it yourself
