### ISSUE TITLE
Attach Angular Component in AsyncPostRender and keep it running

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/Angular-Slickgrid#1294]
### Clear and concise description of the problem

Currently the approach shown in https://ghiscoding.github.io/Angular-Slickgrid/#/angular-components is merely rendering the dynamic Angular Component by waiting for one cycle and than picking up it's dom value and copying it over the cells innerHtml.

This is fine for one of renderings but is not enough for "interactive" components. As soon as your component is supposed to have Databindings and Events still working, this approach is too limiting.

### Suggested solution

What I'd propose instead is:

* provide an alternative angularUtilService.createAngularComponent (e.g. createInteractiveAngularComponent) so we dont introduce a breaking change
* the new method is: (see // INFO !!! for changes)

```typescript
createInteractiveAngularComponent<C>(component: Type<C>, targetElement?: Element, data?: any, createCompOptions?: CreateComponentOption): AngularComponentOutput {
    // Create a component reference from the component
    const componentRef = this.vcr.createComponent(component, createCompOptions);

    // Get DOM element from component
    let domElem: HTMLElement | null = null;
    const viewRef = (componentRef.hostView as EmbeddedViewRef<any>);

    // INFO !!! <------------ no longer wait for one cycle

    // get DOM element from the new dynamic Component, make sure this is read after any data and detectChanges()
    if (viewRef && Array.isArray(viewRef.rootNodes) && viewRef.rootNodes[0]) {
      domElem = viewRef.rootNodes[0] as HTMLElement;

      // when user provides the DOM element target, we will move the dynamic component into that target (aka portal-ing it)
      if (targetElement && domElem) {
        // INFO !!! <------------  replace with the nativeElement instead of just cutting out the body
        targetElement.replaceChildren(componentRef.location.nativeElement);
      }
    }

    return { componentRef, domElement: domElem as HTMLElement };
  }
```
* let the user handle the component destruction or be super-intelligent about how to automate it

---

I would create an PR introducing this new method, update the existing example to show an "interactive" component and add the tests. But I wanted to check back first with you @ghiscoding whether you think this is a useful general feature or we should keep developing this on ourselves.

### Additional context

To give some context about our use case.

We have a generic base grid implementation which abstracts away the communication with the backend and server-side paging/sorting ...

It's planned to support multiple grids, tables, spreadsheets and whatsoever. Now there is a set of premade CellComponents which we'd like to re-use.

Additionally we want to be able to declaratively modify the formatter, editor etc. of an individual column:

```html
<grid-slickgrid-container [gridId]="id" [providedFilterData]="filter$ | async">

    <button *gridCustomFormatter="'ResourceName'; let item;" mat-icon type="button" (click)="sayMyName(item.ResourceName)">{{ item?.ResourceName ?? "..." }}</button>
</grid-slickgrid-container>
```

so in this example the Dev can specify that the ResourceName column should render the button as custom formatter, and this than works with every grid type we have, be it Slickgrid a simple NG-Datatable or Material Table.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
Ah sure go ahead, I thought that the 1 cycle wait was mandatory but if you found a way to make it faster by not having to wait a cycle every time then yeah it's a win-win. A side note though, I think the AsyncPostRenderer is executed 1 at a time/1 after the other (not in parallel) but I'm not entirely sure since I barely use it. 

I'm working on another feature and I still have a few more days of work, so I guess I would be releasing sometime early next week and that could include your change if you have it done by then. Cheers

**Comment by zewa666** [comment]
its not about the waiting per se here. we simply dont destroy the component any longer and move its root element to the destination as opposed to waiting for the first cycle and than copying solely the innerhtml.

one after another might actually be true as you can see a cascading render effect in our large grid. but it doesnt actually matter in our case.

no probs with regards to releasing this right away. I'll come up with the PR and than we can see whenever it suites the next release at that time.
