### ISSUE TITLE
Row details is adding multiple times 

### ISSUE THREAD

**Issue by ananddotnetdeveloper** [ghiscoding/Angular-Slickgrid#136]
Hi, 
When click on the "+" icon , the  row detail is expanding , If we click multiple times or scroll outside of the rowdetailview , The rowdetailview component is loading multiple times, 

Here is the screen shot. 
The row detailview component is loading multiple time 
![image](https://user-images.githubusercontent.com/21267441/53753899-6acbfc00-3e80-11e9-8cd1-14b73fdd7b93.png)

. The Ng-component is adding multiple time , it is suppose to add only once 
![image](https://user-images.githubusercontent.com/21267441/53753961-918a3280-3e80-11e9-946f-3534a2a82375.png)

**I'm submitting a bug report**
**I'm submitting a feature request**

* **Angular Version:7
major.minor.patch

* **Library Version:**
major.minor.patch

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript 3.3

**Current behavior:**

**Expected/desired behavior: Expecting the rowdetailveiew to load only once 

* **What is the expected behavior? Expecting the rowdetailveiew to load only once 

* **What is the motivation / use case for changing the behavior?**

**Comment by ghiscoding** [comment]
This should be fixed under [version 2.4.1](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.4.1)

You could also up vote ⭐️ if you like the lib. Thanks 😸

**Comment by ananddotnetdeveloper** [comment]
Thanks for Quick response

**Comment by ghiscoding** [comment]
That helps when I'm in the middle of a release lol 😜

**Comment by ananddotnetdeveloper** [comment]
Can we set height of the row detail dynamically

**Comment by ghiscoding** [comment]
Hmm I don't know, I haven't used that feature much yet. The [SlickGrid Example](http://6pac.github.io/SlickGrid/examples/example16-row-detail.html) seems to have it. So I guess you'll need to use the plugin directly. 

Didn't test it, but something like this
```ts
changeRowDetailCount(rows) {
  if (this.angularGrid && this.angularGrid.extensionService) {
      const extension = this.angularGrid.extensionService.getExtensionByName(ExtensionName.rowDetailView);
      const rowDetailPlugin = extension.addon;
      const options = rowDetailPlugin.getOptions();
      options.panelRows = 10; // change number of rows
      rowDetailPlugin.setOptions(options);
  }
}
```

I can maybe add that later to the Example if that works. I think it should, I just copied some of the code from the original [code](https://github.com/6pac/SlickGrid/blob/master/examples/example16-row-detail.html#L187) of that [SlickGrid Example](http://6pac.github.io/SlickGrid/examples/example16-row-detail.html)

**Comment by ghiscoding** [comment]
I added it to the [demo - row detail](https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail), you can see it in action.

**Comment by ananddotnetdeveloper** [comment]
Thank you ,
 Do we have document  how to save the row detail data and retrieve  the data from them ?

**Comment by ghiscoding** [comment]
You'll have to look at the Examples, I don't have time to do more documentation. You can see the links for the examples in the previous [release](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.2.1)
