### ISSUE TITLE
How to open row details grid based on column value 

### ISSUE THREAD

**Issue by ananddotnetdeveloper** [ghiscoding/Angular-Slickgrid#140]
HI, 
When we use row details plugin , 
We have two options to open row detail view 
1. Clicking at the "+" icon 
2. on the row by making (useRowClick: true in row detail plugin).

Issue is i want to show the row detail based on selected value in row ,
For example 
Here based on the name i want to show the row detail,
I want to show when user select "Jhon" 
![image](https://user-images.githubusercontent.com/21267441/53763371-9c50c180-3e98-11e9-9419-4e4393c90149.png)

How can i achieve this functionality ?
 

**I'm submitting a feature request**

* **Angular Version: 7**
major.minor.patch

* **Library Version:**
major.minor.patch

* **Browser:**
all 

* **Language:**
TypeScript 3.3

**Current behavior:**

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by ghiscoding** [comment]
This is not currently supported and is not a problem with Angular-Slickgrid itself but with the core lib instead. I also contribute to the core lib and we recently did something similar but for the Row Selection by providing an override method, which you can see in this [PR #346](https://github.com/6pac/SlickGrid/pull/346), we can probably do the same kind of override with the Row Detail plugin. 

So in brief, it not currently supported and it has to be in the core lib first so it's available later in Angular-Slickgrid. It's probably going to take a few weeks or a month for this to be available here.

**Comment by ghiscoding** [comment]
I created [PR #351](https://github.com/6pac/SlickGrid/pull/351) to support that

**Comment by ananddotnetdeveloper** [comment]
Hi , 
i have installed angular-slickgrid 2.4.6, 
but   , i am not able use expandableOverride this  function, i think we need to wait until latest package

**Comment by ghiscoding** [comment]
This feature is now available under the latest version release [2.4.7](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.4.7)
