### ISSUE TITLE
Missing date formats in filter

### ISSUE THREAD

**Issue by melvinvdb** [ghiscoding/Angular-Slickgrid#141]
**I'm submitting a bug report**

* **Angular Version:**
7.2.7

* **Library Version:**
2.4.1

* **Browser:**
all 

* **Language:**
TypeScript 3.2

**Current behavior:**
When `dateTimeShortIso` is used as `formatter` and `outputType` the filter will be filtering only on dates without time.

**Expected/desired behavior:**
It should also filter with hour and minutes but outputs as 'Y-m-d H:i'.

**What is the motivation / use case for changing the behavior?**
In function `mapFlatpickrDateFormatWithFieldType` the following two cases are missing:
dateTimeShortIso: should be 'Y-m-d H:i'
dateTimeShortUs: should be ''m/d/y H:i'
now it reverts to the default case which is 'Y-m-d'.

**Comment by ghiscoding** [comment]
I'd be happy to have a PR fixing it.

**Comment by ghiscoding** [comment]
Available under the new [version 2.4.2](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.4.2).
