### ISSUE TITLE
Bug: invalid height when using autoHeight with filtering

### ISSUE THREAD

**Issue by melvinvdb** [ghiscoding/Angular-Slickgrid#143]
**I'm submitting a bug report**

* **Angular Version:**
7.2.7

* **Library Version:**
2.4.1

* **Browser:**
all

* **Language:**
TypeScript 3.2

**Current behavior:**
When autoHeight is enabled with filterable enabled the last row will not be visible.

**Expected/desired behavior:**
With autoheight and filterable enabled I expected every row to be visible. 

**What is the motivation / use case for changing the behavior?**
I'm not sure how to solve this issues but when testing with the autoHeight example and enabling filterable "Task 24" won't be visible anymore.

Sorry for the amount of bugs created today but apart from a few bugs this Grid is really great!

**Comment by ghiscoding** [comment]
This is (was) a problem in the core lib (SlickGrid) and we pushed a fix with [PR #342](https://github.com/6pac/SlickGrid/pull/342) but that won't be available in Angular-Slickgrid until there's a new version of SlickGrid. So you'll have to be patient on this one.

**Comment by melvinvdb** [comment]
A great that it is a known issue. I'll wait.

**Comment by ghiscoding** [comment]
Yeah we pushed it yesterday 😛

**Comment by melvinvdb** [comment]
There is still another issue though. Since autoHeight is set, the `gridPane` class still calculates its `newHeight` in `calculateGridNewDimensions`. This causes issues where my surrounding div is never able to set its height to the childrens height. See the `container-fluid` div in your autoHeight example. This div stays rendered as the display height instead of the height of the slickgrid. Giving the `container-fluid` div a background-color will reveal that.

**Comment by ghiscoding** [comment]
I added a condition in the ResizerService when `autoHeight` is set [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/resizer.service.ts#L196) but might have missed this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/resizer.service.ts#L199)

**Comment by melvinvdb** [comment]
Yep when moving this [https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/resizer.service.ts#L199](line) to [https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/resizer.service.ts#L196](that) statement solves the problem

**Comment by ghiscoding** [comment]
I added a PR to resolve the last issue, as for the other core lib problem, if you want to bypass that issue, what you can do in the mean time (before any new version of SlickGrid is out) is to copy the `slickgrid.js` from the core lib and overwrite it inside your `node_modules/slickgrid`. That is usually how I test my stuff anyway

**Comment by ghiscoding** [comment]
@melvinvdb 
I've pushed the PR #145 to fix the `autoHeight` with height that was incorrect. It's part of the new [version 2.4.2](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.4.2). 

As for the other issue you mentioned, it will be fixed only when SlickGrid releases a new version as well. This might take a couple weeks, so I'll leave this issue open to keep an eye on it.

**Comment by ghiscoding** [comment]
This should be fixed with latest version [2.4.4](https://www.npmjs.com/package/angular-slickgrid)
