### ISSUE TITLE
Detail row content is cleared when the grid columns are changed

### ISSUE THREAD

**Issue by joostvanbijsterveld** [ghiscoding/Angular-Slickgrid#1476]
### Describe the bug

In a grid with detail row functionality it is possible to expand the detail row.
The content in the detail area of the row is shown based on the data of the row.
However the content is no longer displayed when the columns of the grid are changed.

### Reproduction

- Go to https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail
- Expand the first row.
- Remove the column 'Finish' using the commands menu
- The content of the detail is now no longer shown.

![Bezigmetopnemen2024-09-25143619-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/69053e2a-4a4b-42cf-a398-59e69800a073)

### Expectation

The content of the detail row should remain visible when the columns of the grid are changed.

### Environment Info

```shell
Angular 18.2.2
Angular-Slickgrid 8.6.0
Typescript 5.4.2
Google Chrome 129.0.6668.60
Windows 11 10.0.22631
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Quick Start](https://ghiscoding.gitbook.io/angular-slickgrid/getting-started/quick-start).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Yeah Row Detail is a very special thing, every time the grid UI changes it has to call the `redrawAllViewComponents()` method and it looks like some command of the Grid Menu calls the redraw (like column reordered) but it's not being called for the column selection, it should be added for the `onColumnsChanged` event as well (I'm assuming you'll have the same problem with the Column Picker as well). For now you can call `redrawAllViewComponents()` yourself, see [Row Detail - Calling Addon Methods Dynamically](https://ghiscoding.gitbook.io/angular-slickgrid/grid-functionalities/row-detail#calling-addon-methods-dynamically)

```ts
this.gridOptions = {
  columnPicker: {
          onColumnsChanged: (_e, args) => rowDetailInstance.redrawAllViewComponents()
  },
  gridMenu: {
          onColumnsChanged: (_e, args) => rowDetailInstance.redrawAllViewComponents()
  },
}
```

https://github.com/ghiscoding/Angular-Slickgrid/blob/f9a96bf1caa95b3173dec1c46bc0583f4685a55c/src/app/modules/angular-slickgrid/extensions/slickRowDetailView.ts#L192-L212

A PR fix would be welcome, I'm assuming something like this should fix the issue (unit tests would also need to be updated)

```diff
this._subscriptions.push(
  this.eventPubSubService?.subscribe('onFilterChanged', this.redrawAllViewComponents.bind(this)),
+ this.eventPubSubService?.subscribe('onGridMenuColumnsChanged', this.redrawAllViewComponents.bind(this)),
+ this.eventPubSubService?.subscribe('onColumnPickerColumnsChanged', this.redrawAllViewComponents.bind(this)),
  this.eventPubSubService?.subscribe('onGridMenuClearAllFilters', () => window.setTimeout(() => this.redrawAllViewComponents())),
  this.eventPubSubService?.subscribe('onGridMenuClearAllSorting', () => window.setTimeout(() => this.redrawAllViewComponents())),
);
```

This Row Detail really has to be redrawn every time the UI changes and it happens so, so many times, I'm sure that there's even more events that are missed.

**Comment by joostvanbijsterveld** [comment]
Thank you for the solution, I hadn't gotten around to creating a PR myself yet.

**Comment by ghiscoding** [comment]
no problem, I actually wanted to test with the `grid.onRendered` event, it is being called more often covering most use cases. And if you haven't already, you can ⭐ if you like the project, cheers 😉

**Comment by ghiscoding** [comment]
So it turns out that using the `grid.onRendered` event is not ideal because this event is actually called way too often (it's called even when scrolling up/down) and this makes it worst on the perf side because we should only re-render the Row Detail when it comes back into the view (i.e. scroll to the bottom of the grid and then scrolling back to top, we should re-render at that time only, however with the scroll it was re-rendering a **lot** of times and this is bad).... So I will revert the PR #1480 and instead use the other 2 events that I proposed earlier in another PR.
