### ISSUE TITLE
Can't bind to ColumnDefinitions

### ISSUE THREAD

**Issue by ptrarun** [ghiscoding/Angular-Slickgrid#151]
I am using ionic 4 application.I am implemented slick grid functionality.I am refereed  Following  document 
https://github.com/settings/emails

**I am using ionic details**

Ionic:

   ionic (Ionic CLI)             : 4.10.2 
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 7

Angular CLI: 7.3.5

Node: 8.11.3
OS: win32 x64
Angular: 7.2.8
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.3.5
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0

**AppModule**
```ts
// @dynamic
@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [BrowserModule, IonicModule.forRoot(), AngularSlickgridModule.forRoot(), AppRoutingModule],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA,
    NO_ERRORS_SCHEMA
  ],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
```

I have followed document in step to step but i got following error so clarify my issue as soon as possible.

**Error :**
```shell
<core.js:15723 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'columnDefinitions' since it isn't a known property of 'angular-slickgrid'.
1. If 'angular-slickgrid' is an Angular component and it has 'columnDefinitions' input, then verify that it is part of this module.
2. If 'angular-slickgrid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <div class='container'>
    <angular-slickgrid gridId='grid1' 
    [ERROR ->][columnDefinitions]='columnDefinitions' 
    [gridOptions]='gridOptions' 
    [dataset]='dataset'>
"): ng:///HomePageModule/HomePage.html@10:4

Can't bind to 'gridOptions' since it isn't a known property of 'angular-slickgrid'.
```

**Comment by ghiscoding** [comment]
I have never used it with Ionic, so I don't know. Have you followed every steps from the [HOWTO](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step)? Looks like you're not loading Angular-Slickgrid properly somewhere. Maybe another suggestion would be to try to build the [Angular-Slickgrid Demo](https://github.com/ghiscoding/angular-slickgrid-bs4-demo) and then try to add Ionic to it.

**Comment by ghiscoding** [comment]
@ptrarun 
Did you fix your problem or is that still an issue? There's not enough info in this issue to troubleshoot or provide any help.

**Comment by ghiscoding** [comment]
Closing as no feedback was provided and this is not probably just a setup problem and not a real issue. I can reopen if more info is provided
