### ISSUE TITLE
CustomAngularComponent  with RowDetail Plugin

### ISSUE THREAD

**Issue by ananddotnetdeveloper** [ghiscoding/Angular-Slickgrid#155]
Hi , 
I am using CustomAngular Component (like Example 22 ), But when one row is getting expanded or closed the reload of Angular component is happening in each row. 
How to stop this reloading of angular component each and every time.
When there is a change in value of Angular component,'sgOnCellChange'  is not getting fired 
  

**I'm submitting a feature request**

Angular Version:7.2.4

*
* **Browser:**
all

* **Language:**
TypeScript 3.3

**Comment by ghiscoding** [comment]
Do you mean a mix of Example 22 and 23 with Row Detail View? If it's with Row Detail, then it's supposed to be the `loadOnce` flag. 

```ts
rowDetailView: {
        // load only once and reuse the same item detail without calling process method
        loadOnce: true,
```
For the `sgOnCellChange` to trigger, you need a change to happen in your object.

**Comment by ananddotnetdeveloper** [comment]
Load Once is working fine , but **Angular component is loading every time** on the row detail hide and expand.

**Comment by ghiscoding** [comment]
Sorry but I'm more a visual person and I can't visually figure out what your problem is because you haven't provided any code neither print screen. Still unsure of what your issue is.

**Comment by ananddotnetdeveloper** [comment]
Hi , 
Here is the code i am using for expand & collapse of the row Details 
rowDetail = this.angularGrid.extensionService.getSlickgridAddonInstance(ExtensionName.rowDetailView);
const options = rowDetail .getOptions();
for expand 
rowDetail .expandDetailView(item);

for collapse
rowDetail .collapseDetailView(item);

Can you help how to call this method "toggleRowSelection".

The problem of directly using expandDetailView and collapseDetailView is when we exapnd the  rowDetails with"expandDetailView " and do some changes that and close by calling "collapseDetailView ', when i open back that data is not getting saved

can you help me to get the latest updated data (or) will my issue get fix if i call toggle method

**Comment by ghiscoding** [comment]
I think you misunderstood how to use the Row Detail feature. You are **not supposed** to touch any of the `rowDetail` methods, except for the `getOptions()` to help you change some of the internal option of the Slickgrid plugin like `panelRows` which is shown in the example. So **do not** call `expandDetailView`, `collapseDetailView` or `toggleRowSelection` or any of them, these are all handled by the Angular-Slickgrid [RowDetailExtension](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts). If you override them you will potentially break the Row Detail feature (unless you want to recreate the entire extension yourself, which I really doubt you wish to do). 

The Row Detail behavior is that whenever it goes outside of the viewport cache (in other word, the row detail is no longer displayed in the screen), it will recreate the Angular Component once it comes back to that row and at that time it will use (I think) the last data that was used in that Component. That Component should have it's own way of saving to your backend, and I am assuming that if you saved and if you then scroll to the end of the grid and come back (or close/reopen the row) it should have the same value as before you left it. 

I have to admit that I did not use the Row Detail yet in any project, the only place I used it was in the [Example 21](https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail). I really don't know how it behaves with a Component that you use to save data, so far I only used it to display data. 

For example, if I change the input text and click on the button. It opens a javascript alert with the input text and if I scroll to the end of the grid and come back on top of the grid. The text is exactly as how I left it before, it also contains the same text as what was there before I started scrolling. The same is true if I open/close the Row Detail (that is if you use `loadOnce: true`, if it's set to `false`, it will reload every time). 
![2019-03-28_18-40-51](https://user-images.githubusercontent.com/643976/55197568-61853500-5189-11e9-94dd-1bd6daee0323.gif)

**Comment by ghiscoding** [comment]
was the post that I wrote earlier any helpful? 
If this is not a real issue and more of a question, I'd like to keep only issues open.
Can we close it?

Thanks for the feedback

**Comment by ghiscoding** [comment]
@ananddotnetdeveloper 
Unless you provide more feedback, I am inclined in closing this ticket since I don't think there's any issue with the library.

**Comment by ghiscoding** [comment]
closing as no feedback was provided and there is no obvious issue with the library itself.
