### ISSUE TITLE
Checkbox to select all items inside group

### ISSUE THREAD

**Issue by yongde01** [ghiscoding/Angular-Slickgrid#159]
How do I add a checkbox for grouping to select all the items inside the group ?

Thanks.

**Comment by ghiscoding** [comment]
Sorry but I don't have time to answer every questions, a few lately, I would rather keep issues for real issues not just questions. I don't think that I've done what you are describing, I suggest you to check all the examples from the core lib, [here](https://github.com/6pac/SlickGrid/wiki/Examples)

**Comment by yongde01** [comment]
Thanks. Need to change the GitHub code to make it work. Let me try on my
own.thanks.

**Comment by ghiscoding** [comment]
I'm not sure what you are referring to, but PR are welcome.

**Comment by ghiscoding** [comment]
Are you referring to maybe this SlickGrid [example](http://6pac.github.io/SlickGrid/examples/example-grouping-checkbox-row-select.html) from the core lib? If not please specify or I'll eventually close this issue since your question is not clear

**Comment by yongde01** [comment]
Hi,


Yes, i am referring to that. I have got it working with some css, and
coding added. However I notice that even the example given got some issue,
when playing with the example, I notice that even if I click on the group
with header collapsed,  and I go and expand it, some of the items in the
group was selected but not all. Anyway I may be force to find another grid.
Thanks

Yongde

**Comment by ghiscoding** [comment]
Yes that example still have couple of small issues and that is mostly why I didn't spend time in replicating that example in Angular-Slickgrid. You can see some of the small issues remaining in this [issue #165](https://github.com/6pac/SlickGrid/issues/165) on the core lib repo.

**Comment by yongde01** [comment]
No issue. Thanks a lot.

**Comment by ghiscoding** [comment]
If you don't mind then I would rather close this issue

**Comment by yongde01** [comment]
Hi,

Please close this. Actually I have got it working but I cannot leave with
the issues also. So I might be finding another grid. Anyway thanks. Please
close.

Yongde

**Comment by ghiscoding** [comment]
I would like to mention though that if you get it working and want to contribute to Angular-Slickgrid, I would be really happy to review and merge any good feature. Would you mind sharing a print screen of what you got working so far? What are the issues that you're having?

**Comment by ghiscoding** [comment]
Closing as this is more of a core lib issue

**Comment by ptatoChi** [comment]
Will this be a feature someday? :)

**Comment by ghiscoding** [comment]
No
