### ISSUE TITLE
backendServiceApi - calling from external button to load the grid 

### ISSUE THREAD

**Issue by Osmo123** [ghiscoding/Angular-Slickgrid#167]
How to call the backendserviceAPI process method without initializing the column definitions and grid options.

* **Angular Version:**
major.minor.patch

* **Library Version:**
major.minor.patch

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript X.X

**Current behavior:**
Currently on page load the grid pagination is loaded with default fields filters and page options by calling the backendserviceAPI process and post process.

**Expected/desired behavior:**
I have external buttons to load the grid data like Show all and refresh Buttons. But pagination process is not triggering in the grid options when I try to call the Process. The service is initializing and the process method is not triggering. It is only triggering when I make ngif false and load all the definitions and grid options. 

* **What is the expected behavior?**
I want to call the process method in the **backendserviceAPI** on binding the data without loading the grid again

* **What is the motivation / use case for changing the behavior?**

**Comment by ghiscoding** [comment]
Which Service are you using? I think you're using the GraphQL Service but I'm not sure since you didn't mention it. Assuming that it's GraphQL, you can set the option flag `executeProcessCommandOnInit` to false and call the backend process yourself. 

```ts
backendServiceApi: {
  service: new GraphqlService(),
  options: { 
    executeProcessCommandOnInit: false,
  },
  process: (query) => this.getCustomer(query)
}
```
to call the query, you can call the refresh method from the `PluginService`
```ts
export class MyClass {
  angularGrid: AngularGridInstance;

  angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
  }

  refreshDataset() {
    this.angularGrid.pluginService.refreshBackendDataset();
  }
}
```

**Comment by Osmo123** [comment]
Sorry to mention that, I am using ODataService. Can you please tell me how can I do with ODataservice

**Comment by Osmo123** [comment]
Thank you, It worked fine. I used ODataService for pagination. I added refreshDataset method and called it in my button click method.
