### ISSUE TITLE
Installed everything needed for the translate service and everything mentioned in the documentation, but still getting errors

### ISSUE THREAD

**Issue by eyandow** [ghiscoding/Angular-Slickgrid#172]
**I'm submitting a bug report**

* **Angular Version:**
7.2.14

* **Library Version:**
2.5.2

* **Browser:**
all 

* **Language:**
TypeScript 3.1.1

**Current behavior:**
Getting The following Error:
ERROR Error: StaticInjectorError(AppModule)[AngularSlickgridComponent -> TranslateService]: 
  StaticInjectorError(Platform: core)[AngularSlickgridComponent -> TranslateService]: 
    NullInjectorError: No provider for TranslateService!
Note, I have looked at all the previously closed bugs, followed the entire 'How To' step by step and we are still getting this error. We have Translate/core and translate/http-loader installed.  We have exhausted what we know and we need your help 💃 

**Expected/desired behavior:**
We do have more than one Locale. We will be translating from French to English and back. Even if we have to not do any translations on this grid that is fine. The grid doesn't render at all and only does the behavior mentioned above. The expected behavior is for the grid to render the data that we have in our dataset.

* **What is the expected behavior?**
NOTE: A this point, I am trying to do the basic rendering of the grid. Nothing crazy.  I will attach my package.json so you can take a look at it if needed.
Thank you!!!
[package.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/3133034/package.zip)

**Comment by diegosliver** [comment]
Hello!

Verify that the TranslateService is declared in the module in the session providers.

`@NgModule ({`
`  declarations: [`
`    AppComponent,`
`  ],`
`  providers: [ `
`    TranslateService`

Also check that your service is decorated with @Injectable()

`@Injectable `
`export class TranslateService { `
 `}

**Comment by ghiscoding** [comment]
@eyandow 
I suggest that you clone the working example referenced in the library [readme](https://github.com/ghiscoding/Angular-Slickgrid#working-demo). As @diegosliver pointed out, that looks like some setup problem `ngx-translate` and/or DI.

Note, I can't and won't open zip file (company policies)

**Comment by eyandow** [comment]
@ghiscoding 
Hey guys, Thanks for responding so quickly! We have already downloaded and cloned the repository for comparison to our project, and set it up just like the project. However, we are still getting the translate module error.
These are my providers(sorry, I can't get the lines to break):
`providers: [  
    PiDataService, 
  PIWebAPIService,  
    {
      provide: HTTP_INTERCEPTORS,  
      useClass: WinAuthInterceptor,
      multi: true
    },
    {
      provide: APP_INITIALIZER,
      useFactory: appInitializerFactory,
      deps: [TranslateService, Injector],
      multi: true
    },
    ColorService,
    ZoomWidgetService,
    GridOdataService,
    ResizerService,
    TranslateService
  ]`
I also have Injectable() decorating my service. I will continue to look through the provided repository and see if what I am missing. I am still getting the error though. Is there anything else it could possibly be? Do I need a newer typescript version?

**Comment by ghiscoding** [comment]
To better display the code, use 3 back ticks and the language, I usually do it like this for TypeScript. ` ```ts `  and don't forget to close all 3 as well. I edited your post with it.

You didn't paste your code for the App Module `imports`, but make sure that you import both Angular-Slickgrid and the Translate modules.

```ts
imports: [
  AngularSlickgridModule.forRoot(Globals.defaultGridOptions),
// ... and all the other ones
  TranslateModule.forRoot({
      // use a Custom Translate Loader
      loader: {
        provide: TranslateLoader,
        useClass: CustomTranslateLoader
      }
  }),
]
```
Are you using a Shared Module? If so, you need to make sure to export the `TranslateModule` module as well. Anyhow, the way I see it, your problem is not in Angular-Slickgrid but in how your use and import `ngx-translate` within your project. 

Maybe 1 last thing you can check, if you are using Angular 7 then make sure that you are using the correct `ngx-translate` versions, mine are the following
```json
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
```

**Comment by eyandow** [comment]
Cool, thanks for the tips :)
I got it to render :) It was the versions of ngx-translate/core and ngx-translate/http-loader that were causing the issue I believe. Thanks for your help!

**Comment by ghiscoding** [comment]
Great, you can also up vote ⭐️ if you like the lib to make it more visible 😃 
Cheers
