### ISSUE TITLE
How to set Grouping in group header

### ISSUE THREAD

**Issue by diegosliver** [ghiscoding/Angular-Slickgrid#177]
I wonder if there is some way to include the grouped column in the grouped columns header

I called the function viewData.setGrouping(array), it work fine, but not show in grouping header. 

![Capturar](https://user-images.githubusercontent.com/5364796/57194348-1f83a780-6f1c-11e9-9b41-bb9fe4ba5a35.PNG)

**Comment by ghiscoding** [comment]
The draggable grouping comes from this [example](http://6pac.github.io/SlickGrid/examples/example-draggable-grouping.html) of the core lib. So the functionality must be coming from the core lib

**Comment by diegosliver** [comment]
Tanks @ghiscoding
