### ISSUE TITLE
Other ideas for contributions and features

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/Angular-Slickgrid#18]
From @sabeurch in a different post
> Well, thinking especially about item editors: Those 2 facilities are in my planning, but milestone is not yet specified as other tasks in the work are taking my time:
1- Generic Formater, could be used to display different types of formatters in the same column.
2- Column Header Formatter, you already introduced the use of Header Button Plugin and Header Menu, but it will be better for other purposes usage to use formatters rather than plugins. Example, if we want to add a checkbox into the column's header, developer will find it much easier.
Some other minors, like
  1- Using jsonpath library, it will be easier for developer to just set the basic URL+Json Xpath like expression for the datagrid. Datagrid will be self updating itself.
  2- Also, image formatter based on based 64 encoded images. Images could be retrieved from DB& dynamically, no more need for assets folder. The idea comes from using "font awesome" or "glyphicon".

**Comment by ghiscoding** [comment]
@sabeurch 
Here's some of my answers

1. I have a `multipleFormatter` in my other repo Aurelia-Slickgrid, I forgot to copy it over to Angular-Slickgrid, but what it brings is the ability to provide multiple Formatters. They are in sequence, so the 1st formatter is the output that will be used for the 2nd formatter and so.
2. The Header Button and Header Menu plugins are just plugins that were brought from SlickGrid directly. They are quite flexible, I'm not sure if you can add checkbox into them, but possible yes, you ca refer to SlickGrid directly for that.
   - if you want more than that, they contributions are more than welcome
  - 1. I never use Xpath but use quite a lot JSON, not sure where you want to go with that but yes please make a contribution :)
  - 2. all my SASS files are programmed with the idea that if you don't like `Font-Awesome`, you can simply change the `font-family` and the necessary unicode of the icon. I like this concept and would push for future contributions to include them as well if they are related to styling (SASS)

**Comment by sabeurch** [comment]
@ghiscoding 
1- What I meant by formatter is the data renderers, which means one item renderer could serve for multiple ways to display data: It could display dates as calenders, choices as comboboxes, binary data as radio groups, etc...
2- i, I am planning to use jsonpath for Json static exprerssions , it is similar to Xpath for XML.
[](https://www.npmjs.com/package/JSONPath), we can perform queries on the json data, example: `Filter all books cheaper than 10, an expression will be: $..book[?(@.price<10)]`
ii- It is OK to use Font-Awesome  and Bootstrap Glyphicon for the display , more than that, using Base 64(or any form of encoding) images rendering in cells will let us dynamically display images without referring to their location in server folder like "./assets".
For grid that requires dynamic icons based on data content, it will not be easy to manage many icons and images in a folder.

**Comment by ghiscoding** [comment]
@sabeurch 
1. Sure you can already do that with a [Custom Formatter](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#custom-formatter), but if you think it could help others then we can surely make it a built-in Formatter. Contribution welcome
2. That topic is a little outside of my comfortable knowledge zone but if you think that you need to change the code to implement this then we can discuss it more.
   ii. whenever I see dynamic image, all I can think in my head is again a Custom Formatter. All the logic would go in the Formatter, not very hard to do.

**Comment by ghiscoding** [comment]
The [multipleFormatter](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/formatters/multipleFormatter.ts) is now available in latest [version 0.12.3](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v0.12.3).

This Formatter allow you to pipe multiple formatter. The output of the 1st Formatter will be passed to the 2nd Formatter and so on.

**Comment by sabeurch** [comment]
Good. it's powerful !

**Comment by ghiscoding** [comment]
@sabeurch 
Are you still planning on adding the features you talked about? Just curious...

I just released a new [version 0.13.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v0.13.0) today which brings some of the topics discussed here
- Multiple Formatter is used in the Editor example demo, see this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-editor.component.ts#L104) and this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-editor.component.ts#L109)
- SingleSelect and MultipleSelect Editors were added
- There was a problem with the OData sample, where a change to the grid option pagination object wasn't triggering a dirty check, hence breaking the Pagination. I'm not sure if you have this problem on your side with my latest version, but you should take a look at this [patch](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-odata.component.ts#L96) to force a dirty check.

**Comment by ghiscoding** [comment]
@sabeurch 
Any updates? This issue seems to be more on your side than mine.

**Comment by sabeurch** [comment]
@ghiscoding 
The major thing I am planning to add is the **grid header renderer**, which should be based on a formatters (Like the cell formatting).
Until now, I have no enough time to go back to the Angular project as I am assigned to many projects simultaneously (Flex into Angular migration is one among 4 projects).
**The Custom Formatter**, that will display data in different formats within the same column is useful for transposed datagrids. Example: We can transpose a row and display it into a one column, this way a multipurposes formatter is what we want. Maybe a new functionality transpose grid ?
I am sorry for not having a clear deadlines for my proposals (a rough estimation will be within 1 month and half for my 2 points).

**Comment by ghiscoding** [comment]
@sabeurch 
If it's only a month or two, I can leave it open but if we are talking over 6 months period, I would rather close it. 

You can build your own [Custom Formatter](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#custom-formatter), the latest version of SlickGrid also includes an extra optional 6th arguments which is the grid object. This extra argument is rather useful to pull gridOptions `params` (for example, I pass the translate service instance in the `gridOptions.params: { i18n: this.translate }`.

Your issue seems to be really all related to Custom Formatter, isn't it?

**Comment by sabeurch** [comment]
@ghiscoding 
Yes for both header and cells

**Comment by ghiscoding** [comment]
@sabeurch 
I am currently working in a new Major Version (with breaking changes) and I'm not sure if you will provide more work on this issue but I will close it for spring cleaning. We can re-open in the future if need be. Thanks
