### ISSUE TITLE
Detailview Scrollbar

### ISSUE THREAD

**Issue by Yuof** [ghiscoding/Angular-Slickgrid#180]
**I'm submitting a bug report**

* **Library Version:**
2.5.5

* **Browser:**
all

**Current behavior:**
When using Detailview the Detailcomponent always has a Scrollbar even if its small enough to fit.

Reproduce:
1. https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail 
2. Open a Detailview
3. Every Detailview has a Scrollbar

**Expected/desired behavior:**
No scrollbar if component is small enough.

**Comment by Yuof** [comment]
i tried both and none worked. It still gets overwritten somewhere else.

**Comment by Yuof** [comment]
> 
> 
> Ah I thought I had fixed that in the core lib, as it was discussed [here](https://github.com/6pac/SlickGrid/pull/351#issuecomment-469947531), but it looks like I was waiting for an answer and push a commit without the change. I'll make another PR on the core lib soon, but it might take a few weeks before any new release is out on the core lib since it's not updated as often.
> 
> In the mean time, I'm not sure if that would work, but the problem is on the `<div class="detail-container">`, the `min-height` has to be removed. I did not tested it, but maybe trying to reset the `min-height` like this would work !?
> 
> ```css
> .detail-container {
>   min-height: initial !important;
> }
> ```
> 
> or set it to 0 if that didn't work.

I tried both and none worked. It still gets overwritten somewhere.

**Comment by ghiscoding** [comment]
If that didn't work, you'll have to wait for the fix to be available in the core lib (6pac/SlickGrid). Like I said, this might take few weeks though.

**Comment by Yuof** [comment]
`document.getElementsByClassName("detail-container")[0].setAttribute("style", "min-height: 0;"); `
worked as an hack for now.

Thank you for the advice!

**Comment by ghiscoding** [comment]
PR [#370](https://github.com/6pac/SlickGrid/pull/370) raised on core lib

**Comment by ghiscoding** [comment]
Now released under version [2.7.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.7.0)
