### ISSUE TITLE
Collapse opened rowDetail on selecting expanding a new one

### ISSUE THREAD

**Issue by bandhammanikanta** [ghiscoding/Angular-Slickgrid#194]
Hi @ghiscoding,

It is regarding 'row details view'. I just wanna have only one 'row details' opened at a time. If there is one already opened, on expanding a new one, should collapse the other row details.
Please assist me. 

Thank you.
happy coding.

**Comment by ghiscoding** [comment]
There is no such options in the core lib, so Angular-Slickgrid does not have it either

**Comment by ghiscoding** [comment]
I created a PR that got merged in the core lib, now waiting for a new version of the core lib SlickGrid to be released. I have no control over that, so we'll have to be patient.

**Comment by ghiscoding** [comment]
Now fixed under version [2.7.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.7.0)
