### ISSUE TITLE
Error while deleting new rows created while pasting from excel

### ISSUE THREAD

**Issue by reejeshkv** [ghiscoding/Angular-Slickgrid#198]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           |^6.0.3
| Angular-Slickgrid |^1.9.6
| TypeScript        |~2.7.2
| Operating System  |
| NPM/Node/Yarn     |

### Context
Requirement is we need to delete the extra rows created while we copying and pasting from excel sheet. I couldn't find any event handler like onAfterPasteFromExcel() or onUpdateGrid() to do that. So I have written a method which is called in onCellValueChange() and here I have wrote code to check for rows which all having id starting with "newRow_" and trying to delete it.

I am getting the below error.. The newly created rows are deleted successfully but in console i am seeing the javascript errors. (Jul 17 is column name)

```
core.js:1598 ERROR TypeError: Cannot read property 'Jul 17' of undefined
    at Object.execute (slick.cellexternalcopymanager.js:245)
    at Object.queueAndExecuteCommand (angular-slickgrid.js:1213)
    at Object.clipboardCommandHandler (angular-slickgrid.js:1173)
    at _decodeTabularData (slick.cellexternalcopymanager.js:320)
    at slick.cellexternalcopymanager.js:422
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4053)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
```

### Expected Behavior
 The newly created rows should be deleted. 

### Current Behavior
 The newly created rows are deleted successfully but I am getting the error in console.

### Possible Solution
 It could be good if we have some eventhandler like onAfterPasteFromExcel() so that I can delete those new rows and delete.

### Code Sample
My code snippet : I have called checkForNewRows() method from onCellValueChange() eventHandler
```ts 
checkForNewRows() {
    let newRows : any = [];
    this.formattedData.forEach((row,key) => {   
      let idStr = row.id.toString(); 
      if(idStr.indexOf('newRow_') != -1) {
        newRows.push(idStr);
      }
    });
   // Delete one row for testing
    if (newRows.length > 0 ) { 
      this.angularGrid.gridService.deleteDataGridItemById(newRows[0]);
    }
  }
```

**Comment by ghiscoding** [comment]
It's really hard to help you without any sample. However my guess is that you are maybe deleting the row too early, the error thrown comes from the `cellexternalcopymanager` core plugin. Perhaps what you can try, just to see if that is the problem, add a `setTimeout` of a second to delay the delete, so that it happens after every cells are pasted. 

As for the events on that plugin, they are all [here](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.cellexternalcopymanager.js#L466) in the core plugin but I forgot to expose them in Angular-Slickgrid (I will do that in future release). However you can always get the reference to all the core plugins (or controls) with this line
```ts
angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
}

onPastedCells() {
  const copyInstance = this.angularGrid.extensionService.getSlickgridAddonInstance(ExtensionName.cellExternalCopyManager);
  copyInstance.onPasteCells((e, args) => {
    console.log(args.ranges);
  });
}
```
I think your code is fine with the `onCellValueChange` but maybe too early.

**Comment by ghiscoding** [comment]
@reejeshkv 
I added a new Grid Option `excelCopyBufferOptions` with the SlickGrid events you can hook to, that was added in PR #205 , you can see an example of the events [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/dee9e0488248905a5d2b68b03c52ad5cda92fa50/src/app/examples/grid-formatter.component.ts#L59)

Release to follow shortly

**Comment by ghiscoding** [comment]
Closing since I got no feedback provided and the addon/plugin events are now exposed, as describe in previous [post](https://github.com/ghiscoding/Angular-Slickgrid/issues/198#issuecomment-495680194).
