### ISSUE TITLE
How to preset filter values on filter row with GridOdataService

### ISSUE THREAD

**Issue by audrys** [ghiscoding/Angular-Slickgrid#206]
Hello,
Thanks for great tool.
I need to preset some values into filter row. For the filtering I am using OData filtering.
BR
Audrius

**Comment by ghiscoding** [comment]
Start by looking at the Wikis I've done, that would be a good first step... [Wiki - Presets](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-State-&-Preset)

**Comment by audrys** [comment]
Hi,
I checked this documentation, but there is no info how to set with backendServiceApi. In my situation, I have got response from the server with filtered values (filtered from code, not from filter event).
I need to set filters parameters to filter row. I'm using:
let f: CurrentFilter[] = [{
      columnId: "user",
      operator: "a*",
      searchTerms: ["t"]
          }];
    let new_cf = [...this.gridOptions.presets.filters, ...f];
    this.gridOptions.presets.filters = new_cf;
But filters in filter row does not changing.
Do I need to reset state?
Thanks in advance
Audrius

**Comment by ghiscoding** [comment]
Grid Presets works with/without backend service. However the name suggest, it's a **preset**, it will only works on first page load and never after. You cannot change it after, you can only set it in your grid option when you declare you grid definitions and options and then see the filters showing up on page load.

**Comment by ghiscoding** [comment]
@audrys 
Unless you provide more info, I'm thinking of closing this issue since it was more of a question and not really an issue.

**Comment by ghiscoding** [comment]
Closing as no feedback was provided and I don't think there is any issue with the lib

**Comment by ghiscoding** [comment]
Reopening, since after starting to work on the unit tests, it seems that this was not fully implemented in the GridOData Service, so I'll have to review that later. We use only the GraphQL Service nowadays, which is why the OData one might be missing some of these features.

**Comment by ghiscoding** [comment]
The GridOData Service is now working correctly with Presets, you can see the updated [Example 5](https://ghiscoding.github.io/Angular-Slickgrid/#/odata) that now has presets. I have to mention again that Presets is **only** for the initial page load.
