### ISSUE TITLE
Slick grid jasmine test cases

### ISSUE THREAD

**Issue by reejeshkv** [ghiscoding/Angular-Slickgrid#210]
Any sample jasmine test cases written for Slick grid samples ?

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           |
| Angular-Slickgrid |
| TypeScript        |
| Operating System  |
| NPM/Node/Yarn     |

**Comment by ghiscoding** [comment]
All the tests that I wrote are made with Jest, which is very similar to Jasmine. However these tests are strictly for the library itself, not for testing values or anything like that. The biggest focus right now is to increase the code coverage by adding tests for the library itself, I only started writing these tests about 2 months ago. There no plans, at least not now, to create any external facing testing methods.

**Comment by ghiscoding** [comment]
Closing this since the question was answered
