### ISSUE TITLE
Cell Button like header button

### ISSUE THREAD

**Issue by Sakkanan** [ghiscoding/Angular-Slickgrid#213]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           |7|
| Angular-Slickgrid |2.6.0
| TypeScript        |
| Operating System  |
| NPM/Node/Yarn     |

### Context

Need to add action buttons   on a row depending on the row-data-set. List of actions depends on the row data-set. (Success / Failure / types ). 

### Expected Behavior
Ability to add buttons at the cell level, like header buttons 

### Current Behavior
Currently (click) action per cell is allowed; unable to add multiple actions in a cell

### Possible Solution
like header buttons 

Thank you very much for the library and your time

**Comment by ghiscoding** [comment]
You can add button(s) through Custom Formatters then use the `onCellClick` to decide what action to do. If you want different type of button(s) depending on some of the item object properties, well it's just logic inside your Custom Formatter. The Formatters can be string and/or HTML.

**Comment by ghiscoding** [comment]
Here's a demo in our current project, it's connected to a backend service and once I get the response back and refresh the row, it changes the icon. So it's not really hard to do, it's a simple Custom Formatters which changes the icon depending on a flag (`isAllowed` in my item property) 

![2019-05-31_12-37-40](https://user-images.githubusercontent.com/643976/58720736-01855780-83a1-11e9-951b-d1378819cdfb.gif)

**Comment by Sakkanan** [comment]
Thank you ! I was able to implement.

**Comment by ghiscoding** [comment]
That is good news, just so you know, I added a demo that basically does what I posted in the animated gif in previous post, I added it in this [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/b9f6aa7c96d42417569834f96efd6ca9253605ee), it will be shown in the Formatter example by next week. 

Cheers ⭐️
