### ISSUE TITLE
Slickgrid in multiple tabs(bootstrap4)

### ISSUE THREAD

**Issue by bandhammanikanta** [ghiscoding/Angular-Slickgrid#219]
HI ghiscoding,

Slickgrid table is not working in multiple tabs(boostrap-angular 7). Here is my code.

Parent.html:
>`<div class="container">`
>`        <tabset>`
>`            <tab heading="Basic title" id="tab1">`
>`                <child-child></child-child>`
>`            </tab>`
>`            <tab heading="Basic Title 1">`
>`                <child-child></child-child>`
>`            </tab>`
>`        </tabset>`
>`    </div>`

**child.html:**
`<div id="grid1" class="container-fluid">`
         `<angular-slickgrid gridId="grid1" [columnDefinitions]="columnDefinitions1" [gridOptions]="gridOptions1"
        [dataset]="dataset1" gridHeight="300" gridWidth="800">
    </angular-slickgrid>`
`</div>`

**child.component.ts:**
`import { Component, OnInit } from '@angular/core';`
`import { Column, GridOption } from 'angular-slickgrid';`

`@Component({`
`  templateUrl: './child.component.html',`
`  selector: 'child-child',`
`})`
`export class ChildComponent implements OnInit {`

`  columnDefinitions1: Column[];`
`  columnDefinitions2: Column[];`
`  gridOptions1: GridOption;`
`  gridOptions2: GridOption;`
`  dataset1: any[];`
` grid1: number;`
`  grid: any;`
` `
` ngOnInit(): void {`
`    this.grid1 = Math.random() * 100;`
 `   this.columnDefinitions1 = [`
  `    { id: 'title', name: 'Title', field: 'title', sortable: true },`
   `   { id: 'duration', name: 'Duration (days)', field: 'duration', sortable: true },`
    `  { id: '%', name: '% Complete', field: 'percentComplete', sortable: true },`
     ` { id: 'start', name: 'Start', field: 'start' },`
      `{ id: 'finish', name: 'Finish', field: 'finish' },`
`      { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', sortable: true }`
`    ];`
`    this.gridOptions1 = {`
`      enableAutoResize: false,`
`      enableSorting: true`
`    };`
` `
`    // mock some data (different in each dataset)`
`    this.dataset1 = this.mockData();`
`  }`
` `
`  mockData() {`
`    // mock a dataset`
`    const mockDataset = [];`
`    for (let i = 0; i < 1000; i++) {`
`      const randomYear = 2000 + Math.floor(Math.random() * 10);`
`      const randomMonth = Math.floor(Math.random() * 11);`
`      const randomDay = Math.floor((Math.random() * 29));`
`      const randomPercent = Math.round(Math.random() * 100);`
` `
`      mockDataset[i] = {`
`        id: i,`
`        title: 'Task ' + i,`
`        duration: Math.round(Math.random() * 100) + '',`
`        percentComplete: randomPercent,`
`        start: `${randomMonth}/${randomDay}/${randomYear}`,`
`        finish: `${randomMonth}/${randomDay}/${randomYear}`,`
`        effortDriven: (i % 5 === 0)`
`      };`
`    }`
`    return mockDataset;`
`  }`
`}`

**In the UI, I can see a thin horizontal line, instead of slickgrid table**

![image](https://user-images.githubusercontent.com/39230890/59155928-9deddf00-8ab0-11e9-958e-ab7f8d64b9c4.png)

Please suggest. Thank you in advance.

**Comment by ghiscoding** [comment]
This is a limitation of SlickGrid itself, not Angular-Slickgrid. Basically the issue is that SlickGrid doesn't work well with hidden DOM element, so the next tabs are hidden and SlickGrid cannot resize well. It might work to manually call a resize after switching tabs. I suggest you to google all of that.

**Comment by ghiscoding** [comment]
I added a demo with ngx-bootstrap Tabs, there isn't much special about it. The only thing that I did as extra was to resize the grid after I click on the 2nd tab, which I spoke in my previous comment. 

You can see the new [Example 24](https://ghiscoding.github.io/Angular-Slickgrid/#/gridtabs) and the [Component](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-tabs.component.ts)
