### ISSUE TITLE
Angular 4 Compatibilty

### ISSUE THREAD

**Issue by MasiGit** [ghiscoding/Angular-Slickgrid#220]
Not able to get it work with Angular 4.
On compilation receving the following error

ERROR in C:/AllData/Workspace/Projects/slick/node_modules/angular-slickgrid/app/modules/angular-slickgrid/models/operatorType.enum.d.ts (3,13): In ambient enum declarations member initializer must be constant expression.

package.json dependencies

"dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.0",
    "ag-grid-angular": "^20.2.0",
    "ag-grid-community": "^20.2.0",
    "angular-slickgrid": "^1.9.6",
    "bootstrap": "^3.4.1",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.4.1",
    "lt-themify-icons": "^1.1.0",
    "ng2-breadcrumb": "^0.5.14",
    "ngx-bootstrap": "^1.8.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.2.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }

**Comment by ghiscoding** [comment]
Seems that you need at least TypeScript 2.4 as mentioned in this other [project](https://github.com/swimlane/ngx-ui/issues/95). I would suggest you to upgrade to Angular 5, there isn't much different with Angular 4, the biggest jump is to Angular 6.

Sorry I cannot help you more than that, I don't support older version that far away.

**Comment by MasiGit** [comment]
Thanks..Upgrading to 2.4 solved the issue.

**Comment by ghiscoding** [comment]
Good to hear that fixed it

Cheers ⭐️
