### ISSUE TITLE
can i use Bootstrap 4

### ISSUE THREAD

**Issue by harryhahn2** [ghiscoding/Angular-Slickgrid#23]
We are using BS 4 in our Project. Can we use Angular-Slickgrid ?

Thanks

**Comment by ghiscoding** [comment]
Side note, the Bootstrap in the lib is much more of a Theme than anything else. I would be surprise of any big problems. I would be happy if you can confirm that. Thanks

**Comment by ghiscoding** [comment]
@harryhahn2 
Have you had a chance to try it with BS4 ?

**Comment by ghiscoding** [comment]
@harryhahn2 
It now fully works with Bootstrap 4, I also created a new repo with a new [Angular-Slickgrid - Bootstrap 4](https://ghiscoding.github.io/angular-slickgrid-bs4-demo) demo. So go take a look at it.

Some more comments, all BS4 support fixes were made through this [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/e4674253d7461332bcc2ec1223e2f923d40a7068), however it is worth to know that prior to that commit, only a very small subset of features weren't correctly working, that were mainly the Compound Filters. All of which got updated and tested with BS4. 

If you like and use the lib, please upvote ⭐️  
Cheers

**Comment by kamlesh0606** [comment]
Hi,

Can i use bordered-table css of bootstrap?

Ref. https://getbootstrap.com/docs/4.3/content/tables/#bordered-table

Thanks

**Comment by ghiscoding** [comment]
There's 300 [SASS variables](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Styling), that is how you'll get to do that. This lib has a Bootstrap theme, however it is **not** a Bootstrap table.

**Comment by kamlesh0606** [comment]
Thanks For above help.
