### ISSUE TITLE
Column Picker & Grid Menu not updated after dynamically updating column definitions

### ISSUE THREAD

**Issue by rihabJaballah** [ghiscoding/Angular-Slickgrid#233]
Hello, It' s possible to re-create header menu after grid initialization with new columns definition?
In previous version 1.1... this code  worked fine  : 

```
this.controlAndPluginService.userOriginalGridMenu ={ ...this.angularSlickGrid.gridOptions.gridMenu };
this.controlAndPluginService.createGridMenu(this.gridObj, this.columnDefinitions);
```
 but no more .... thanks.

**Comment by ghiscoding** [comment]
The Grid Menu is a standalone piece, it's handled internally by the library itself, you're not supposed to re-create it. If it was available in previous version, that was a mistake. 

However, after trying the [Example 3](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) and click on the button to "Add Dynamically a Title Column", I see that the Grid Menu doesn't update with the new column. That might be a bug that I would need to investigate.

**Comment by ghiscoding** [comment]
Adding a new column definition, now works correctly and both Column Picker & Grid Menu will have their list of column titles refreshed. See [Example 3](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) and [Example 12](https://ghiscoding.github.io/Angular-Slickgrid/#/localization) to see how to add a Column Definition dynamically. 

Cheers ⭐️
