### ISSUE TITLE
Dynamic frozen columns 

### ISSUE THREAD

**Issue by husyer** [ghiscoding/Angular-Slickgrid#242]
Hello Ghiscoding,

I am having trouble setting up frozen columns when columns are 
loaded dynamically from a webservice.

If i define **gridOptions** before loading **columnDefinitions** it's not working.

If i update the grid options using **gridObj.setOptions** after everything is loaded slickgrid turns blank.

Last thing i tried is to define **gridOptions** right after columns are loaded it's not working neither (gridId is undefined).

Do you have clues of what i am doing wrong and is it even possible to have pinned columns when they are loaded from a webservice ?

Thank you so much for the great work.

**Comment by ghiscoding** [comment]
I personally never load column definition dynamically, I always define my `gridOptions` then `columnDefinitions` one after the other at the same time. When I have to wait for an API call to receive some info that I need to use for the `columnDefinitions`, I simply put an `ngIf` in the View for the `<angular-slickgrid>` to be created after I get the info back. For an example, we do that in our project with user permissions, depending on the user role, we display/hide certain columns in the grid and for that I must create the grid with the `ngIf`. You have to know that the grid must have all its options and definitions set and ready prior to using it, adding a column definition dynamically is doable but never ever add them all up dynamically, that is not a good approach,

**Comment by husyer** [comment]
This component was not made by me i will rebuild it without dynamics columns when i find so time. 
In the mean time i will simply use a ng-if as you suggested.

Thank you very much.
