### ISSUE TITLE
How to open context menu on right click, using Angular 7?

### ISSUE THREAD

**Issue by doll612** [ghiscoding/Angular-Slickgrid#248]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 7.1.4
| Angular-Slickgrid | 2.9.8
| TypeScript        | 3.1.6
| Operating System  | win 10
| NPM/Node/Yarn     | 6.4.1/10.13.0

### Code Sample

Thanks,

**Comment by ghiscoding** [comment]
Are you talking about this, shown at the bottom?
I've never done any implementation or need such thing, but you can easily reproduce by using the SlickGrid grid object (and maybe the DataView object as well) directly. It's not a plugin or anything, it's just plain DOM element with jQuery events attached to them. I'm sure you can reproduce that easily. 

![image](https://user-images.githubusercontent.com/643976/61997509-7b1f8600-b070-11e9-92fb-7559b7a230dd.png)

**Comment by coolrb** [comment]
We have implemented this functionality using a mix of jquery code. 
First you need to define menu - html in your component like

```
> <ul id="contextMenu" style="display:none;position:absolute">
>   <b>Set priority:</b>
>   <li data="Low">Low</li>
>   <li data="Medium">Medium</li>
>   <li data="High">High</li>
> </ul>
And then define a method in your component to actually show the context menu
```
contextMenu(e){
    console.log('Event ',e);
    e.preventDefault();
    const eventData = e.detail.eventData;
    var cell = this.angularGrid.slickGrid.getCellFromEvent(e);
    var x = e.pageX - 250;// $(e.target).offset().left;
    $("#contextMenu")
        .data("row", cell.row)
        .css("top", e.pageY)
        .css("left", x)
        .show();
    $("body").one("click", function () {
      $("#contextMenu").hide();
    });
  }
```
And finally calling this in rowSelection event like
`this.contextMenu(evt);`
You need to have jquery installed

**Comment by ghiscoding** [comment]
Thanks for the code sample, I knew it wasn't that hard to implement with raw javascript/jQuery code.

> You need to have jquery installed

jQuery is a dependency of this library, so you have no choice but to have it installed 😉

**Comment by ghiscoding** [comment]
not yet released it will come in the new year

**Comment by ghiscoding** [comment]
@doll612 @coolrb 
This is now live as a new feature. Check out latest [version 2.15.x](https://github.com/ghiscoding/Angular-Slickgrid/releases)

**Comment by doll612** [comment]
Thanks, @ghiscoding.
