### ISSUE TITLE
When we hide any column, row's multi-select checkbox column disappear

### ISSUE THREAD

**Issue by pranayshinagare** [ghiscoding/Angular-Slickgrid#250]
row selection checkbox column hides when we hide any column in slickgrid menu. Is there any workaround for this ?

**Comment by ghiscoding** [comment]
I'm aware of it, assuming that your 1st row is using the `excludeFromGridMenu`, if that is the case then the problem was fixed in the core lib with this [PR #402](https://github.com/6pac/SlickGrid/pull/402) in the core lib.

**Comment by ghiscoding** [comment]
Adding the "on hold" tag, just to mention that I'm waiting for a new NPM release of the core lib (SlickGrid) in order to have the fix showing up in Angular-Slickgrid. I'm expecting a new version of the core lib sometime this week or the following week.

**Comment by pranayshinagare** [comment]
Thanks for quick response..

**Comment by ghiscoding** [comment]
Side note, please use and fill in the provided Issue Template when creating a new issue. It's only a couple of questions and helps identifying the real issue. Thank you

**Comment by ghiscoding** [comment]
The core lib new version is out and I added new Cypress E2E tests to cover this issue, it seems all good now. However I'm not expecting to release a new version of Angular-Slickgrid until at least next week, I'm working on new features and I'd like to release them all at same time.

**Comment by ghiscoding** [comment]
The fix is now pushed with the new version [2.10.1](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

If you like the lib and you haven't already up vote, please do so.. ⭐️ 😸 
Thank you

**Comment by pujapradhan10** [comment]
I have upgraded version to 2.10.1 but still have same issue. This is not working for me. Any other solution for it, to always show checkbox column.

**Comment by ghiscoding** [comment]
@pujapradhan10 
What you're asking for is completely different and not related to this issue. I don't fully understand your question about always showing the checkbox? If you mean to display checkbox for all column including the checkbox row, then there's nothing to do (just to use any of the exclude flag), that is the default. If you mean to always show the picker, then that is not doable and I don't why you would want to do that.
