### ISSUE TITLE
Rowdetail view close expanded/hide programmatically

### ISSUE THREAD

**Issue by ddbailon** [ghiscoding/Angular-Slickgrid#271]
Hello, Is there a way to programmatically close/hide an expanded rowdetail view after clicking a button inside the rowdetail view.  Thank you in advance.

**Comment by ghiscoding** [comment]
Refer to the new [Wiki - Row Detail](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Row-Detail#calling-addon-methods-dynamically)

Cheers, please up vote ⭐️ if you haven't already, thanks 😺

**Comment by ddbailon** [comment]
Thank you @ghiscoding
