### ISSUE TITLE
Adding columns definitions in presets of grid options does not show the checkboxes

### ISSUE THREAD

**Issue by vaibhavzambad** [ghiscoding/Angular-Slickgrid#276]
I'm submitting a bug report

**Angular Version:**
8.1.1

**NPM Package Version:**
2.10.5

**Browser:**
Chrome 76.0.3809.132 (64-bit)

**Language:**
TypeScript 3.4.5

**Context :** 

I am trying to get the multiple/single selection feature of the grid with the column definitions in presets. Due to this issue, I am not able to achieve the same.

**Current Behavior :**

Adding columns definitions in presets of grid options does not show the checkboxes (for both the single and mutiple selection) in the whole grid.

**Expected Behaviour :** 

Adding columns definitions in presets of grid options should show the checkboxes and support both the single and multiple selection.

**Code Sample :** 

Please find the code sample here : 
https://github.com/vaibhavzambad/Angular-SlickGrid-Issue/

Thanks a lot.

**Comment by ghiscoding** [comment]
Same answer I gave [here](https://github.com/ghiscoding/Angular-Slickgrid/issues/277#issuecomment-531779071)
