### ISSUE TITLE
Adding columns definitions in presets of grid options does not show the row-detail buttons in the whole grid.

### ISSUE THREAD

**Issue by vaibhavzambad** [ghiscoding/Angular-Slickgrid#277]
I'm submitting a bug report

**Angular Version:**
8.1.1

**NPM Package Version:**
2.10.5

**Browser:**
Chrome 76.0.3809.132 (64-bit)

**Language:**
TypeScript 3.4.5

**Context :** 

I am trying to get row detail feature of the grid with the column definitions in presets. Due to this issue, I am not able to achieve the same.

**Current Behavior :**

Adding columns definitions in presets of grid options does not show the row-detail buttons in the whole grid.

**Expected Behavior :** 

Adding columns definitions in presets of grid options should show the the row-detail buttons in the whole grid.

**Code Sample :** 

Please find the code sample here : 
https://github.com/vaibhavzambad/Angular-SlickGrid-Issue/

Thanks a lot.

**Comment by ghiscoding** [comment]
The column to show the icon is added automatically when setting `enableRowDetailView: true` and so you will never get it by reassigning `this.columnDefinitions`, that is your local column definitions which does not include the updated definitions with the icon column. You can get the entire list of column definitions by calling `getColumns()` on the [Grid Object](https://github.com/ghiscoding/Angular-Slickgrid/wiki/SlickGrid-&-DataView-Objects) and that should work

```ts
angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;

    // the Angular Grid Instance exposes both Slick Grid & DataView objects
    const entireColumnDefinitions = angularGrid.slickGrid.getColumns();
  }
```

Please note that Row Detail is not, and will not, be part of the `presets` feature. The Grid State/Presets is only meant for Grid Filtering, Sorting & Column Position.
