### ISSUE TITLE
I would like to ask how can I check the status of a row detail if it is expanded

### ISSUE THREAD

**Issue by ddbailon** [ghiscoding/Angular-Slickgrid#279]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           |
| Angular-Slickgrid |
| TypeScript        |
| Operating System  |
| NPM/Node/Yarn     |

**Comment by ghiscoding** [comment]
Angular-Slickgrid is just a wrapper of [SlickGrid](https://github.com/6pac/SlickGrid) core library, all the documentation on the Row Detail plugin can be found [here](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js) directly in the core library plugin itself. I don't think what you are looking for exists, but again take a look at the documentation [here](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js)
