### ISSUE TITLE
Dynamically Duplicate Title Column in sample 12 does not work in ng build --prod

### ISSUE THREAD

**Issue by tannenbaums** [ghiscoding/Angular-Slickgrid#281]
I'm submitting a Bug report

Your Environment
| Angular 7.2.15
| Angular-Slickgrid 2.10.5|
| TypeScript 3.2.4 |
| Operating System: windows 8 |
| NPM/Node/Yarn NPM 6.0.0 |

Context
I took the code in sample 12 and put it in my project. Everything works in dev. When publish using ng build --prod everything works including all the features of angular slickgrid except for dynamically duplicate title column, no columns are added in the screen. I can see that the array has the new columns but it's not being picked up by angular change detection.
I even tried cd.markForCheck() or cd.detectChanges() to no avail.

Any ideas? This is driving me nuts :)

The code is identical to that in sample 12. The only thing that could be different is angular.json which i'm including here.

angular.json

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "xtrack": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/xtrack",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/app/styles.scss",
              "node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css",
              "node_modules/bootstrap/dist/css/bootstrap.css",
              "node_modules/bootstrap/dist/css/bootstrap-grid.css",
              "node_modules/bootstrap/dist/css/bootstrap-reboot.css",
              "node_modules/@swimlane/ngx-datatable/release/assets/icons.css",
              "node_modules/ng2-toasty/bundles/style-bootstrap.css",
              "node_modules/bootstrap-select/dist/css/bootstrap-select.css",
              "node_modules/flatpickr/dist/flatpickr.css",
              "node_modules/angular-slickgrid/lib/multiple-select/multiple-select.css",
              "node_modules/font-awesome/css/font-awesome.css",
              "src/app/styles-external.css",
              "node_modules/@ng-select/ng-select/themes/default.theme.css"
            ],
            "scripts": [
              "node_modules/chart.js/dist/Chart.bundle.min.js",
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/jquery-ui-dist/jquery-ui.min.js",
              "node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js",
              "node_modules/bootstrap/dist/js/bootstrap.js",
              "node_modules/angular-slickgrid/lib/multiple-select/multiple-select.js"

            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "outputPath": "dist/xtrack_prod",
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "7mb",
                  "maximumError": "7mb"
                },
                {
                  "type": "bundle",
                  "maximumWarning": "7mb",
                  "maximumError": "7mb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "xtrack:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "xtrack:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "xtrack:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/app/styles.scss",
              "node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css",
              "node_modules/bootstrap/dist/css/bootstrap.css",
              "node_modules/bootstrap/dist/css/bootstrap-grid.css",
              "node_modules/bootstrap/dist/css/bootstrap-reboot.css",
              "node_modules/@swimlane/ngx-datatable/release/assets/icons.css",
              "node_modules/ng2-toasty/bundles/style-bootstrap.css",
              "node_modules/bootstrap-select/dist/css/bootstrap-select.css",
              "node_modules/flatpickr/dist/flatpickr.css",
              "node_modules/angular-slickgrid/lib/multiple-select/multiple-select.css",
              "node_modules/font-awesome/css/font-awesome.css",
              "src/app/styles-external.css",
              "node_modules/@ng-select/ng-select/themes/default.theme.css"
            ],
            "scripts": [
              "node_modules/chart.js/dist/Chart.bundle.min.js",
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/jquery-ui-dist/jquery-ui.min.js",
              "node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js",
              "node_modules/bootstrap/dist/js/bootstrap.js",
              "node_modules/angular-slickgrid/lib/multiple-select/multiple-select.js"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "xtrack:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "xtrack:serve:production"
            }
          }
        }
      }
    }},
  "defaultProject": "xtrack"
}

**Comment by tannenbaums** [comment]
I finally got it with the almighty's help: in tsconfig.json i had target: es2015 instead of es5.

**Comment by ghiscoding** [comment]
Indeed targeting ES2015 won't work and it's worth to know that both GitHub Demos of Bootstrap 3 and 4 are both built with the Production flag. I do this to make sure that it works with Production code and catch any errors before release new versions.
