### ISSUE TITLE
columnNamesH error while creating a build of project.

### ISSUE THREAD

**Issue by GirishSS** [ghiscoding/Angular-Slickgrid#284]
| Software          | Version(s) |
| ----------------- | ---------- |
|Angular | 8 |
|Angular-Slickgrid | 2.10.5|
|Node version | 10.16.0|
|npm version | 3.10.10|

 **Context**
I am using slickgrid to display a huge data generated by IoT devices. The report is huge which is why I have to add scroll. I have completed the UI and created a build of the overall project.

 **Expected Behavior**
Build runs without error properly.

 **Current Behavior**
An error related to angular-slickgrid is invoking. I am sharing the screeshot. 
Error : " ReferenceError: columnNamesH is not defined" 

**Possible Solution**
Using autoHeight: true; in gridOption, but this fixes the height of the table which I dont want. Maybe some other gridOption to overcome the height issue.

**Comment by ghiscoding** [comment]
I think what you mean is Pagination not Scrolling. The `autoHeight` will basically create a huge grid the scrolling changes from the grid to the browser scrolling. The other downside of using `autoHeight` is also that it won't be using SlickGrid caching system, by default SlickGrid caches and create rows in the DOM for only what it shows to the users (with a buffer of about 5 rows on top/bottom) which is what makes SlickGrid work with big dataset without too much slowdown (the only limitation becomes the code that holds the dataset in javascript in your computer memory). 

In terms of Pagination, I only have that working with a Backend Service (OData or GraphQL), there is no Pagination with regular JSON grids. There's a user that created his own Backend Service that you can see [here](https://ghiscoding.github.io/Angular-Slickgrid/#/swt) but that requires a bit more work. What is easiest is to use OData or GraphQL (if you opt for that, then check the associated Wiki on how to do so).

**Comment by ghiscoding** [comment]
Closing since no feedback was provided, I can reopen if this is found to be an issue and more info is provided.

**Comment by tsimgsong** [comment]
Same story.
is slickgrid 2.10 compatible with Angular 8 ? 
anyone has made it work with angular 8 ?

**Comment by tsimgsong** [comment]
even you try with the basic example, you run into this . 
https://github.com/ghiscoding/Angular-Slickgrid/wiki/HOWTO---Step-by-Step#6-create-a-basic-grid 
please try out

**Comment by tsimgsong** [comment]
> Closing since no feedback was provided, I can reopen if this is found to be an issue and more info is provided.

even you try with the basic example, you run into this .
https://github.com/ghiscoding/Angular-Slickgrid/wiki/HOWTO---Step-by-Step#6-create-a-basic-grid
please try out

**Comment by ghiscoding** [comment]
Well if you read the welcome page, I have a section for the Angular Compatibility and it is mentioned that you need to switch your compilation to `ES5` for Angular 8 [here](https://github.com/ghiscoding/Angular-Slickgrid#angular-8). It is also mentioned that the [angular-slickgrid-demos](https://github.com/ghiscoding/angular-slickgrid-demos) was all upgraded to Angular 8

**Comment by GirishSS** [comment]
Yes, after changing the target from ES6 to ES5, I was successful in running the build. Thank you for the support

**Comment by ghiscoding** [comment]
NOTE

Latest version of the SlickGrid core library fixed all `ES2015` build errors, you can upgrade to latest version of Angular-Slickgrid [version 2.11.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.11.0) and change back your build target to `ES2015`. The GitHub demos have been updated already and there's no longer any build errors.
