### ISSUE TITLE
how do i set default column filters even after clearFilters() call? (Filters not working unless filterService.clearFilters() not called)

### ISSUE THREAD

**Issue by pranayshinagare** [ghiscoding/Angular-Slickgrid#286]
I want to show some default filters in grid but somehow its not showing. for this reason i calling `angularGrid.filterService.clearFilters();` and then i tried to add filters but not working.

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           |    7.2
| Angular-Slickgrid | 2.10.5
| TypeScript        |  3.2.2
| Operating System  |  Windows 10
| NPM/Node/Yarn     | npm node -8.9.4

### Expected Behavior
We want to show some working filters on default slickgrid loading.

### Current Behavior
whenever grid is loaded, first time filters not working unless i do clear filter call.

### Code Sample
calling this for filter works but it should not solution.
angularGrid.filterService.clearFilters();

**Comment by ghiscoding** [comment]
You didn't include the code you tried. I think you might have tried [searchTerms](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Select-Filter#default-search-terms)? I think those comes back after a clear filter. What is probably better is to use [Grid Presets](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-State-&-Preset#grid-presets), that is the only thing I use in my projects. The only thing to know is that the Presets will only work on first page load, never after, meaning that if you change some filters (or clear filters), the only way to get the default filters back is to refresh the page which is really what most people want anyway.

**Comment by ghiscoding** [comment]
Closing since no feedback was provided, I can reopen if this is found to be an issue and more info is provided.
