### ISSUE TITLE
Excel export

### ISSUE THREAD

**Issue by naveenkumar096** [ghiscoding/Angular-Slickgrid#289]
Is there excel export feature

**Comment by ghiscoding** [comment]
No there's only CSV Export (which works in Excel), you can see that through the [Wiki - Export to File](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Export-to-File)

**Comment by ghiscoding** [comment]
This is now implemented as a new feature, see version [2.12.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.12.0
