### ISSUE TITLE
Header Grouping not showed when frozenColumn are setted

### ISSUE THREAD

**Issue by ybarbaria** [ghiscoding/Angular-Slickgrid#290]
Hi, 

I am trying to set some header group, some of my cols are frozen some not. I try to add a header grouping on the col not frozen and doesn't appear. 
I tried to show a header group on the frozen cols and this one appear but still not on the cols not frozen. 

So i took your code from the demo page and I created a stackblitz, will be easy to show you what happened :) 

[https://stackblitz.com/edit/angular-slickgrid-headergroup](url)

If you take off the param :
` frozenColumn: 1, `
All the header-group missing will appear. 

Let me know if you have any idea for fix that.
Thanks for your job by the way , your lib is great !

Cheers

**Comment by ghiscoding** [comment]
Are you talking about this kind of [Example](https://6pac.github.io/SlickGrid/examples/example-frozen-columns-and-column-group.html) from the core lib? If so this was fixed recently on the core lib in this [PR #429](https://github.com/6pac/SlickGrid/pull/429) and I did not upgrade to latest version of SlickGrid yet so it won't work in Angular-Slickgrid until I upgrade

**Comment by ybarbaria** [comment]
Exactly what I am looking for ! Thanks for you response! I will wait until you release the new version.

**Comment by ghiscoding** [comment]
Latest version includes the core lib fix, please upgrade to Angular-Slickgrid version [2.11.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.11.0).

Also note that it probably won't work out of the box without some code change, I see some differences in the new SlickGrid example on this [line](https://github.com/6pac/SlickGrid/blob/master/examples/example-frozen-columns-and-column-group.html#L51).

**Comment by ybarbaria** [comment]
Thanks @ghiscoding  ! I will look at that !

**Comment by mad786** [comment]
@ybarbaria Any update on that feature. Have you been able to get the Header Grouping on the right panel of unfrozen columns. In my case the issue still persists.

Thanks.

**Comment by ybarbaria** [comment]
@mad786 sorry didn't have time to try the last version. Will do this weekend.

**Comment by mad786** [comment]
@ybarbaria Ok. Thanks. Do let me know if it works. 
@ghiscoding Can you please take a look into this if possible.

Thanks in advance.

**Comment by mad786** [comment]
@ghiscoding  Can we reopen this issue for angular-slickgrid?

**Comment by ghiscoding** [comment]
> Also note that it probably won't work out of the box without some code change, I see some differences in the new SlickGrid example on this [line](https://github.com/6pac/SlickGrid/blob/master/examples/example-frozen-columns-and-column-group.html#L51).

**Comment by ghiscoding** [comment]
I pushed a commit to update the [example](https://ghiscoding.github.io/Angular-Slickgrid/#/colspan) and the service with pinned (frozen) columns. 

@mad786 
I suggest you to read about the meaning of Open Source Community, in short, if you want help then you should help back. Contributions are welcome and beneficial to this project. Thanks
