### ISSUE TITLE
[feature] Support Multiple Grid in 1 View - Major Release with Breaking Changes

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/Angular-Slickgrid#31]
After working on supporting Multiple Grid in same View, I found out that all the work from the start was to use Services as Singleton (services which are exposed by Angular-Slickgrid through Depency Injection (DI)). The first code change that was made to support multiple grid was to change the Singleton Services to non-Singleton, however that breaks all the Services exposed by Angular-Slickgrid. 

So we need a new Major Release, below are the things that I have always put aside and that will be addressed before releasing a new Major Version (aka version `1.x`)

Task List
- [x] 1. GridEvent Service, no longer references the 2nd argument `gridOptions`  
- [x] 2. a lot of the Services instantiated in `aurelia-slickgrid` ViewModel use an `init()` which usually ask for `init(grid, gridOptions, dataView)` but once we get the grid object, we actually have access to the `gridOptions`, so we can simplify this a lot (closed by PR [#28](https://github.com/ghiscoding/Angular-Slickgrid/pull/28)).
- [x] 3. remove all deprecated code (just search for the word deprecated), code change could be renamed or re-implemented ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/47dbdcbe61b5e00d1d7ec3fb22542fb190055feb))
  - [x] a. `onBackendEventApi` was re-implemented and replaced by `backendServiceApi`
- [x] 4. change all Singleton Services to non-Singleton
- [x] 5. Filter could possibly use only `searchTerms` array instead of doing multiple logic to deal with both `searchTerm` (singular) and the `searchTerms` array ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/7dfb06f9e652dd550d04bd569134fa2cb6a87c76) and [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/ad3769f63ba518dd151dbc6e4cb9ea3c5c2b5fa6)).
- [x] 6. Remove all previous reference of `selectOptions` in all Filters ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/247727b47bcf5b53d7f66fdc9aa0d292a5aef441)). 
- [x] 7. Editors/Filters should use a common `Column` property and possibly remove the `filter` Column property ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/bd8440b5d50ab8338b5b32e3d8a68643dda75d12)). 
- [x] 8. remove `FormElementType` from Filters, it should **only** use `FilterType` ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/c9288468a57cfc2c6e2484548e79d3a28e48974e))
  - [x] a. the `FormElementType` is actually not used anywhere else I think, so might be better to delete it completely
- [x] 9. BackendService API `onFilterChanged` function and the Filter Service `onFilterChanged` Event Emitter, should not be named the same, it is rather confusing when troubleshooting, maybe change function to `processOnFilterChanged` ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/96505688c8b79dd097181507a32b5087597af483))
- [x] 10. remove `exportWithFormatter` from GridOptions.interface since it is now part of `exportOptions` ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/9eb9d0edd3648e17801fd8d6d98edc73b8e4443f))
- [x] 11. GridMenu has both `hideX` and `showX` flags, they should all be `hideX` since that is the default name in the external plugins ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/29855285102af03e99b7b8f927d18d9326e94370))
- [x] 12. Possibly rename the `GridExtraService` to simply `GridService` or `DataGridService`
- [x] 13. Not exporting all Services in the Angular-Slickgrid module can break user who created their own `BackendServiceApi`, for example [swt-grid-component](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/swt-common-grid.component.ts) 
   - [x] a. remove all Services from the module export since they aren't singleton anymore ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/2cf15373d293127af0e38ef37d013851fcd5ef57))
- [x] 14. A lot of the Editors properties (like `collection`) are available only from the generic `params` property which removes the benefit of intellisense and type check. This goes with number `7.` ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/bd8440b5d50ab8338b5b32e3d8a68643dda75d12))
- [x] 15. Expose all SlickGrid Events the same way they are currently exported in Aurelia-Slickgrid ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/beb414b2ebd1b8410917cd590b293c67a0ec7bdf) and [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/509ea253d2f66333fc646a2ac80778779428ae53))
   - [x] a. update Event Wiki, for now more info can be found in the [Aurelia Wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Grid-&-DataView-Events#example-with-event-aggregators) 
      - [x] SlickGrid Event `onClick` can be used in the View as `(sg-on-click)="handleClick($event.detail.eventData, $event.detail.args)"`
      - [x] DataView Event `onRowCountChanged` can be used as `(sg-on-row-count-changed)="handleRowCountChanged($event.detail.eventData, $event.detail.args)"`
   - [x] b. update the Example 3 (Editors) to demo this new way of using `sg-on-click=""`
- [x] 16. Remove the `initOptions` from the `BackendService`, that was replaced by `init` ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/08882bee0d1e252c5eca7afa27b3dbead5d0c870))
- [x] 17. `GridExtraUtil` contain only 1 function, it would be better to move it into the renamed `GridService` and delete `GridExtraUtil` completely ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/718e7f60f3a5fc7f6490f83caf75680ea377ccbc) and [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/beb414b2ebd1b8410917cd590b293c67a0ec7bdf))
- [x] 18. Should pass `i18n` as a Grid Options instead of a generic `params` grid option and fix a column picker issue ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/ce9426f91329bd22e97a3e3ee70bd801f75f9b34))
- [x] 19. add `Percent` (divide by 100, they display %) and `PercentSymbol` (only add "%" suffix symbol) ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/d21b4d4dd69edb834355d4426a8b2081126324c5))
- [x] 20. Add a sample for multiple grids in 1 view ([commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/c691bc3e1047bbd47702f69e3a75007ea60e77a3))
- [x] 20. Update all the [Wikis](https://github.com/ghiscoding/Angular-Slickgrid/wiki) and there's a **lot**
- [x] 21. Update all the GitHub demo examples

### Migration Guide will be available [here](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Migration-from-0.x-to-1.x)

**Comment by ghiscoding** [comment]
@sabeurch 
I need your input on number 13.
If you read the title of this issue, you will end up seeing that I am in the process of doing a **Major** version with breaking changes. The breaking piece is that users won't use Dependency Injection anymore to use the Angular-Slickgrid Services, because they are no longer Singleton. 

All that to say, if I look at my Services using the `BackendServiceApi` (which are `GraphqlService` and `GridOdataService`). They are not using using any DI of Angular-Slickgrid, but your demo (Example 13) as all the Services in the `constructor` with DI. Is it just because you did a copy + paste? or do you use any of these Services? I don't want to break your custom `BackendServiceApi` but I need an answer rather soon on this.

**Comment by sabeurch** [comment]
@ghiscoding 
**I confirm that we can remove all DI in the contructor of SwtCommonGridComponent except the HttpClient oen which is supposed to be used in the logging framework (even if not implemented, but looks wise to keep it, ie as if we are logging into the server the errors)**.
BTW, for a time ago I wanted to take a talk with you about the expanding number of dependency injections in the AngularSlickgridComponent's constructor, in fact you can group all services into a unique service and inject it solely. But now, since you are going to "provide" services from within the component itself, then forget my suggestion.
Are you planning to move all singleton services into non singletons ? I think yes, since variables such as :
**private _dataView: any;** and  **private _grid: any;** are shared .

**Comment by ghiscoding** [comment]
@sabeurch 
I only wanted to confirm the Angular-Slickgrid DI in your custom implementation, `HttpClient` is not part of Angular-Slickgrid, so it's all good. I won't be exposing the Services anymore from the outside, instead they will be available from 1 Angular-Slickgrid instance.

> Are you planning to move all singleton services into non singletons ? I think yes, since variables such as: private _dataView: any; and private _grid: any; are shared .

The reason of this Major Version is because I want to support multiple grids and that requires moving all Services from singleton to non singleton (hence the Major version with breaking changes)

**Comment by mohit4834** [comment]
Hello @ghiscoding,
Greetings!
Does our angular slickgrid supports delete of multiple rows after i select multiple rows using our row selection. As i am not able to do it.
Major Issue i am facing is once i provide index of the rows i selected from the grid. After 1st delete index got changed and there after it deletes the row which are not selected.

Thanks,
Mohit Goyal

**Comment by ghiscoding** [comment]
@mohit4834 
Your issue is different than the original issue, you should open a new issue if need be. 
There's a delete example in the [Editor Example](https://ghiscoding.github.io/angular-slickgrid-bs4-demo/#/editor) and the code is shown [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-editor.component.ts#L473)
