### ISSUE TITLE
Filter combined with sort makes rows disappear

### ISSUE THREAD

**Issue by RajeshGunasundaram** [ghiscoding/Angular-Slickgrid#310]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 7        | 
| Angular-Slickgrid | 2.4.2       | 
| TypeScript        | 3.1.3        | 
| Operating System  | WIndows 10        | 
| NPM/Node/Yarn     | 10.15        | 

### Expected Behavior

Sorting should work even after hiding the filtered column

### Current Behavior

Enter a filter value in any of the column in the grid
Remove that filtered column from the grid
Click on any other column in the grid to sort
All rows in the grid disappear

**Comment by ghiscoding** [comment]
I can reproduce, I think this might be fixable by calling a clear filter internally before hiding the column. That seems to work from my early testing on the demo site anyway

**Comment by RajeshGunasundaram** [comment]
I don't want to clear the filter. I want to keep the filter and do sorting after hiding the filtered column

**Comment by RajeshGunasundaram** [comment]
> I can reproduce, I think this might be fixable by calling a clear filter internally before hiding the column. That seems to work from my early testing on the demo site anyway

I don't want to clear the filter. I want to keep the filter and do sorting after hiding the filtered column

**Comment by ghiscoding** [comment]
This was fixed and released under the new version [2.12.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.12.0), please make sure to read the entire announcement as there is an important change, even though small, to make. 

Also please up vote ⭐️ if you have not yet and of course if you like the lib. Thank you
