### ISSUE TITLE
odata query does not escape single quote 

### ISSUE THREAD

**Issue by whtan98** [ghiscoding/Angular-Slickgrid#328]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8        | 
| Angular-Slickgrid | 2.12.2       | 

### Context
Whenever a fitler value eg. **lee's** is entered, the generated odata query fails to escape single quote with 2 single quotes

### Expected Behavior
$count=true&$top=20&$orderby=Name asc&$filter=(contains(Name, 'lee''s'))

### Current Behavior
$count=true&$top=20&$orderby=Name asc&$filter=(contains(Name, 'lee's'))

![image](https://user-images.githubusercontent.com/13287569/67773529-d6f61280-fa96-11e9-9cac-1747c328219d.png)

**Comment by ghiscoding** [comment]
I'd be happy to have a PR fixing it... if I look quickly at the code I do see that I double up the single quote on this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/grid-odata.service.ts#L293), so I'm not sure why it doesn't work

**Comment by ghiscoding** [comment]
I had to do a quick fix for GraphQL Service, so I fixed your issue at the same time and released it under latest version `2.12.3`. The GitHub [demo](https://ghiscoding.github.io/Angular-Slickgrid/#/odata) was also updated.

**Comment by whtan98** [comment]
Thanks a lot for speedy release.

**Comment by ghiscoding** [comment]
You're welcome, thanks for the good feedback
