### ISSUE TITLE
Is there any way to implement client side pagination in Angular slickgrid? Please suggest 

### ISSUE THREAD

**Issue by GowthamKarthick12** [ghiscoding/Angular-Slickgrid#338]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | x.y        | 
| Angular-Slickgrid | x.y        | 
| TypeScript        | x.y        | 
| Operating System  | x.y        | 
| NPM/Node/Yarn     | x.y        |

**Comment by ghiscoding** [comment]
There is no pagination for regular grid (without Backend Service) and I won't add it either. You could if you want create a Pull Request and I might accept it, but I won't personally spend time on something that I will never use.

**Comment by soft24technologies** [comment]
Hi,

I am using Slick Grid with Angular 8 in one of my big and very IMP project.
Facing client side pagination issue like every grid or tables, its a basic feature for every grid.

Please provide client side pagination option with Angular 8 or 8+.

Thanks in advance.

**Comment by ghiscoding** [comment]
Well then go ahead and create a Pull Request for this feature, I'm very open to contributions. 

Seriously what's the point of having Pagination if you have to load the entire dataset in memory anyway? There's no real benefit to client side Pagination. We always use Pagination with a Backend Service (OData/GraphQL) and that is where it's available. I already said that I will **not** spend time on something that I will most probably never use. 

May I also remind you of the Open Source [MIT License](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/LICENSE)
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND

I stand by my earlier answer, I won't fix it and won't spend time on this feature request unless someone wants to contribute.

**Comment by soft24technologies** [comment]
So can you share server side pagination enable code using Angular 8 
And how to enable pagination options on ui ? 
Thanks in Advance

**Comment by ghiscoding** [comment]
Local grid Pagination is now possible with latest [version](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.16.0)
