### ISSUE TITLE
Odata query builder to support IN operator for numeric column

### ISSUE THREAD

**Issue by whtan98** [ghiscoding/Angular-Slickgrid#340]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8       | 
| Angular-Slickgrid | 2.13.1        | 
### Context
For the preset filter like below:
eg.
filters: [ { columnId: 'id', searchTerms: [100, 101], operator: OperatorType.in } ]

The IN filter operator will cause the following JS error, as it assume the filter value to be "string"
![image](https://user-images.githubusercontent.com/13287569/69244404-de18c800-0bdf-11ea-8066-f84808ae4758.png)

### Possible Solution
Can we consider  enhancing the GridOdataService.ts to something like below ?
p/s only escape single quote if the column type is "string"

![image](https://user-images.githubusercontent.com/13287569/69244540-19b39200-0be0-11ea-9add-38d1c181f180.png)

**Comment by ghiscoding** [comment]
That seems quite reasonable, would you mind creating a Pull Request for this?

**Comment by ghiscoding** [comment]
Closed by #341

**Comment by ghiscoding** [comment]
Released under the new version [2.14.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.14.0) with 2 new features. Thanks for the quick PR

**Comment by whtan98** [comment]
Nice features...thanks
