### ISSUE TITLE
How to add dynamic row height based on row/cell content

### ISSUE THREAD

**Issue by gokhanntaskinnn** [ghiscoding/Angular-Slickgrid#342]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | x.y        | 
| Angular-Slickgrid | x.y        | 
| TypeScript        | x.y        | 
| Operating System  | x.y        | 
| NPM/Node/Yarn     | x.y        |

**Comment by ghiscoding** [comment]
That is not really possible in SlickGrid, all the CSS styling uses `<div>` for each row and because of that, it's fixed. There's nothing Angular-Slickgrid can do, neither will do for this. However, if you search on Google for dynamic row height, you might find hacks to do it.
