### ISSUE TITLE
Can this be used for Angular 8 project

### ISSUE THREAD

**Issue by helihno** [ghiscoding/Angular-Slickgrid#350]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | x.y        | 
| Angular-Slickgrid | x.y        | 
| TypeScript        | x.y        | 
| Operating System  | x.y        | 
| NPM/Node/Yarn     | x.y        |

**Comment by ghiscoding** [comment]
Yes it is, you can the [Compatibility List](https://github.com/ghiscoding/Angular-Slickgrid#angular-compatibility) and all [Angular-Slickgrid demos](https://github.com/ghiscoding/angular-slickgrid-demos) were updated to Angular 8
