### ISSUE TITLE
autosizeColumns not working

### ISSUE THREAD

**Issue by mayankgirdhar** [ghiscoding/Angular-Slickgrid#354]
Hey,
autosizeColumns is not working with angular slickgrid. i tried this.angularGrid.slickGrid.autosizeColumns(); this method.
Please help me. 
thanks in advance.

**Comment by ghiscoding** [comment]
Read the [Auto-Resize Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-Auto-Resize)
