### ISSUE TITLE
Update slickgrid version in npm package json

### ISSUE THREAD

**Issue by mayankgirdhar** [ghiscoding/Angular-Slickgrid#362]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 7        | 
| Angular-Slickgrid | 2.14.4       | 
| TypeScript        |~3.2.2       | 
| Operating System  | ubuntu        | 
| NPM/Node/Yarn     | 6.12.0 / v10.16.3        | 

### Context or Topic 

Please Update slickgrid version in npm. it's really urgent.

### Current Behavior

maxIndex is not initialized in slick.grid.js so getting an error when resizing a column.

### Possible Solution

change slickgrid version from 2.4.14 to 2.4.16

**Comment by ghiscoding** [comment]
> Please Update slickgrid version in npm. it's really urgent.

May I remind you that this is an Open Source project with an [MIT license](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/LICENSE) which strictly says 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND

Comment like yours just make me want to wait longer to release anything. I already told you in earlier [reply](https://github.com/ghiscoding/Angular-Slickgrid/issues/178) that I **will not** release anything until Next Year. Besides, every SlickGrid variables is accessible directly in the lib if you do your research.

**Comment by mayankgirdhar** [comment]
@ghiscoding at line number 2361 in slick.grid.js
        var tempVal, maxLen = 0, maxIndex; <==== this variable is not initialized also it is not accessible anywhere. its declared in funtion

**Comment by ghiscoding** [comment]
closed by latest release
