### ISSUE TITLE
Upgrade dompurity to 2.0.7 to fix vulnerability 

### ISSUE THREAD

**Issue by Teesit-Draycir** [ghiscoding/Angular-Slickgrid#365]
https://www.npmjs.com/advisories/1223

### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 8.2        | 
| Angular-Slickgrid   | 2.6.0     | 
| TypeScript              | 3.4.5      | 

### Describe the Bug
[dompurify ](https://www.npmjs.com/package/dompurify) prior to 2.0.7 has are vulnerable to Cross-Site Scripting (XSS). https://www.npmjs.com/advisories/1223

### Steps to Reproduce
Run npm audit againt project

### Expected Behavior
No Vulnerabilities dependency used. 

### Current Behavior
Using dompurify version 1.0.10 which reported as Vulnerable package

### Possible Solution
Upgrade dompurify to version 2.0.7 or later.

**Comment by ghiscoding** [comment]
Thanks for reporting, I just wished you would have told me earlier (yesterdat) when I pushed 2 new versions 😆

**Comment by ghiscoding** [comment]
Fixed under latest version [2.15.2](https://github.com/ghiscoding/Angular-Slickgrid/releases), thanks for reporting

Cheers ⭐️

**Comment by Teesit-Draycir** [comment]
Thanks for quick turnaround.

**Comment by ghiscoding** [comment]
Welcome, you can upvote ⭐️ if you haven't already, thanks 😉

**Comment by ghiscoding** [comment]
Welcome, you can upvote ⭐️ if you haven't already, thanks 😉
