### ISSUE TITLE
where did setColumns go?

### ISSUE THREAD

**Issue by ctung** [ghiscoding/Angular-Slickgrid#40]
I used to use getColumns()/setColumns() to get/set the visible columns as a subset of the full list of columns.

It looks like I can still use angularGrid.pluginService._grid.setColumns() & ._grid.getColumns()  but I don't see that documented anywhere.  Also it causes inconsistencies in other variables like visibleColumns and areVisibleColumnsDifferent.

https://stackblitz.com/edit/angular-cjiajg 

  angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
    console.log(angularGrid.gridStateService.getColumns());  // returns []
    this.angularGrid.gridStateService.resetColumns(this.columnView); // does nothing?
    console.log(angularGrid.pluginService._grid.getColumns()); // returns original columns
    this.angularGrid.pluginService._grid.setColumns(this.columnView); // changes columns
    console.log(angularGrid.pluginService.areVisibleColumnDifferent);  // false should be true
    console.log(angularGrid.pluginService._grid.getColumns());  // returns the partial list
  }

**Comment by ghiscoding** [comment]
Maybe the Migration Guide is not clear enough but if you look at the Example code, you will see that the best way to get the `grid` and/or the `dataView` object is through the new `AngularGridInstance`. I tried to expose most of everything in that new instance.

Like this way:

```javascript
angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
    this.gridObj = angularGrid.slickGrid;
    this.dataViewObj = angularGrid.dataView;

    // and any other Services you wish to use
    this.gridService = angularGrid.gridService;
  }
```

Please don't use any `_grid`, they are meant to be for internal usage only.

**Comment by ghiscoding** [comment]
BTW I'm not sure what you are trying to do with the code, but aren't you looking for a Grid State & Presets functionality? The [Wiki - Grid State & Presets](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-State-&-Preset) was updated after the new `1.x` version. Also the Grid State now also deal with the `columns`, that is new in version `1.x`. So you might want to take another look at the wiki.

It's also a lot of work for 1 person (me), so if you feel that the examples, wikis are lacking then feel free to mention which wiki should be updated. Our team decided to make it open source, in the hope of bringing feedback and improvement, I think it's going good so far.

**Comment by ctung** [comment]
Ok, Thanks again!
