### ISSUE TITLE
Use Only Angular Base Plugin

### ISSUE THREAD

**Issue by kamlesh0606** [ghiscoding/Angular-Slickgrid#402]
### Context or Topic 

Can this project convent to only angular base plugin ?

Like jquery-ui replace with Angular CDK , multiple-select replace with ng-select , bootstrap.js replace with ng-bootstrap ,etc ...

Due to i use angular then again need to jquery and jquery base plugin And made some problem like build size, Angular and jQuery manage (both are JavaScript framework), Angular <=> jquery calling problem, etc ...

### Possible Solution

Thanks
kamlesh

**Comment by ghiscoding** [comment]
> Can this project convent to only angular base plugin ?

I think you meant "convert"? The answer is NO, this is a wrapper of SlickGrid which has a deep dependency of jQuery. If you're looking for a datagrid without jQuery then look for another lib. 

> Angular and jQuery manage (both are JavaScript framework),

What??? jQuery is not a framework, it's a library to query and control the DOM, below is the definition pulled from the jQuery website
 
> jQuery is a fast, small, and feature-rich JavaScript library. It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers. With a combination of versatility and extensibility, jQuery has changed the way that millions of people write JavaScript.

Some people like you might want to use as small library as possible, but I didn't create this lib for you, I created this lib for our project, we were looking for usability, customizability and performance and that is what we get with this lib. If you're so concerned about lib size, you can always go and use Ag-Grid, they have a great library, it's small and it's written in plain JavaScript without any dependencies and they have all features that Angular-Slickgrid has... as long as you're willing to pay. So please go ahead and use any other library. Oh wait I have another suggestion for you, why don't you contribute to the [SlickGrid](https://github.com/6pac/SlickGrid) repo to remove jQuery from the core library? This way it would fix all your problem.

**Comment by kamlesh0606** [comment]
Cool Cool ...

I and my team planing for make analytics  tool like [metabase ](https://www.metabase.com/), Redash , etc ... and in tool , i will use 'Angular-Slickgrid', '[D3](https://d3js.org/)', '[Akka](https://akka.io/)', '[Spark](https://spark.apache.org/)', etc...  . so i asking to you.
And part of Ag-Grid , this is pay Api but i will go for opensource api. And also my tool will also opensource.

_Thank For your Reply._

**Comment by ghiscoding** [comment]
Since you did a thumbs down on my message... I must remind you that this library is an Open Source project and is provided **"AS IS"** as defined in the [MIT License](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/LICENSE).

**Comment by kamlesh0606** [comment]
Thanks for reply.
