### ISSUE TITLE
Draggable Grouping - remove group

### ISSUE THREAD

**Issue by pwidanka** [ghiscoding/Angular-Slickgrid#407]
## I'm submitting a Bug report
HI,
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 8.2       | 
| Angular-Slickgrid   | 2.17     | 
| TypeScript              | 3.5       | 

### Describe the Bug

Example 19 - don't see dataset on grid after remove grouping 
### Steps to Reproduce

I set grouping by title -> click collapse all groups -> remove grouping
### Expected Behavior

Should show all dataset
### Current Behavior

![image](https://user-images.githubusercontent.com/31447178/75668912-57619580-5c7a-11ea-97fa-7687d1debba2.png)

Thank You

**Comment by ghiscoding** [comment]
just call a render on the grid object and that will fix it
```ts
clearGrouping() {
  // ...
  this.gridObj.render();
}
```

**Comment by ghiscoding** [comment]
I've update the example to use `this.gridObj.invalidate()` and now it's all good, the `invalidate` method in SlickGrid is a 2 in 1, it invalidate the row and re-render the grid. You can see the [Example 19](https://ghiscoding.github.io/Angular-Slickgrid/#/draggrouping) now works as expected.

Please upvote the lib if you haven't already ⭐️ Thanks

**Comment by pwidanka** [comment]
Works like a charm. 

But if You want to work perfectly. I added  `this.gridObj.invalidate()` on event (red X) in pre-header row

I have given you ⭐️ 2 years ago :)
Best wishes
