### ISSUE TITLE
multipleSelect filter doesn't handle cell value arrays

### ISSUE THREAD

**Issue by ctung** [ghiscoding/Angular-Slickgrid#41]
If I have a cell with the value: ["foo","bar"] it displays correctly on the grid as "foo,bar"
If I select "foo" from the multiSelect filter, I get all rows with "foo", but I do not get the row with "foo,bar"
If I select "foo" and "bar" from the multiSelect filter, I get all rows with "foo" and all rows with "bar" but not "foo,bar".  

I suspect I should be able to write a custom filter that replicates the multiSelect filter, but searches for matches on any element in the array.  Before doing that, is there an option/config setting that I'm not using correctly?

**Comment by ghiscoding** [comment]
Can you provide some code to replicate, I kinda get lost in your foo... However I believe that the MultipleSelectFilter won't handle well cell values that are arrays.

**Comment by ctung** [comment]
`ngOnInit(): void {
    this.columnDefinitions = [
      { id: 'title', name: 'Title', field: 'title', sortable: true },
      { id: 'dependencies', name: 'Dependencies', field: 'dependencies',
        filterable: true,
        filter: {
          collection: [{value:'a',label:'a'},{value:'b',label:'b'},{value:'c',label:'c'}],
          model: Filters.multipleSelect,
          searchTerms: []
        }
      },
      { id: 'duration', name: 'Duration (days)', field: 'duration', sortable: true },
      { id: '%', name: '% Complete', field: 'percentComplete', sortable: true }
    ];


    this.gridOptions = {
      enableAutoResize: true,       // true by default
      enableCellNavigation: true,
      enableFiltering: true
    };



    // fill the dataset with your data
    // VERY IMPORTANT, Angular-Slickgrid uses Slickgrid DataView which REQUIRES a unique "id" and it has to be lowercase "id" and be part of the dataset
    this.dataset = [];

    // for demo purpose, let's mock a 1000 lines of data
    for (let i = 0; i < 1000; i++) {
      const randomYear = 2000 + Math.floor(Math.random() * 10);
      const randomMonth = Math.floor(Math.random() * 11);
      const randomDay = Math.floor((Math.random() * 28));
      const randomPercent = Math.round(Math.random() * 100);

      this.dataset[i] = {
        id: i, // again VERY IMPORTANT to fill the "id" with unique values
        title: 'Task ' + i,
        dependencies: this.getRandomSubarray(["a","b","c"],Math.floor(Math.random()*3)+1),
        duration: Math.round(Math.random() * 100) + '',
        percentComplete: randomPercent
      };
    }
  }

  getRandomSubarray(arr, size) {
    var shuffled = arr.slice(0), i = arr.length, temp, index;
    while (i--) {
      index = Math.floor((i + 1) * Math.random());
      temp = shuffled[index];
      shuffled[index] = shuffled[i];
      shuffled[i] = temp;
    }
    return shuffled.slice(0, size);
  }
`

**Comment by ctung** [comment]
Here's a stackblitz of the example https://stackblitz.com/edit/angular-nctj2c

**Comment by ghiscoding** [comment]
What you want is not actually supported and is more a combination of the operators `IN` and `LIKE` (or `Contains`), just like this [SO Question](https://stackoverflow.com/questions/3014940/is-there-a-combination-of-like-and-in-in-sql). So we are missing a new operator to do that work since the `IN` is made for search a perfect match (equal) inside a collection. 

I worked on that last night in my other repo `Aurelia-Slickgrid` and got it working in this [commit](https://github.com/ghiscoding/aurelia-slickgrid/commit/e695660bd74814dd96a195a321b7ce13bc228f87). I'm not sure if I will have time to copy it over in this repo today, if not then on Monday

The Starblitz do help, so it's good you provide. Thanks

**Comment by ctung** [comment]
Wow! thank you so much!!!

**Comment by ghiscoding** [comment]
Also note that at first I started modifying the `IN` to do what the new `IN_CONTAINS` but it had some side effect and the `IN` is really meant to be an equality search.

As for the implementation, it's in the commit on my other repo that I mentioned earlier. You can see the new filter condition [here](https://github.com/ghiscoding/aurelia-slickgrid/commit/e695660bd74814dd96a195a321b7ce13bc228f87#diff-3a6be671a1f146b3b72c8a6b78258fc2). I use a findIndex` which has a `indexOf` inside it. Simply using 1 or the other is not enough, it's a combination of both.

**Comment by ghiscoding** [comment]
Made the changes, but forgot to include the issue inside the commit. Here's the [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/b9d1d3b0098155fa13edcd2f9e1ed5ea3d6fc294) 

I tested it by modifying the Example 3 (Editor), however I only changed it locally. 
I used the following

```javascript
// modify the Prerequisites column and add the filter to it
filterable: true,
  filter: {
  operator: 'IN_CONTAINS', // <= this is new
  collection: Array.from(Array(12).keys()).map(k => ({ value: `Task ${k}`, label: `Task ${k}` })),
  model: Filters.multipleSelect
},

// and enableFiltering to True inside the Grid Options
```

Updated on [NPM](https://www.npmjs.com/package/angular-slickgrid) at version `1.0.19`
Also note, that I will release the official `1.x` version next week with an upcoming new feature so stay tuned.

Lastly if you wish to contribute in any matter, you can easily do so by cloning the repo locally and running the VSCode task "Start Library Dev" (or run `npm start` in console). All the examples are within the lib.
