### ISSUE TITLE
Input Filter no longer supports operators

### ISSUE THREAD

**Issue by ctung** [ghiscoding/Angular-Slickgrid#42]
visible in the demo:
https://ghiscoding.github.io/Angular-Slickgrid/#/clientside

If you enter "ta*" into the title quick filter, no rows are returned
This applies to the other operators as well.

**Comment by ghiscoding** [comment]
I'll have to look into that, there was a lot of refactoring done in `1.x`, in the mean time you can use the CompoundInput

**Comment by ghiscoding** [comment]
fixed with last commit, however it might take couple days before I push a new release

**Comment by ghiscoding** [comment]
This was also pushed in latest version `1.0.19`, thanks for feedback
