### ISSUE TITLE
Unit tests with Jasmine: ../node_modules/angular-slickgrid/lib/multiple-select/multiple-select.js not found

### ISSUE THREAD

**Issue by AndreasLehnerCDE** [ghiscoding/Angular-Slickgrid#420]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.0.5     | 
| Angular-Slickgrid   | 2.17.11 | 
| TypeScript              | 3.7.5     | 

### Describe the Bug
When testing a component that includes slick grid, the test fails because the multiple-select.js cannot be found. Both in the production code and in the test code the module is imported with ".forRoot()" and the angular.json has the styles and scripts defined as described in the HOWTO.
In production, the slick grid is working fine, but it is not testable this way.

### Steps to Reproduce
Create a new test with the Jasmine testing framework
Use a component, that uses slick grid
Write a test for this component

### Expected Behavior
The test should run. Currently it stops before execution.

### Current Behavior
The test stops with the following error:

Error: multiple-select.js was not found, make sure to modify your "angular-cli.json" file and include "../node_modules/angular-slickgrid/lib/multiple-select/multiple-select.js" and it's css or SASS file
	    at MultipleSelectFilter.push../node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js.SelectFilter.createDomElement (http://localhost:9876/_karma_webpack_/node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js:5894:1)
	    at MultipleSelectFilter.push../node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js.SelectFilter.renderDomElement (http://localhost:9876/_karma_webpack_/node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js:5800:1)
	    at MultipleSelectFilter.push../node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js.SelectFilter.init (http://localhost:9876/_karma_webpack_/node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js:5640:1)
	    at FilterService.push../node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js.FilterService.addFilterTemplateToHeaderRow (http://localhost:9876/_karma_webpack_/node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js:7712:1)
	    at SlickGrid.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js:7274:1)
	    at Event.notify (http://localhost:9876/_karma_webpack_/node_modules/slickgrid/slick.core.js:183:1)
	    at trigger (http://localhost:9876/_karma_webpack_/node_modules/slickgrid/slick.grid.js:2557:1)
	    at createColumnHeaders (http://localhost:9876/_karma_webpack_/node_modules/slickgrid/slick.grid.js:1303:1)
	    at SlickGrid.finishInitialization [as init] (http://localhost:9876/_karma_webpack_/node_modules/slickgrid/slick.grid.js:557:1)
	    at AngularSlickgridComponent.push../node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js.AngularSlickgridComponent.initialization (http://localhost:9876/_karma_webpack_/node_modules/angular-slickgrid/__ivy_ngcc__/fesm5/angular-slickgrid.js:17126:1)

**Comment by ghiscoding** [comment]
So just include it in your Test, that is what I do with my own test [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/filters/__tests__/selectFilter.spec.ts#L2), you'll need to adjust the path for your test though, it will probably something similar to what you need to add in your `angular.json` file

```ts
import 'node_modules/angular-slickgrid/lib/multiple-select/multiple-select';
```
I don't think it's a problem with the lib, you just need to import it and you should be fine

**Comment by ghiscoding** [comment]
@AndreasLehnerCDE have you tried what I suggested? I'm almost sure that will work and I'm thinking of closing this issue since it's not really an issue but more of a question.

**Comment by AndreasLehnerCDE** [comment]
I got one step closer. Now the multiple-select can be found. So this looks good to me. Thank you.
But another problem came up with the auto-complete filter. Again the problem is only present while testing.
TypeError: $filterElm.autocomplete is not a function
When I follow the path, where the error happens, it seems to me that I do not have a valid filterTemplate, that is passed in the method (AutoCompleteFilter.prototype.createDomElement).
Although the debugger says there is a autocomplete function, I get this exception.

**Comment by ghiscoding** [comment]
The [unit test](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/filters/__tests__/autoCompleteFilter.spec.ts) I have for the Autocomplete Filter doesn't seem to require any special imports. It uses jQuery UI, you could maybe try to import it in your test. You said your debugger has it, but you might be getting a racing condition, you might need delays. 

```ts
import 'jquery-ui-dist/jquery-ui';
```

BTW, I had another thought about this, some these external libraries are required in your `angular.json` file, have you checked if it was also included for the test section in that same `angular.json` file?

**Comment by AndreasLehnerCDE** [comment]
This was also the test I looked up before writing the answer before :)
Yeah that could be the case. I just also realized that onAngularGridCreated() is not being called. I was able to overcome the error I described above by calling fixture.whenStable().then(()=> {}). I found out that my angularGrid member is undefined, because the method does not get called.
When I call fixture.detectChanges() instead I get the error from the previous post.

Thanks for the tip in the angular.json file. You are right, in the test section I have not defined the scripts and styles needed for the slickgrid. I just did so, but I still need the import.
The jquery import did not change anything.

So just to clarify, when I am debugging, the error happens too although I see the function in the proto of the object.

Then I tried adding a delay and the exception was gone. So most likely an issue with a race condition. If adding the delay, the onAngularGridCreated() is being called. It is not a nice solution using a delay but for now it seems to work as expected.

The only thing left now is the following error:
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'false'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook?
I think this is because the grid is assigned in the onAngularGridCreated(). Did you run in such an error before? Otherwise thanks for your help. I guess I can find this problem on my own.

Thank you again for your support.

**Comment by ghiscoding** [comment]
oh that `ExpressionChangedAfterItHasBeenCheckedError` is so annoying, that is again a racing condition, there are some ways to overcome it but very often I resolve to using a `setTimeout` delay to get rid of it.

**Comment by AndreasLehnerCDE** [comment]
Ok I now resolved it. I use the ChangeDetectorRef class and use detectChanges in ngAfterViewInit().
This allows me to remove the delay I had before. Now everything is working as expected and I can do my tests.
I will write the Wiki page and let you know when I am done with it.

Thank you for your great support and your library.

**Comment by ghiscoding** [comment]
Awesome, you can also upvote if you haven't already ⭐️  
Cheers 😉 🌞
