### ISSUE TITLE
Date sorting not working

### ISSUE THREAD

**Issue by Sudalaiyandi** [ghiscoding/Angular-Slickgrid#425]
Hi Team,
I have used angular slick grid in my application."angular-slickgrid": "2.17.10". In my scenario, get timestamp from webservice and convert it date using date pipe for correct dateformat.Date conversion is done properly.If sort the date column, it didn't give the exact sorting date value.Kindly provide solution for this issue.

**Comment by Sudalaiyandi** [comment]
**Your Environment**

Software | Version(s)
-- | --
Angular | 7.3.5
Angular-Slickgrid | 2.17.10
TypeScript | 3.1.6
Operating System | macOS High Sierra
Node | 10.16.3
NPM | 6.9.0

**Context or Topic**

Hi Team,
In my scenario, get timestamp from webservice and convert it date using date pipe for correct dateformat.Date conversion is done properly.If sort the date column, it didn't give the exact sorting date value.Kindly provide solution for this issue.

**Expected Behavior**
While sort date fields, asc and desc should be done date/time value.

**Current Behavior**
While sort date fields, asc and desc not done properly.

**Possible Solution**
Provide solution to handle timestamp in sorting.

_Here I attached my issue video.Kindly Check it._
[Sorting Issue.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/4425110/Sorting.Issue.zip)

**Comment by ghiscoding** [comment]
Date must be valid format, you have to provide a valid `type` in your column definition for the Filtering and Sorting to work correctly. If your data has anything other than what the lib provides as `FieldType` then it won't work.

might be a duplicate of #426 

Also to avoid having your issue being close by the bot, you must read and provide necessary info in the issue template.

**Comment by ghiscoding** [comment]
Actually I forgot that you can pass your own custom Sort Comparer method in your column definition 

```ts
this.columnDefinitions = [{ 
  id: 'start', name: 'Start',
  sorter: (value1: any, value2: any) => x > y ? 1 : -1,
  formatter: myCustomFormatter
}];
```

Change the Sort Comparer to your need, I only displayed a numeric comparer for reference, you just need to adjust it.
