### ISSUE TITLE
Add new row dynamically to the grid.

### ISSUE THREAD

**Issue by YadavAvinashK** [ghiscoding/Angular-Slickgrid#43]
Am using slickgrid to populate the data as well as for inserting the new record. For inserting am using "enableAddRow" set to true.  Do i need to set columns value to empty or is there any other way??

**Comment by ghiscoding** [comment]
Take a look at the [Wiki - Add/Update Items](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Add,-Update-or-Highlight-a-Datagrid-Item) and the [demo](https://ghiscoding.github.io/Angular-Slickgrid/#/additem) it's all there

**Comment by YadavAvinashK** [comment]
Thanks.. that worked
