### ISSUE TITLE
Grouping interface getter property type

### ISSUE THREAD

**Issue by gregoryfikator** [ghiscoding/Angular-Slickgrid#430]
### Motivation / Use Case
I'm trying to group by column with complex object data but grouping.interface doesn't allow me to set function as getter. Using default string from column field which points to exact property doesn't seem to work for me as I'm getting groups with [undefined] value.

**Slickgrid's dataview can handle getter as function, so my question is if getter property of [Grouping Interface](../blob/master/src/app/modules/angular-slickgrid/models/grouping.interface.ts) shouldn't take `string` or `(value: any) => string`?**

![obraz](https://user-images.githubusercontent.com/14919969/78983659-e89f1400-7b24-11ea-8092-c9df406edff9.png)
![obraz](https://user-images.githubusercontent.com/14919969/78983813-39af0800-7b25-11ea-8de3-d455117981c5.png)
![obraz](https://user-images.githubusercontent.com/14919969/78984766-6106d480-7b27-11ea-95a5-59a224226cb3.png)
![obraz](https://user-images.githubusercontent.com/14919969/78984502-ab3b8600-7b26-11ea-9463-90d28b6f27fe.png)

### Expected Behavior
Allow string or function returning string as parameter for getter property of Grouping interface by changing `getter?: string` to `getter?: string | (value: any) => string`

### Other Information
Setting any accepted type instead of Grouping for my setGrouping argument makes it working so the interface property type is the only one obstacle . I think interface should also consider this case.

**Comment by ghiscoding** [comment]
I wasn't aware that it could take a function, it's hard to cover every cases since SlickGrid doesn't have any Typing, I added all of them by what I see available at the time of creating the feature. 

So please go ahead with a Pull Request if possible.

**Comment by ghiscoding** [comment]
This is now available in latest version [2.18.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

Please upvote ⭐ if you haven't already. 
Cheers
