### ISSUE TITLE
Toggle filter row option disappeared once language switched in Angular SlickGrid

### ISSUE THREAD

**Issue by sundaramoorthyjeeva** [ghiscoding/Angular-Slickgrid#438]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 7.3.5        |
| Angular-Slickgrid | 2.17.10        |
| TypeScript        | 3.1.6        |
| Operating System  | Windows 10        |
| Node     | 10.16.3        |
| NPM     | 6.9.0        | 

### Describe the Bug
I am using Angular Slickgrid in my application and I am facing an issue in the slick grid option. Here I described my scenario. First I have applied Toggle Filter Row option in the right corner. Then I switched the language, now I seen the list of option which available at the right corner. I cannot see the Toggle Filter Row option, its disappeared.

### Steps to Reproduce
I have mentioned the below link which has the screen record clip taken from your samples. Please check and advise. Thanks. https://www.loom.com/share/58bcd0850ba844cf8140c2d48121a9de

### Expected Behavior
Toggle Filter Row should not disapprear ever.

### Current Behavior
I am using Angular Slickgrid in my application and I am facing an issue in the slick grid option. Here I described my scenario. First I have applied Toggle Filter Row option in the right corner. Then I switched the language, now I seen the list of option which available at the right corner. I cannot see the Toggle Filter Row option, its disappeared.
I explained this case in Stackoverflow as well. Please the stackoverflow link below.
https://stackoverflow.com/questions/61505151/toggle-filter-row-option-disapperaed-once-language-switched-in-angular-slickgrid?noredirect=1#comment108869400_61505151

**Comment by ghiscoding** [comment]
Fixed with a side effect, see PR #448 for more details.

Note however that I won't release a new version until couple more weeks, I want to finish some other features before I'm ready for a new version.
