### ISSUE TITLE
Multiselect collectionAsync API on click

### ISSUE THREAD

**Issue by meta-akshita-agrawal** [ghiscoding/Angular-Slickgrid#451]
## I'm submitting a Feature request
Hi @ghiscoding, Thanks for creating such a great library :)
I have added an HTTP API on my multiselect collectionAsync field which is working perfectly fine.
My concern is that my API returns a huge data and there are 4-5 columns on which I have added this because of which API gets hit every time backend service is called. 
I want to do this whenever the user clicks on the multiselect filter. I did a lot of digging but unable to find something like this.

Also, I found one workaround on this but I don't know it's not working as expected.

So what I did, was, I called the API on the hook **onOpen** and fed the result to **collectionAsync**.
It worked. When I clicked on the filter the API was called but it does not render the results in the filter.

Thanks!

**Comment by ghiscoding** [comment]
The problem with `collectionAsync` is that if you have multiple filters which call the `collectionAsync` it's actually worst than getting data by a Resolver. So I personally never use `collectionAsync`, I always use a Resolver and return the data with `forkJoin` so all the data is all in 1 call instead of multiple calls like you're trying to do.

**Comment by ghiscoding** [comment]
For a complete answer on your question, it goes with what I wrote in previous comment

>  If you feed the collectionAsync afterward, you need to call it with next(data) as shown [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-editor.component.ts#L487)

```ts
// find the Column Filter from the definitions
const requisiteColumnDef = this.columnDefinitions.find((column: Column) => column.id === 'prerequisites');

// for the Filter only, we have to trigger an RxJS/Subject change with the new collection
// we do this because Filter(s) are shown at all time, while on the Editor it's unnecessary since they are only shown when opening them
const filterCollectionAsync = requisiteColumnDef.filter.collectionAsync;
if (filterCollectionAsync instanceof Subject) {
  filterCollectionAsync.next(editorCollection);
}
```
I'm not sure if that would work for your use case, you might need an `onBeforeOpen` to build the full list (from the collection) prior to `onOpen` but there's no `onBeforeOpen` callback on that 3rd party `multiple-select.js` lib, so you can't do that... you could always create a [Custom Filter](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Custom-Filter) but that would require more work on your side. 

I would again, recommend that you look at using `Resolvers` with `forkJoin` when you have multiple sources. The only time that the `collectionAsync` could be useful is when there's only 1 of them in your entire grid, as soon as you have multiple, you should use `Resolvers` 

Closing as I can't help you more than that and it's not really an issue with the lib itself
