### ISSUE TITLE
Exported PDF is not in supported format.

### ISSUE THREAD

**Issue by SanthoshSansh14** [ghiscoding/Angular-Slickgrid#452]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 7.3.5        | 
| Angular-Slickgrid | 2.17.10        | 
| TypeScript        | 3.1.6        | 
| Operating System  | Windows 10        | 
| Node     | 10.16.3        | 
| NPM     | 6.9.0        | 

### Describe the Bug

The table when exported using the ExportOption interface in PDF format, the exported file is not supported in chrome as well as Adobe pdf viewer.
### Steps to Reproduce

Use this code on the export button click
exportTable() {
    this.angularGrid.exportService.exportToFile({
      filename: 'myExport',
      format: FileType.pdf
    })
  }
### Expected Behavior

We should be able open the downloaded file in any PDF viewer.
### Current Behavior

When we try to open the downloaded file the following error messages arise.
1) Edge browser - "This PDF is corrupted"
![image](https://user-images.githubusercontent.com/65221226/81664989-c408c580-945d-11ea-8444-7df8f22552a5.png)

2) Chrome - "Failed to load PDF document."
![image](https://user-images.githubusercontent.com/65221226/81664860-91f76380-945d-11ea-832e-9cd50e810a70.png)

3) Adobe Acrobat Reader DC  - "Adobe Acrobat Reader could not open the file"
![image](https://user-images.githubusercontent.com/65221226/81664557-32995380-945d-11ea-9f42-f6bdbd826d31.png)

### Code Sample

You can check this by changing the exportToFile method in the Example 12: Localization (i18n) class in the examples.
exportToFile(type = 'csv') {
    this.angularGrid.exportService.exportToFile({
      filename: 'myExport',
      format: FileType.pdf
    });
  }

**Comment by ghiscoding** [comment]
This is most probably a SlickGrid core lib related issue. You most probably cannot just use the browser print directly, I don't think the grid was meant to be print directly from the browser, there are some opened issues similar to this on SlickGrid like this [issue](https://github.com/6pac/SlickGrid/issues/368). 

Lastly what is most probably a better approach is to create a PDF Export Service, but I personally will not invest time in creating this. I never use PDF export but I would certainly accept Pull Request for the feature. This is an Open Source project, if you want a new feature then please help.
