### ISSUE TITLE
Force Fit Columns

### ISSUE THREAD

**Issue by pwidanka** [ghiscoding/Angular-Slickgrid#461]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.0       | 
| Angular-Slickgrid   | 2.17.11        | 
| TypeScript              | 3.75       | 

### Describe the Bug

Force Fit Columns show hidden columns
### Steps to Reproduce

I click 'hide column' next i click 'force fit columns'
### Expected Behavior

I would like to see unhidden columns
### Current Behavior

I see all columns

**Comment by ghiscoding** [comment]
Seriously your question is missing content, what have you tried? I don't understand what is wrong, "Force Fit Columns" has nothing to do with "Hide Column", they do very different thing. If you hide a column, you can show it back from the Column Picker (right+click on any header title) or from the Grid Menu.

**Comment by pwidanka** [comment]
I explained bad.
I mean when i hide some column 
![image](https://user-images.githubusercontent.com/31447178/82116443-30d7d480-976a-11ea-8c97-83eb13ead628.png)
and then i click 'Force Fit Columns' i get all column but i expected get columns without 'Effort Driven'
![image](https://user-images.githubusercontent.com/31447178/82116476-68df1780-976a-11ea-8795-78f8f717cec0.png)

**Comment by ghiscoding** [comment]
This is an issue in the core lib [6pac/SlickGrid](https://github.com/6pac/SlickGrid) and can be reproduced in this [Grid Menu Example](https://6pac.github.io/SlickGrid/examples/example-grid-menu.html). You should open your issue on the core lib [6pac/SlickGrid](https://github.com/6pac/SlickGrid) instead, there is nothing to do or change in Angular-Sclikgrid.

Side note, you can avoid the issue by enabling "Force Fit Columns" **before** hiding the column(s).

**Comment by pwidanka** [comment]
Ok Thank You,

I don't know how to use it(Side note, you can avoid the issue by enabling "Force Fit Columns" before hiding the column(s)), but I will wait for 6pac/Slickgrid

**Comment by ghiscoding** [comment]
closed by #460

**Comment by ghiscoding** [comment]
This is now available in latest version [2.18.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

Please upvote ⭐ if you haven't already. 
Cheers
