### ISSUE TITLE
Odata Query encoding

### ISSUE THREAD

**Issue by meta-akshita-agrawal** [ghiscoding/Angular-Slickgrid#463]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.0        | 
| Angular-Slickgrid   | 2.17        | 
| TypeScript              | 3.7        | 

### Describe the Bug

Hi Author,

Thanks for making such a great library :). I am reporting this issue for backendservice oData query
So the current behaviour is that when a multiselect value contains a value having special symbol(/, @, #, etc.) it encodes the string and then oData query is built. 
This works properly when a single value is selected but when user selects multiple values encoding does not work properly. I replicated the issue in your code too.
https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-odata.component.ts

Also, note that **single quotes** and **double quotes** are not encoded if present in the value

### Expected Behavior

- Change singleselect(male/female) to multiselect in column definitions
- Change *value* of male label from *male* to *ma/le* in collection
- Now select male and female both from dropdown

### Code Sample

`{
        id: 'gender', name: 'Gender', field: 'gender', filterable: true,
        filter: {
          model: Filters.multipleSelect,
          collection: [{ value: '', label: '' }, { value: 'ma/le"', label: 'male' }, { value: 'female', label: 'female' }]
        }
      }`

**Comment by ghiscoding** [comment]
Sorry but I don't really want to do any changes for this, if I encode the value then the users (you) will have to decode it. I don't think this is ideal and I think you should encode/decode yourself.

**Comment by meta-akshita-agrawal** [comment]
Umm.. Sorry if I was unable to make myself clear, but the issue is it encodes the string if I only select *male*
 $inlinecount=allpages&$top=20&$orderby=Name asc&$filter=(Gender eq 'ma%2Fle')
and if select both *male* and *female*:
$inlinecount=allpages&$top=20&$orderby=Name asc&$filter=(Gender eq **'ma/le'** or Gender eq 'female')
It doesn't.

I have no problem in decoding but the oData query produces is not consistent.
How will I know when its already encoded and when its not.

**Comment by ghiscoding** [comment]
Hmm ok I see, can you try to troubleshoot the problem and fix it? I'd be happy to have help on this since we don't use OData anymore. 

By looking at the code, I see that I dealt with single search by escaping single quote and encoding on this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/grid-odata.service.ts#L293) but I don't remember how it's dealing with multiple search values. The project is already setup with debugging, if you could just clone and contribute to a fix that would be really great. Thanks

**Comment by meta-akshita-agrawal** [comment]
I can see the issue is on this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/7535f49c8b15309202590e2876a04d36980b087d/src/app/modules/angular-slickgrid/services/grid-odata.service.ts#L263). 
I guess this works only when **searchTerms** has length 1. In this case its ['ma/le', 'female']

**Comment by ghiscoding** [comment]
No I don't think so, that line is only to check if there's an Operator that was typed in the filter. It's most probably around this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/7535f49c8b15309202590e2876a04d36980b087d/src/app/modules/angular-slickgrid/services/grid-odata.service.ts#L323) but like I said earlier, I wish that you troubleshoot with your use case then contribute by providing a Pull Request. Thanks

**Comment by meta-akshita-agrawal** [comment]
Sorry I tagged the wrong line.
This seems correct https://github.com/ghiscoding/Angular-Slickgrid/blob/7535f49c8b15309202590e2876a04d36980b087d/src/app/modules/angular-slickgrid/services/grid-odata.service.ts#L263

**Comment by ghiscoding** [comment]
This is now fixed in latest version [2.18.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). I'd be happy to have more help next time around, thanks.

Please upvote ⭐ if you haven't already. 
Cheers
