### ISSUE TITLE
When using Locales, z* shows the tool tip "Contains" in CompoundInputFilter

### ISSUE THREAD

**Issue by yazhiniHariharan3** [ghiscoding/Angular-Slickgrid#468]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 8.2.14        | 
| Angular-Slickgrid   | 2.16.5      | 
| TypeScript              | 3.5.3   | 

### Describe the Bug
On hovering over a CompoundInputFilter, the z* select option shows the tooltip incorrectly.

### Steps to Reproduce
Do not use the TranslateService, so it defaults to use the locale constants.
For a string field, CompoundInputFilter will now show z* tooltip to be Contains
       eg: filter: {
                 model: Filters.compoundInputText
            }
### Expected Behavior
For a CompoundInputFilter of String type, the z* description should be set to Ends with

### Current Behavior
For a CompoundInputFilter of String type, the z* description shows Contains in that 

### Possible Solution
https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts#L179

In the above line,  getOptionValues() is returning "ends with" description incorrectly, It should be as follows :
``{ operator: '*z' as OperatorString, description: this.translate && this.translate.currentLang && this.translate.instant && this.translate.instant(`${translationPrefix}ENDS_WITH`) || this._locales && this._locales.TEXT_ENDS_WITH} ``

**Comment by ghiscoding** [comment]
Do you mean that it shows the text from the `this._locales.TEXT_CONTAINS` which is "Contains". Is that what you mean? That was a mistake, it should be `this._locales.TEXT_ENDS_WITH`

**Comment by yazhiniHariharan3** [comment]
Yes, that's what i meant. Thanks !

**Comment by ghiscoding** [comment]
This is now fixed in latest version [2.18.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

Please upvote ⭐ if you haven't already. 
Cheers
