### ISSUE TITLE
Titre des colonnes non visible

### ISSUE THREAD

**Issue by rihabJaballah** [ghiscoding/Angular-Slickgrid#47]
salut,
 je voulais savoir pourquoi les noms des colonnes ne sont pas encore visibles dans la version Angular-Slickgrid  1.1.0 qui viens d’être lancée?
Merci :)
![capture](https://user-images.githubusercontent.com/40670037/42046733-cb0d992a-7afe-11e8-8a6b-3ed13527bebb.JPG)

**Comment by ghiscoding** [comment]
Pour résumé, ce ne sont pas toutes les examples qui supportent la traduction. Pour la supporter, on doit ajout l'option suivante

```javascript
constructor(translate: TranslateService) { }

buildGrid() {
   this.dataset = [ ... ];
   this.gridOptions = {
      i18n: this.translate
   }
}
```
Et c'est tout, les menus devraients être traduits correctement.
