### ISSUE TITLE
Metric labels with custom text are not showing as expected

### ISSUE THREAD

**Issue by pwidanka** [ghiscoding/Angular-Slickgrid#470]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.0        | 
| Angular-Slickgrid   | 2.18.6        | 
| TypeScript              | 3.75       | 

### Describe the Bug

I wrote about this issue on the stackoverflow.
I try to change a metric label in footer 

### Steps to Reproduce

I use customFooterOptions to change metric label in this way

```
this.gridOptions = {showCustomFooter: true,
  customFooterOptions: {
    metricTexts: {
      items: 'myItems',
      of: 'myOf',
    }
  }
}
```

### Expected Behavior

I expected see "2 myOf 2 myItems" in my footer

### Current Behavior

Nothing changes. I see default text in footer

**Comment by ghiscoding** [comment]
This is now fixed in latest version [2.18.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

Please upvote ⭐ if you haven't already. 
Cheers
