### ISSUE TITLE
"Cant resolve all parameters for k in angular-slickgrid.d.ts"

### ISSUE THREAD

**Issue by ctung** [ghiscoding/Angular-Slickgrid#48]
upgraded to 1.1.1 to pull in the fixes to the input filters.
ng serve works fine on my localhost.
When attempting to ng build --prod, I get the following warning:

> PS C:\Users\ctung\git\hld-track> ng build --prod -bh /ps_www/ps_hld/
> Warning: Can't resolve all parameters for k in C:/Users/ctung/git/hld-track/node_modules/angular-slickgrid/angular-slickgrid.d.ts: (?).
 This will become an error in Angular v6.x
Warning: Can't resolve all parameters for k in C:/Users/ctung/git/hld-track/node_modules/angular-slickgrid/angular-slickgrid.d.ts: (?).Date: 2018-07-02T13:46:20.083Z
Hash: 7c85975545ea0c7bd159
Time: 48252ms

Followed by a bunch of these:

> WARNING in ./src/app/features/features.component.ngfactory.js
51:633-651 "export 'SlickgridConfig' (imported as 'i3') was not found in 'angular-slickgrid'
WARNING in ./src/app/features/features.component.ngfactory.js
51:653-671 "export 'SlickgridConfig' (imported as 'i3') was not found in 'angular-slickgrid'
WARNING in ./src/app/features/features.component.ngfactory.js
51:697-713 "export 'FilterFactory' (imported as 'i3') was not found in 'angular-slickgrid'
WARNING in ./src/app/features/features.component.ngfactory.js
51:715-731 "export 'FilterFactory' (imported as 'i3') was not found in 'angular-slickgrid'
WARNING in ./src/app/features/features.component.ngfactory.js
51:747-765 "export 'SlickgridConfig' (imported as 'i3') was not found in 'angular-slickgrid'
WARNING in ./src/app/features/features.component.ngfactory.js
51:868-884 "export 'FilterFactory' (imported as 'i3') was not found in 'angular-slickgrid' 
WARNING in ./node_modules/angular-slickgrid/angular-slickgrid.ngfactory.js
88:1012-1028 "export 'FilterFactory' (imported as 'i1') was not found in 'angular-slickgrid'
WARNING in ./node_modules/angular-slickgrid/angular-slickgrid.ngfactory.js
88:777-795 "export 'SlickgridConfig' (imported as 'i1') was not found in 'angular-slickgrid'
WARNING in ./node_modules/angular-slickgrid/angular-slickgrid.ngfactory.js
88:797-815 "export 'SlickgridConfig' (imported as 'i1') was not found in 'angular-slickgrid'
WARNING in ./node_modules/angular-slickgrid/angular-slickgrid.ngfactory.js
88:841-857 "export 'FilterFactory' (imported as 'i1') was not found in 'angular-slickgrid'
WARNING in ./node_modules/angular-slickgrid/angular-slickgrid.ngfactory.js
88:859-875 "export 'FilterFactory' (imported as 'i1') was not found in 'angular-slickgrid'
WARNING in ./node_modules/angular-slickgrid/angular-slickgrid.ngfactory.js
88:891-909 "export 'SlickgridConfig' (imported as 'i1') was not found in 'angular-slickgrid'

Then the table fails to load complaining about:
> ERROR Error: Uncaught (in promise): TypeError: i is not a constructor
TypeError: i is not a constructor

**Comment by ctung** [comment]
ng build without the --prod flag works fine, so perhaps its a problem with AOT or tree shaking?

**Comment by ghiscoding** [comment]
Might be related to this [post](https://github.com/ghiscoding/Angular-Slickgrid/issues/38#issuecomment-398546558), however I do a Prod Build for the GitHub Demo page (and work project) and it works fine on my side.

Can you provide a sample of your column definitions?

@sabeurch the filter factory that I exposed in `1.1.0` seems to be causing some problems.

**Comment by ghiscoding** [comment]
@ctung 
I made a commit to address the Factory, it might help but I think there's still some warnings while compiling though. 

I'm not sure how I will address the remaining warnings, since SlickGrid itself is passing arguments to the constructor of each Editors. Anyway, give it a try and see what happens

**Comment by ghiscoding** [comment]
@ctung 
I believe that I finally fixed this issue with latest commits, please update and try version `1.2.7` thanks
