### ISSUE TITLE
Toggle filter view showing as blank space after reorder the columns in Angular SlickGrid

### ISSUE THREAD

**Issue by sundaramoorthyjeeva** [ghiscoding/Angular-Slickgrid#493]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular           | 7.3.5        |
| Angular-Slickgrid | 2.17.10        |
| TypeScript        | 3.1.6        |
| Operating System  | Windows 10        |
| Node     | 10.16.3        |
| NPM     | 6.9.0        | 

### Describe the Bug
I am using Angular Slickgrid in my application and I am facing an issue in the slick grid option. Here I described my scenario. At the time filter view closed, I have done reorder of the column. After the I toggled the filter view, showing blank instead of filter view. The similar thing I faced with other scenario last month and I raised a bug(https://github.com/ghiscoding/Angular-Slickgrid/issues/438). Its got fixed I hope. The similar issue with other case now occurred. Please clear filter view related issue in the single shot and provide fixes.

### Steps to Reproduce
1) Toggle filter view should be closed state.
2) Reorder the columns
3) Now open the toggle filter, blank space showing instead of filter view.

### Expected Behavior
Toggle Filter Row should not disapprear ever.

### Current Behavior
I am using Angular Slickgrid in my application and I am facing an issue in the slick grid option. Here I described my scenario. At the time filter view closed, I have done reorder of the column. After the I toggled the filter view, showing blank instead of filter view. The similar thing I faced with other scenario last month and I raised a bug(https://github.com/ghiscoding/Angular-Slickgrid/issues/438). Its got fixed I hope. The similar issue with other case now occurred. Please clear filter view related issue in the single shot and provide fixes.

**Comment by ghiscoding** [comment]
Sorry but I really don't understand your issue, your English is really hard to read. Maybe the best would be to add an animated gif of the issue. I already fixed the other issue you mentioned and I don't understand why you mention it again.

Also note that making your friend to thumbs up the issue is **not** going to help in fixing the issue faster, it's actually very frustrating for me to see this. This is an Open Source project, you guys should help instead...

**Comment by sundaramoorthyjeeva** [comment]
As per your request. I have attached the GIF which contains the issue. Hope it should be clear.
![ezgif-6-4246125789fd](https://user-images.githubusercontent.com/5718408/84586248-d3967800-ae28-11ea-9e8c-9b8a9fdfe8b1.gif)

**Comment by AjithkumarAK26** [comment]
Please update here once this solution gone live for developers use.

**Comment by ghiscoding** [comment]
This is now fixed in latest version [2.19.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

Please upvote ⭐ if you haven't already. 
Cheers
