### ISSUE TITLE
Unable to delete rows, as duplicate IDs are getting created

### ISSUE THREAD

**Issue by SumeetKumarBarua** [ghiscoding/Angular-Slickgrid#495]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 7.3.9        |
| Angular-Slickgrid | 2.17.4        |
| TypeScript        | 3.2.2        |
| Operating System  | MacOS        |
| NPM/Node/Yarn     | 6.9.0        |

### Context or Topic

Slickgrid has existed since long, but doing it the Angular way was
really fun. Thanks to the Team.
I was trying out the feature of add / update
[https://ghiscoding.github.io/Angular-Slickgrid/#/additem](url) and
its really cool. But some how it was generating duplicate IDs as a
result of which I was not able to delete the rows. I was going through
its demo component
[https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-additem.component.ts](url)
and figured in line no: 167  ` const newId = this.dataset.length;`. I
understand its a very minor issue but newbie might struggle a bit at
start if they follow the Demo component.
### Expected Behavior

Should generate unique IDs.

### Current Behavior

Row IDs are repeating. I have attached a gif for the same.
![slickgrid-add](https://user-images.githubusercontent.com/6895456/84562017-b43b1480-ad6e-11ea-8cbb-4d523bb62741.gif)
### Possible Solution

Could use a min heap to get the missing IDs. 
But we can simply use the below as we just need to mention some unique ID:
`let length = this.dataset.length;`

`let id = (length === 0) ? len : this.dataset[length-1].id + 1
`

**Comment by ghiscoding** [comment]
Ok thanks for the hint but that doesn't seem to work correctly, what is better is to find the highest Id of the dataset and increment by 1, that is what I've done in the PR #497, I'm also pulling latest dataset from the DataView so it's updated.

**Comment by SumeetKumarBarua** [comment]
Thanks for looking into it :)

**Comment by ghiscoding** [comment]
This is now fixed in latest version [2.19.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

Please upvote ⭐ if you haven't already. 
Cheers
