### ISSUE TITLE
Compiling Error when using --aot or --prod switch

### ISSUE THREAD

**Issue by danielgschliesser** [ghiscoding/Angular-Slickgrid#5]
I am trying to use the grid.
It works fine calling ng build.

calling ng build --aot
or calling ng build --prod
I get the error  
ERROR in Error: Can't resolve all parameters for AngularSlickgridComponent in /Users/dg/Documents/repositories/yoda/src/gui-server/node_modules/angular-slickgrid/angular-slickgrid.d.ts: (?, ?, ?, ?, ?, ?).

What is my mistake?

**Comment by ghiscoding** [comment]
Yup I tried that couple days and I seen this error, however I'm still new to the Angular 4+ world and I have no clue on how to fix this one yet. I'm not sure if it comes from the packager itself (which is [ng-packagr](https://github.com/dherges/ng-packagr)) or if it's something in my own implementation. If you can point me in the right direction, I would be happy to fix it

**Comment by ghiscoding** [comment]
Great news, I finally found how to fix this (I had double exports causing cyclic dependencies). The latest version `0.6.6` is now working with AOT/Prod compilation.

Thanks for the feedback
