### ISSUE TITLE
onDblClick event 

### ISSUE THREAD

**Issue by rihabJaballah** [ghiscoding/Angular-Slickgrid#50]
Hello, unable to find onDblClick event  on the grid , there is something missing ? 

thx

**Comment by ghiscoding** [comment]
Follow these steps [Wiki - Aurelia Grid & DataView Events](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-&-DataView-Events)

**Comment by ghiscoding** [comment]
If you read the [Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-&-DataView-Events#example-with-event-dispatch-sgonx), like I said in previous post, it will tell you that the best way is to do this

```html
<angular-slickgrid 
     gridId="grid2"
     [columnDefinitions]="columnDefinitions" 
     [gridOptions]="gridOptions" 
     [dataset]="dataset"
     (onAngularGridCreated)="angularGridReady($event)"
     (sgOnDblClick)="onCellDoubleClicked($event.detail.eventData, $event.detail.args)">
</angular-slickgrid>
```
```javascript
// class
onCellDoubleClicked(e, args) {
    // do something
}
````
