### ISSUE TITLE
Expand function does not work for level 2 after using collapse all in a multi level grouping

### ISSUE THREAD

**Issue by Anilima** [ghiscoding/Angular-Slickgrid#515]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 8.3 .26   | 
| Angular-Slickgrid   | 2.18.7       | 
| TypeScript              | 3.5.3      | 

### Describe the Bug

When I click Collapse all in a grid and then try to expand the groups one by one, the second level group expand does not work. I see the same issue in the TestSlickgrid, Example 14 Grouping.

### Steps to Reproduce

In the Test Slickgrid, Use either of "Group by duration then effort-driven" or "Group by duration then effort-driven then percent"
Right click and collapse all groups
Expand Level 1 - this works.
4 Expand Level 2 - does not work.
### Expected Behavior

After Collapse All, it should be possible to expand groups as required.
### Current Behavior

Level 2 group does not open.

**Comment by ghiscoding** [comment]
The grouping is done in the core lib (SlickGrid), Angular-Slickgrid is just a wrapper on top of SlickGrid.
This seems to be this SlickGrid [issue #512](https://github.com/6pac/SlickGrid/issues/512)

**Comment by ghiscoding** [comment]
This is now fixed in latest version [2.19.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

Please upvote ⭐ if you haven't already. 
Cheers
