### ISSUE TITLE
dot notation in field name yields undefined values

### ISSUE THREAD

**Issue by pollusion** [ghiscoding/Angular-Slickgrid#520]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.0        | 
| Angular-Slickgrid   | 2.19       | 
| TypeScript              | 3.7        | 

### Describe the Bug

When I use the dot notation in a field name of a column definition,
the formatter function for this field is called with
`value=undefind,`
even though the data source has a value assigned.

### Steps to Reproduce

Set the data source to something like
`dataSource = [ {id: 1, process: {id: 43, name: 'some name'}} ...`
and define a field like:
`{id: 'process', name: 'Process', field: 'process.id', formatter: myFormatter }`

### Expected Behavior

The function myFormatter is called with
`value=43`

### Current Behavior

The function myFormatter is called with 
`value=undefined`

**Comment by ghiscoding** [comment]
If you use a Custom Formatter, you should get the value from the `dataContext` object instead and you can use [getDescendantProperty()](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/utilities.ts#L431) from Angular-Slickgrid which is a utility to get the value from the dot notation

**Comment by ghiscoding** [comment]
Actually thinking, the only thing that I could maybe do is to add 1 new Formatter for Dot Notation but I certainly **won't** add the dot notation handling in each Formatters

**Comment by ghiscoding** [comment]
Forget about everything I said earlier, I totally forgot that there's already a Formatter that does exactly that which is the `Formatters.complexObject` and like I said earlier you probably want to combine it with other Formatter(s) if so then use the `Formatter.multiple` (more info in the [Wiki - Formatters](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#list-of-provided-formatters)

The list of Formatter is shown [here](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#list-of-provided-formatters) and so is the `complexObject` Formatter, and has been there for a while.
