### ISSUE TITLE
simple date filter without compound

### ISSUE THREAD

**Issue by barmi-solgvent** [ghiscoding/Angular-Slickgrid#528]
### Motivation / Use Case

We cannot select a simple date without the help of operators. We want to create a really simple filtering, where we won't display the operator dropdown. Is there any oppertunity to archive that?

### Expected Behavior

Similar to the dateRange filter, but only for one date.

### Other Information
Maybe it would be enough, to hide the operator dropdown via css? The default operator would fit our needs, so no need to change it.

**Comment by ghiscoding** [comment]
You can define the `operator` inside your column definition `filter: { model: Filters.compoundDate, operator: '>=' }` or create your own Custom Filter ([Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Custom-Filter)). I won't change the current 2 Date Filters
