### ISSUE TITLE
updateCell

### ISSUE THREAD

**Issue by bel1ever** [ghiscoding/Angular-Slickgrid#54]
Hallo. In JS version I can update only one cell with _slickgrid.updateCell(x,y)_.

Now I must update all row, but it is a problem, because I put a countdown timer in the first column, and I can`t edit any cell.

How can I do that in angular version?

**Comment by ghiscoding** [comment]
You can still use SlickGrid functions directly, the lib exposes both SlickGrid & DataView objects, read the [Wiki - SlickGrid & DataView objects](https://github.com/ghiscoding/Angular-Slickgrid/wiki/SlickGrid-&-DataView-Objects#grid--dataview-objects-through-onangulargridcreated)

**Comment by ghiscoding** [comment]
Good, so I assume the question is answered, then I will close the issue
