### ISSUE TITLE
Expanding multiple rows cleans the row expand view of the earlier expanded rows

### ISSUE THREAD

**Issue by rajenme** [ghiscoding/Angular-Slickgrid#546]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.x        | 
| Angular-Slickgrid   | 2.4.24        | 
| TypeScript              | 3.x        | 

### Describe the Bug
I'm facing a issue with the row detail feature, when I expand multiple rows and then come back to the earlier ones, they become blank. 

I checked on the official demo page [here ](https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail) and the issue persist there too.

### Steps to Reproduce
1. Go to example demo page [here ](https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail)
2. Go to the table at bottom and first expand a row. Expanding row 6 here.

![image](https://user-images.githubusercontent.com/25549899/88789819-d7057900-d1b4-11ea-97bc-c3fe97cea20e.png)

3. Expand another row. Sometimes opening another row cleans the view of earlier row expand view.
**Before expanding another row**:

![image](https://user-images.githubusercontent.com/25549899/88790429-cbff1880-d1b5-11ea-948a-2bf3342d12b2.png)

**After expanding another row**:
![image](https://user-images.githubusercontent.com/25549899/88790723-33b56380-d1b6-11ea-9d38-72ef9eaaa558.png)

4. Otherwise, scroll a bit down, expand another row, scroll down more, expand another and then scroll up to check earlier expanded rows, it turns out the earlier ones becomes blank.

![image](https://user-images.githubusercontent.com/25549899/88790065-35325c00-d1b5-11ea-8814-a80f3767668c.png)

### Expected Behavior
All the expanded rows should keep their view data and should not go blank.

### Current Behavior
Currently earlier rows go blank after opening multiple rows and coming back to earlier ones.

### Possible Solution
It seems the library is caching the view or is not always able to maintain multiple view component. Although, I'm not sure. I have tried to toggle these fields and used multiple combinations of these in row detail view object,
rowDetailView: {
        ...
        loadOnce: true,
        saveDetailViewOnScroll: false,
        useSimpleViewportCalc: true,
        singleRowExpand: false,
        ...
}

### Code Sample
https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail

**Comment by ghiscoding** [comment]
Sorry but there's nothing I can do for that, I already spent too much time on this. If you scroll a bit further and come back it will probably re-render. Internally there's a function that tries to detect if you are further away from what the user sees on the screen, and when it detects that the given row detail(s) comes back in the view then it tries to re-render them. 

You can perhaps try to call `redrawAllViewComponents()` method, from the extension, after scrolling, it might be less efficient but might help. 

The calculation happens by the `onRowBackToViewportRange` event and method [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/cc17d369c6eec67be4fe25b834979fe50040297c/src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts#L195), this is supposed to detect which row details are in the viewport and re-render (redraw) them, SlickGrid requires a re-render anytime a row gets out of the viewport and later comes back in the viewport. With that in mind, you could try to register to this event from the grid option `rowDetail: { onRowBackToViewportRange: (e, args) => console.log(args) }`

I'll say it again, I won't spend more time on this but if you find a fix then I'll be happy to receive a PR

**Comment by ghiscoding** [comment]
If you want to troubleshoot the lib, it mostly happen in this method [calculateOutOfRangeViewsSimplerVersion](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js#L345) and [checkIsRowOutOfViewportRange](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js#L366).

If you find a solution, that would be great, most probably in the core lib SlickGrid, probably no changes to do in Angular-Slickgrid.

**Comment by rajenme** [comment]
Hi, I tried the things you mentioned but couldn't get it to work. I'll keep trying and searching and will create a PR if I'm able to fix it.

**Comment by ghiscoding** [comment]
If you could use only a single row to be opened, I believe there's no issue with that one and it's only an issue when you use multiple, so if you could do that then go with `singleRowExpand: true`

Sorry I couldn't help with this, I just don't have time to invest in this at that point

**Comment by ghiscoding** [comment]
@rajenme 
I took a quick look at the Row Detail extension I created to handle this plugin with Angular and I found out that I made a mistake when adding the `datasetIdPropName`, I keep the View with an `id` not with the dynamic `datasetIdPropName` and so I was keeping all the Views with `undefined` instead of their correct associated `id` (or custom `id`)... long story short, the refresh of each Row Detail wasn't working correctly with using a custom Id with `datasetIdPropName`

So my question is, did you use `datasetIdPropName` in your grid?

**Comment by ghiscoding** [comment]
I actually found the issue, and the last fix in PR #552 seems to finally make the Row Detail work in every use cases.

**Comment by ghiscoding** [comment]
@rajenme 
The fix is now available in latest version [2.20.2](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.20.2), the [Row Detail Example](https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail) is now also working as expected, it no longer blanks at any point in time. 

Please upvote ⭐ if you haven't already. 
Cheers
