### ISSUE TITLE
Enable the data edit inside the newly introduced tree data grid

### ISSUE THREAD

**Issue by mvgadagi** [ghiscoding/Angular-Slickgrid#554]
## I'm submitting a Feature request
Thanks for publishing the new feature for tree data as referred here https://ghiscoding.github.io/angular-slickgrid-demos/#/tree-data-hierarchical

### Motivation / Use Case

**Feature request** : Enabling the editor for the tree data rows

### Expected Behavior

When users adds the configurations for the gridOptions with editable : true , the edit feature should be working for tree grid as well

### Other Information

 I just think it's quite possible as when we click on the cell we have the reference of __parentId & _treeLevel inside dataContext object

Kindly let me or guide so that I can contribute to this feature as well.

Regards,
Mahesh

**Comment by ghiscoding** [comment]
I don't understand your question, Editors do work with Tree Data and I have a grid with Editors without any issues. I also don't understand what you mean with the `__parentId` and `__treeLevel` these are used internally

**Comment by mvgadagi** [comment]
Hello @ghiscoding , I wanted to implement edit for this grid https://ghiscoding.github.io/angular-slickgrid-demos/#/tree-data-hierarchical 

Like in the above demo , I want to make Size column as editable and as soon user double clicks on the cell it should allow me to edit ,

Please ignore the information regarding the __parentId and __treeLevel I wanted to provide some additional information

I had tried with 

```
this.gridOptions = {
     asyncEditorLoading: true,
      autoEdit: true,
      editable: true
}
```

and added the column with 

```
editor: { model: Editors.float}
```

But it's showing me to edit the cell for size

**Comment by ghiscoding** [comment]
You're missing an important flag in your grid option `enableCellNavigation: true,`, SlickGrid doesn't work without this flag (I never understood why though).

This happens to me so often, I added a note in the [Editors - Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Editors#required-grid-option) to emphasize this flag, we often forget to add it. I never really understood why this flag must be enabled in SlickGrid but it is what it is

![image](https://user-images.githubusercontent.com/643976/89418882-a797c480-d6fe-11ea-9806-7fd48a8199e0.png)
