### ISSUE TITLE
Validate singleSelect editable is not firing onValidationError(e, args)

### ISSUE THREAD

**Issue by ranjithitwizard** [ghiscoding/Angular-Slickgrid#571]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.1.1     | 
| Angular-Slickgrid   | 2.18.7   | 
| TypeScript              | 3.8.3     | 

### Describe the Bug

`Editors.singleSelect` cell validation is not firing the `onValidationError(e,args)` after cell edit completes.
### Steps to Reproduce

1. create a column with inline editable as `Editor.singleSelect`
2. Define custom validator function to validate the value after cell edit
3. OnValidationError is not firing if any error after edit completes

 
### Expected Behavior

onValidationError should taken place

### Current Behavior

Error handling is not prompting the alert message

### Code Sample

```
onValidationError(e, args) {
     alert(args.validationResults.msg);
}
```

**Comment by ghiscoding** [comment]
This is now fixed and released under the new version [2.21.3](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.21.3) 

Please upvote ⭐ if you haven't already. 
Cheers
