### ISSUE TITLE
All selected text is appearing for the Editors.singleSelect 

### ISSUE THREAD

**Issue by ranjithitwizard** [ghiscoding/Angular-Slickgrid#572]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.1.1     | 
| Angular-Slickgrid   | 2.18.7   | 
| TypeScript              | 3.8.3     | 

### Describe the Bug

`All selected` text is appearing when the `Editors.singleSelect` has only one item in the list.

### Steps to Reproduce

1. create a column with inline editable as `Editor.singleSelect`
2. set `editor.collections` value with only one item
3. its showing `All selected` text is appearing like `multiselect` dropdown

### Expected Behavior

Only the selected value should shown for the `singleSelect` editable dropdown.

### Current Behavior

 `All selected` text is appearing 

### Code Sample

Attached sample screenshot 

![All_selected_bug](https://user-images.githubusercontent.com/7435997/92350906-f4086280-f0f7-11ea-9cdb-eb43fd3e8666.png)

**Comment by ghiscoding** [comment]
This is normal and is the default behavior of the `multiple-select.js` library which is used by Angular-Slickgrid, so there's nothing that can be done here

**Comment by ranjithitwizard** [comment]
Thanks for your reply.. But I couldn't find the `All Selected` text for single selection dropdown in the below `multiple-select.js` 
examples. 

[Example 1](http://multiple-select.wenzhixin.net.cn/examples#single-row.html) | [Example 2](http://multiple-select.wenzhixin.net.cn/examples#single-radio.html)

Also it doesn't make any sense the `All Selected` for single select dropdown values when it has only one value. Is there any workaround to fix this issue ?

**Comment by ghiscoding** [comment]
I didn't write that external library, however I use a modified version of it which in the [assets/](https://github.com/ghiscoding/Angular-Slickgrid/tree/master/src/assets/lib/multiple-select) folder (for example the original lib doesn't have an "OK" button for multiple selection, I wrote that), it's forked from the version `1.2.1` and if the author made a fix for that, then it won't be included in my copy.

The Single Select options are defined [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/editors/selectEditor.ts#L105) if you find any problem then create a PR. but I'd be surprised if you find anything. or if you find anything wrong in my copy of the `multiple-select.js`, again please make a PR

If that doesn't help you, well I'm sorry but I'm going to leave it at that.
