### ISSUE TITLE
excel-builder-webpacker GPLv3 license 

### ISSUE THREAD

**Issue by arturtv** [ghiscoding/Angular-Slickgrid#578]
## General Topic

First want to thank you for the great work.

I have a question regarding the license, the library itself is MIT, however it looks like it has dependency of
"excel-builder-webpacker": "^1.0.6", 
https://github.com/ghiscoding/Angular-Slickgrid/blob/master/package.json#L104

which is marked as GPLv3: https://www.npmjs.com/package/excel-builder-webpacker/v/1.0.6

Not really expert however it seems that it forces to use Angular-Slickgrid as GPLv3 due to dependency

### Expected Behavior
excel-builder-webpacker to be optional

### Current Behavior
Excel export is one of the optional functionalities that probably many do not require

### Possible Solution
maybe to move to more permissive libraries or make excel-builder-webpacker optional dependency

**Comment by winghei** [comment]
Had also issue on this one. Is it possible to make the library optional?

**Comment by ghiscoding** [comment]
it will be optional in the next `major` version

**Comment by ghiscoding** [comment]
@winghei as mentioned earlier, the Excel Export will be optional (opt-in) in the next `major` version and I just announced it, you can read more about that in the [Release](https://github.com/ghiscoding/Angular-Slickgrid/releases/) section.

**Comment by ghiscoding** [comment]
@winghei next `major 3.x` of Angular-Slickgrid is out and both Export Services are optional, you can choose which one to install. See the [Release](https://github.com/ghiscoding/Angular-Slickgrid/releases) section
