### ISSUE TITLE
When using Grouping, selection presets are not visibly shown when using SetDroppedGroups

### ISSUE THREAD

**Issue by oppassum** [ghiscoding/Angular-Slickgrid#585]
### Describe the Bug
I have enabled Groups and Checkbox Selection at the same time. When adding in presets (via datacontextIDs), the preset selections get honored, but the UI does not update to show that they are selected until you select another box.
### Steps to Reproduce

I'm using code combined from draggablegroups example and rowselection (multiselect) example.

Grid Options:

```
this.gridOptions = { 
            enableDraggableGrouping: true,
            createPreHeaderPanel: true,
            showPreHeaderPanel: true,
            preHeaderPanelHeight: 40,
            enableFiltering: true,
            enableSorting: true,
            enableRowSelection: true,
            enableCellNavigation: true,
            enableCheckboxSelector: true,
            checkboxSelector: {
                // you can toggle these 2 properties to show the "select all" checkbox in different location
                hideSelectAllCheckbox: true,
              },
            rowSelectionOptions: {
                // True (Single Selection), False (Multiple Selections)
                selectActiveRow: false
            },
            exportOptions: {
              sanitizeDataExport: true
            },
            gridMenu: {
              onCommand: (e, args) => {
                if (args.command === 'toggle-preheader') {
                  // in addition to the grid menu pre-header toggling (internally), we will also clear grouping
                  this.clearGrouping();
                }
              },
            },
            draggableGrouping: {
              dropPlaceHolderText: 'Drop a column header here to group by the column',
              // groupIconCssClass: 'fa fa-outdent',
              deleteIconCssClass: 'fa fa-times',
              onGroupChanged: (e, args) => this.onGroupChanged(args),
              onExtensionRegistered: (extension) => this.draggableGroupingPlugin = extension,
            },
            presets: {
                // you can presets row selection here as well, you can choose 1 of the following 2 ways of setting the selection
                // by their index position in the grid (UI) or by the object IDs, the default is "dataContextIds" and if provided it will use it and disregard "gridRowIndexes"
                // the RECOMMENDED is to use "dataContextIds" since that will always work even with Pagination, while "gridRowIndexes" is only good for 1 page
                rowSelection: {
                  // gridRowIndexes: [2],           // the row position of what you see on the screen (UI)
                  dataContextIds: [8411,8412,8413]  // (recommended) select by your data object IDs
                }
            }
          };
```

```
angularGridReady(angularGrid: AngularGridInstance) 
{
     this.angularGrid = angularGrid;
     this.gridObj = angularGrid.slickGrid; // grid object
     this.dataviewObj = angularGrid.dataView;
     this.draggableGroupingPlugin.setDroppedGroups(['orderNumber', 'foamType', 'thickness']); //THIS LINE CAUSES AN ERROR
}
```

data is loaded in after angularGridReady is called.

Order of operations:
1. Prepare Grid
2. angularGridReady fires
3. loadData() loads data into dataset

### Expected Behavior
Expected that when looking at the grid, the appropriate rows (defined by the presets in the gridoptions) should highlight selected.

### Current Behavior
The selected rows do not visibly show selected. If I click to select another row, or update the dataset a second time (done in my tests by clicking a refresh button), the highlighted rows show correct.

### Possible Solution
I've done a work-around on this by not grouping the rows until after the first time the dataset is loaded, like so:
```
this.dataset = data.items;
         if(this.firstDataPrep)
         {
             this.firstDataPrep = false;
             this.gridObj.invalidate();
             setTimeout(() => {
                 //timeout added to allow selected session rows to be selected when the grid
                 //first loads. Would not work with groups already in place. T.L. 9.18.2020
                 this.draggableGroupingPlugin.setDroppedGroups(['orderNumber', 'foamType', 'thickness']);  
             }, 75);
           
         }
```
The timeout of 75ms seemed necessary to update the grid. It did not work without it.

**Comment by ghiscoding** [comment]
Grouping is not part of the Grid State / Grid Presets and I don't have any intention of adding it either, your patch with a delay is the way to go and it's normal that it requires a delay because of Angular you need a full life cycle to be passed before doing anything with the grid. The Grid Presets feature was always in my mind a quick presets of the grid such as (filter, sort, column position), it was never supposed to be more than that, even the row selections wasn't supposed to be part of the Grid Presets, I manage to add it but it was quite challenging, I want to leave at that, I don't want to add the Grouping in the mix, it's just too much so you'll have to handle it yourself.

There's multiple ways of getting the 3rd party plugin instance like the Draggable Grouping Plugin, but the easiest way to get it is probably this new way
```ts
angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
    const draggableGroupingPlugin = angularGrid.extensions.draggableGrouping.instance || {};
    console.log(draggableGroupingPlugin);
  }
```
You might not know about it since I added it couple months ago, it's described as number 3 in the [Release v2.20.x](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.20.2), you can follow the Wiki that is referenced in the release description.

**Comment by oppassum** [comment]
I didn't know, thanks!

That makes sense and I figured this might be your answer. I wanted to make the issue in case anyone else ran into it, that way my solution was also visible.

Thanks so much for the grid! It's amazing and exactly what I've been looking for!

**Comment by ghiscoding** [comment]
Yes that is a good point, thanks for that.
