### ISSUE TITLE
RowDetailPreloadComponent does not properly destroy itself

### ISSUE THREAD

**Issue by jsEveryDay** [ghiscoding/Angular-Slickgrid#589]
### Your Environment
| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9        | 
| Angular-Slickgrid   | latest        | 
| TypeScript              | latest        | 

### Describe the Bug
The preloader component does not destroy itself when you collapse a row, instead it throws itself at the bottom of the DOM and the components keep piling up every time you hit the - (minus) icon to collapse a row.
### Steps to Reproduce
Visit this link https://ghiscoding.github.io/angular-slickgrid-demos/#/rowdetail
Click the + and - icon several times. Depending on the size of your screen you will likely not see a scroll bar for the page but only on the grid. As you keep hitting the - (minus) button you will notice that the page keeps growing longer and the scroll bar appears. Once you scroll at the bottom you don't see anything there but upon inspection you will notice that the "Loading..." elements keep piling up. In my own code this is not even hidden, it just shows the loading at the bottom.
![image](https://user-images.githubusercontent.com/16431055/94578593-ee5cf300-0245-11eb-81bc-376da2a70ba1.png)
While using the preloadComponent seems to be optional, my code throws an exception in the console if I don't use it. 
![image](https://user-images.githubusercontent.com/16431055/94579762-2d3f7880-0247-11eb-86fa-e866025b70ad.png)
The current solution for me is to create a blank component with nothing in it ``. Not ideal.

### Expected Behavior
The component removes itself, same as when you switch between row expansions. So everything works as expected when you simply hit the + buttons and switch rows without ever collapsing the currently active expansion.

### Current Behavior
See steps to reproduce above. Screenshot included.

**Comment by ghiscoding** [comment]
I see the problem that it creates a bunch of `<ng-component>` but I have no time to fix this and I'm not even using this feature at all. In my other lib [Aurelia-Slickgrid](https://github.com/ghiscoding/aurelia-slickgrid), I use `<slot>` which works better than recreating the component every time like I do here in Angular, `slot` seems to now be available in Angular and it might be better to rewrite the code to use `slot` but again I have no time to look into this. The only quick troubleshoot that I had time to do was to find out that it happens after the Row Detail event of `onAfterRowDetailToggle` which then calls `renderPreloadView()` every time the event gets triggered on this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts#L180) and that is what piles up these pre-load component in the DOM, of course that is a problem and they should be destroyed before creating new ones but I don't know how to delete these `<ng-component` and I have no time to look into this.
 
If you have a way to fix it then please create a Pull Request, else this might end up being opened forever unless you help.

**Comment by jsEveryDay** [comment]
Thank you for your prompt reply, yeah I've been too lazy to look into why it happens.
I'll fix it and send an MR.

Closing this ticket temporarily. Thanks again.

**Comment by ghiscoding** [comment]
oh that is sad, I was hoping you could help.
