### ISSUE TITLE
Columns are autosized even with relevant options set to false

### ISSUE THREAD

**Issue by pcurrivan** [ghiscoding/Angular-Slickgrid#60]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

**Current behavior:**
With forceFitColumns and autoFitColumnsOnFirstLoad set to false, columns are still autosized. It looks like the ResizerService calls autosizeColumns regardless of these options, both when the service is initialized for a grid and every time it responds to a resize event.

**Expected/desired behavior:**
With forceFitColumns and autoFitColumnsOnFirstLoad set to false, columns are never autosized.  These options should be used in the ResizerService.

* **What is the motivation / use case for changing the behavior?**
With many columns, autosizing them results in them all being too small.  Instead I want to set column widths manually and for the library not to interfere with these widths.

**Comment by ghiscoding** [comment]
Perfect timing, it's now fixed and under the new version [1.6.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v1.6.0)

You probably just need to use the new flag `enableAutoSizeColumns` without `autoFitColumnsOnFirstLoad` 

Cheers and thanks for the up vote ⭐️ 👍

**Comment by pcurrivan** [comment]
Thank you for the quick fix.  Looks like you did miss one case, though, when hiding a column (autoResizeColumns in controlAndPlugin.service.ts).

**Comment by ghiscoding** [comment]
@pcurrivan 
I don't see any missed ones, can you send me the line number?

Also it looks like running an `ng build --prod` fails because of some CSS, I'm investigation and might have to release a patch update.

**Comment by ghiscoding** [comment]
hmm right I saw that one but thought it was a utility, I didn't see who called it. I'll change it thanks. Have you had a chance to try it? Does it work as intended for the most part?

**Comment by pcurrivan** [comment]
Other than that it seems to work.

**Comment by ghiscoding** [comment]
After 30min of investigating, I finally found the reason why Prod build was failing. I re-released under version `1.6.1` so please use that latest one. It also include the change you last told. 

Thanks for the feedback
Cheers
