### ISSUE TITLE
Pagination dropdown selects the first pageSize instead of the selected gridOptions.pagination.pageSize

### ISSUE THREAD

**Issue by jr01** [ghiscoding/Angular-Slickgrid#602]
### Your Environment
| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 10.1        | 
| Angular-Slickgrid   | 2.22.1        | 
| TypeScript              | 3.9        | 

### Describe the Bug
The pagination select control on the bottom right always selects the first pageSize instead of the defaultPageSize

### Steps to Reproduce
```
const defaultPageSize = 20;
pagination: {
        pageNumber: 1,
        pageSizes: [10, 15, 20, 25, 30, 40, 50, 75, 100],
        pageSize: defaultPageSize
}
```
The select control shows 10 as selected.

### Expected Behavior
The select control should show 20 as selected.

### Current Behavior
The select control shows 10 as selected.

### Possible Solution
Bind to `[selected]` on the `<option>` instead of binding to `[value]` on the `select` in https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/components/slick-pagination.component.html#L41

```
<select id="items-per-page-label" (change)="changeItemPerPage($event)">
      <option value="{{pageSize}}" [selected]="pageSize === itemsPerPage"  *ngFor="let pageSize of availablePageSizes">{{pageSize}}</option>
    </select>
```

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

### Code Sample
Try it in any of your demo's.

Let me know if you need a PR with a fix.

**Comment by ghiscoding** [comment]
That would be great if you can create a PR
