### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by SteveCorbett** [ghiscoding/Angular-Slickgrid#61]
We are using Angular-Slickgrid with Angular 6 and have discovered that the declarations of the colum definitions and grid options cannot be left as undefined/null.

The "Create a basic grid" in the Wiki "HOWTO Step by Step" needs to be corrected as follows:
..
export class GridBasicComponent implements OnInit {
  **columnDefinitions: Column[] = [];** 
  **gridOptions: GridOption = {};**
  dataset: any[];
..

**Comment by ghiscoding** [comment]
@SteveCorbett 
I'm still using Angular 5 in our current project so I can't really say if that is true or not but in Angular 5 that is not necessary, just defining the variable without assigning it is enough. Are you getting an error or something when you remove the assignment of empty array/object?

**Comment by SteveCorbett** [comment]
Yes, without "GridOption = {}" the following error is generated: 
> ERROR  TypeError: Cannot read property 'enableAutoResize' of undefined

This relates to the following line from the ngOnInit method of angular-slickgrid.component.ts:
>if (!this.gridOptions.enableAutoResize && !this.gridOptions.autoResize)

without "Column[] = []" the following error is generated: 
> ERROR TypeError: Cannot read property 'map' of undefined

This relates to the following line from the initialization method:
>this._columnDefinitions = this._columnDefinitions.map(function (column)

**Comment by ghiscoding** [comment]
Under which method do you set the actual columnDefinitions and gridOptions? If it's not under the `ngOnInit`, it might be normal to get this error. Basically, if you are assigning these variables too late in the process, your grid might not behave the way you want it. Does the grid show up correctly on your side after doing the changes that you mentioned? I just want to make sure of that your order is correct before changing the Wiki. Thanks for the feedback

**Comment by SteveCorbett** [comment]
Yes, we're setting these in the ngOnInit method.  Without these changes the grids appeared correctly but the errors caused other issues with the application (including subscriptions not working). These changes make the application work correctly.

Alternatively, the code should be updated to check for the assignment of the columnDefinitions and gridOptions variables before attempting to access their properties.

**Comment by ghiscoding** [comment]
Ok I've updated the HOWTO, I'll recheck that when we go with Angular 6 (or we might skip to 7 instead which is coming out soon). Also if you like the lib, you can also up vote ⭐️  it helps to make it more popular in the search. 

Thanks for the feedback
