### ISSUE TITLE
JQuery Error from slick.cellrangedecorator.js when using nguniversal SSR

### ISSUE THREAD

**Issue by blubear2shy** [ghiscoding/Angular-Slickgrid#612]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 10.1.6       | 
| Angular-Slickgrid   | 2.22.4       | 
| TypeScript              | 4.0.3       | 
| @nguniversal/builders  | 10.1.0   | 
| @types/express  | 4.17.0   | 
| @types/node  | 12.11.1   | 

### Describe the Bug
When using server side render with nguniversal, I am experiencing 'ReferenceError: jQuery is not defined' error when running my output file '\dist\appname\server\main.js'. This error comes from the function'CellRangeDecorator', which is from './node_modules/slickgrid/plugins/slick.cellrangedecorator.js'.

### Steps to Reproduce
1. Create an angular 10 app
2. Add ssr with 'ng add @nguniversal/express-engine'
3. Add angular-slick-grid by following HOWTO---Step-by-Step
4. Create a simple table.
5. Run 'npm run dev:ssr', or run 'npm run build:ssr' and follow by 'npm run serve:ssr'
6. Error displayed

### Expected Behavior
Supporting SSR

### Current Behavior
{appName}\dist\{appName}\server\main.js:{some line number}
})(jQuery);
   ^
ReferenceError: jQuery is not defined

**Comment by ghiscoding** [comment]
jQuery is a dependency of Angular-Slickgrid, if you don't have it then Yes you will get some errors.

**Comment by blubear2shy** [comment]
> jQuery is a dependency of Angular-Slickgrid, if you don't have it then Yes you will get some errors.

JQuery was installed to the project. When adding angular-slick-grid, I did install all dependencies that 'HOWTO---Step-by-Step' has mentioned and updated angular.json. Also, this issue only occurs when using nguniversal SSR, otherwise the grid works perfectly.

**Comment by ghiscoding** [comment]
Well sorry but I never used, and probably never will use, NgUniversal SSR so unfortunately I can't help you with that. But those errors are only thrown when jQuery isn't loaded so you should double check that it is correctly loaded, Again sorry but I'm going to close this issue, I don't believe this is a problem with the lib, unless proven otherwise and if that is the case then we can re-open the issue.
