### ISSUE TITLE
hide column after reorder doesn't work

### ISSUE THREAD

**Issue by ljacques** [ghiscoding/Angular-Slickgrid#62]
**I'm submitting a bug report**
* **Library Version:**
1.6.1

* **Operating System:**
Windows [10]
* **Browser:**
all 

**Current behavior:**

I noticed that when you move column order with the mouse. if you try to hide column it doesn't work.

for example in https://ghiscoding.github.io/angular-slickgrid-bs4-demo/#/basic

on the grid 1 move the "title" column in the second place and try to hide it.

**Comment by ghiscoding** [comment]
Works for me
![2018-09-06_09-35-41](https://user-images.githubusercontent.com/643976/45160783-47b5dd80-b1b8-11e8-92d9-74ea1d4a83bc.gif)

**Comment by ghiscoding** [comment]
ah you're talking about the Column Header Menu, that's a different implementation. The method called is [hideColumn()](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/controlAndPlugin.service.ts#L422), if you can help in troubleshooting it that would be great

**Comment by ljacques** [comment]
yep I'm going to see about that to fix this.

**Comment by ljacques** [comment]
Change this line
`this.visibleColumns = this.removeColumnByIndex(this.visibleColumns, columnIndex);`
to
`this.visibleColumns = this.removeColumnByIndex(this._grid.getColumns(), columnIndex);`

i'ma think it's work like that because this._grid.getColumns() take care of the column's order but this.visibleColumns not.

**Comment by ghiscoding** [comment]
Ah right that make sense, that would probably fix the issue after we move any column. I also that after moving the column, it was hiding more than 1 column, hopefully that fixes it too. 

I should be able to push the fix and a new patch release sometime tonight. 

Merci :)

**Comment by ghiscoding** [comment]
@ljacques 
Fixed and pushed new release `1.6.2` on [NPM](https://www.npmjs.com/package/angular-slickgrid), thanks for the help on troubleshooting and fixing the issue :)

Merci encore ;)

**Comment by ljacques** [comment]
c'est un plaisir ;-)
