### ISSUE TITLE
Build error - jQuery reference error.

### ISSUE THREAD

**Issue by roopeshkurian** [ghiscoding/Angular-Slickgrid#639]
### Your Environment
| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 11.0.2   | 
| Angular-Slickgrid   | 2.23.2   | 
| TypeScript              | 4.0.5     | 

### Describe the Bug
 I was using Angular-Slickgrid@2.23.0 before.  Everything was working good. But after upgrading to Angular-Slickgrid@2.23.2    I am unable to make the build.  When I am trying to build its giving a jQuery reference error. When I checked the files I found that this reference is new. In the previous version we do not have this reference. 

### Steps to Reproduce
 Upgrade to Angular-Slickgrid@2.23.2  and try to build to project using ng build --prod --build-optimizer

### Expected Behavior
 Normally it should build the application without any error. 

### Current Behavior
 When I  am trying to use ng build --prod --build-optimizer I am getting the following error. 

Error: node_modules/angular-slickgrid/app/modules/angular-slickgrid/editors/dualInputEditor.d.ts:38:26 - error TS2503: Cannot find namespace 'JQuery'.     

38     handleKeyDown(event: JQuery.Event): void;
                            ~~~~~~
node_modules/angular-slickgrid/app/modules/angular-slickgrid/editors/dualInputEditor.d.ts:1:23 - error TS2688: Cannot find type definition file for 'jquery'.

1 /// <reference types="jquery" />
                        ~~~~~~

### Possible Solution
 I think we are missing some reference. We may wanted to add proper reference. 

### Code Sample

Old working code. 
 node_modules/angular-slickgrid/app/modules/angular-slickgrid/editors/dualInputEditor.d.ts

import { Column, ColumnEditor, ColumnEditorDualInput, Editor, EditorArguments, EditorValidator, EditorValidatorOutput, GridOption, SlickEventHandler } from '../models/index';
export declare class DualInputEditor implements Editor {
    private args;
    private _eventHandler;
    private _isValueSaveCalled;
    private _lastEventType;
    private _lastInputKeyEvent;
    private _leftInput;
    private _rightInput;
    private _leftFieldName;
    private _rightFieldName;
    originalLeftValue: string | number;
    originalRightValue: string | number;
    /** SlickGrid Grid object */
    grid: any;
    /** Grid options */
    gridOptions: GridOption;
    constructor(args: EditorArguments);
    /** Get Column Definition object */
    readonly columnDef: Column | undefined;
    /** Get Column Editor object */
    readonly columnEditor: ColumnEditor;
    /** Get the Editor DOM Element */
    readonly editorDomElement: {
        leftInput: HTMLInputElement;
        rightInput: HTMLInputElement;
    };
    readonly editorParams: ColumnEditorDualInput;
    readonly eventHandler: SlickEventHandler;
    readonly hasAutoCommitEdit: any;
    readonly isValueSaveCalled: boolean;
    /** Get the Shared Validator function, can be passed in Editor property or Column Definition */
    readonly validator: EditorValidator | undefined;
    init(): void;
    handleFocusOut(event: any, position: 'leftInput' | 'rightInput'): void;
    handleKeyDown(event: KeyboardEvent): void;
    destroy(): void;
    createInput(position: 'leftInput' | 'rightInput'): HTMLInputElement;
    focus(): void;
    getValues(): {
        [fieldName: string]: string | number;
    };
    setValues(values: Array<number | string>): void;
    applyValue(item: any, state: any): void;
    applyValueByPosition(item: any, state: any, position: 'leftInput' | 'rightInput'): void;
    isValueChanged(): boolean;
    loadValue(item: any): void;
    loadValueByPosition(item: any, position: 'leftInput' | 'rightInput'): void;
    save(): void;
    serializeValue(): {};
    serializeValueByPosition(position: 'leftInput' | 'rightInput'): string | number;
    getDecimalPlaces(position: 'leftInput' | 'rightInput'): number;
    getInputDecimalSteps(position: 'leftInput' | 'rightInput'): string;
    validate(inputValidation?: {
        position: 'leftInput' | 'rightInput';
        inputValue: any;
    }): EditorValidatorOutput;
    validateByPosition(position: 'leftInput' | 'rightInput', inputValue?: any): EditorValidatorOutput;
}

Not working new code 
 node_modules/angular-slickgrid/app/modules/angular-slickgrid/editors/dualInputEditor.d.ts

/// <reference types="jquery" />
import { DOMEvent, Column, ColumnEditor, ColumnEditorDualInput, Editor, EditorArguments, EditorValidator, EditorValidatorOutput, GridOption, SlickEventHandler } from '../models/index';
export declare class DualInputEditor implements Editor {
    private args;
    private _bindEventService;
    private _eventHandler;
    private _isValueSaveCalled;
    private _lastEventType;
    private _lastInputKeyEvent;
    private _leftInput;
    private _rightInput;
    private _leftFieldName;
    private _rightFieldName;
    originalLeftValue: string | number;
    originalRightValue: string | number;
    /** SlickGrid Grid object */
    grid: any;
    /** Grid options */
    gridOptions: GridOption;
    constructor(args: EditorArguments);
    /** Get Column Definition object */
    readonly columnDef: Column | undefined;
    /** Get Column Editor object */
    readonly columnEditor: ColumnEditor;
    /** Get the Editor DOM Element */
    readonly editorDomElement: {
        leftInput: HTMLInputElement;
        rightInput: HTMLInputElement;
    };
    readonly editorParams: ColumnEditorDualInput;
    readonly eventHandler: SlickEventHandler;
    readonly hasAutoCommitEdit: any;
    readonly isValueSaveCalled: boolean;
    /** Get the Shared Validator function, can be passed in Editor property or Column Definition */
    readonly validator: EditorValidator | undefined;
    init(): void;
    handleFocusOut(event: DOMEvent<HTMLInputElement>, position: 'leftInput' | 'rightInput'): void;
    handleKeyDown(event: JQuery.Event): void;
    destroy(): void;
    createInput(position: 'leftInput' | 'rightInput'): HTMLInputElement;
    focus(): void;
    getValues(): {
        [fieldName: string]: string | number;
    };
    setValues(values: Array<number | string>): void;
    applyValue(item: any, state: any): void;
    applyValueByPosition(item: any, state: any, position: 'leftInput' | 'rightInput'): void;
    isValueChanged(): boolean;
    loadValue(item: any): void;
    loadValueByPosition(item: any, position: 'leftInput' | 'rightInput'): void;
    save(): void;
    serializeValue(): {};
    serializeValueByPosition(position: 'leftInput' | 'rightInput'): string | number;
    getDecimalPlaces(position: 'leftInput' | 'rightInput'): number;
    getInputDecimalSteps(position: 'leftInput' | 'rightInput'): string;
    validate(inputValidation?: {
        position: 'leftInput' | 'rightInput';
        inputValue: any;
    }): EditorValidatorOutput;
    validateByPosition(position: 'leftInput' | 'rightInput', inputValue?: any): EditorValidatorOutput;
}

**Comment by ghiscoding** [comment]
That was mentioned in the [release](https://github.com/ghiscoding/Angular-Slickgrid/releases) just read it there (install `@types/jquery` dev dependency)

**Comment by roopeshkurian** [comment]
> 
> 
> That was mentioned in the [release](https://github.com/ghiscoding/Angular-Slickgrid/releases) just read it there (in short, just install `@types/jquery` dev dependency)

Thank you so much. It worked. Sorry for wasting your time.

**Comment by ghiscoding** [comment]
no worries, nice to see a happy customer 😉 ⭐
