### ISSUE TITLE
Export To File Not Respecting datasetIdPropertyName

### ISSUE THREAD

**Issue by SteveCorbett** [ghiscoding/Angular-Slickgrid#67]
The export functions only output heading lines (ie. no data rows) if the "datasetIdPropertyName" is defined in "gridOptions".  The export function only works if the data has an "id" property.

**Comment by ghiscoding** [comment]
Please provide your entire `gridOptions` and the full error thrown. I need something to replicate the issue.

**Comment by SteveCorbett** [comment]
This should be enough to replicate, 
[ExportIssue.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/2395171/ExportIssue.zip)

**Comment by SteveCorbett** [comment]
As per my original post, if the "datasetIdPropertyName" is defined in "gridOptions" then only the header line is exported.  Data rows are only exported if "datasetIdPropertyName" is not specified.  No errors are thrown, the export function does not work correctly.

**Comment by ghiscoding** [comment]
I made a commit to fix it, but won't release a new version until the end of the week, so stay tuned.

**Comment by ghiscoding** [comment]
@SteveCorbett 
This was released under the new patch version `1.6.9`

Also, if you like the lib you can also up vote ⭐️, this helps in making it more popular in the search.
Cheers
