### ISSUE TITLE
grid header menus not visible after adding column(s) dynamically

### ISSUE THREAD

**Issue by mdkamrul** [ghiscoding/Angular-Slickgrid#689]
### My Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | ^11.0.5        | 
| Angular-Slickgrid   | ^2.23.2        | 
| TypeScript              | ~4.0.5        | 

### Bug description
I am trying add dynamic column to my grid. But when I add it at that time header menu not visible that are built in. If I add new custom header menu at that time that menu only visible. On the other hand search filter completely invisible at all.

I have seen the exact same behavior on the documentation page
https://ghiscoding.github.io/Angular-Slickgrid/#/editor

### Steps to Reproduce
I have initialized my grid at page load with mandatory field. And when my data come than I add some extra field which is come from my dynamic field of my record.

### Expected Behavior
It should show header menu as like other field and also show search box if I configured.

### Current Behavior
It adding my dynamic column but not showing header menu and not showing search box

### Code Sample
this.columnDefinitions = [];
this.columnDefinitions = this.columnDefinitions.slice();
newColumn.unshift(...this.getActionColumn());
this.gridObj.setColumns(newColumn);

![slick-grid-header-menu](https://user-images.githubusercontent.com/11798121/106752487-b67f1580-6654-11eb-8c19-a34f15661ca3.gif)

**Comment by ghiscoding** [comment]
As you can see the bot is very strict in checking that you fill all the form, you must have missed one somewhere... just make sure to fill them all next time.

I see the problem, but I don't have time to look into it. It might need to re-render the header menu when the column definitions changes. Dynamically changing the column definitions list, will call `updateColumnDefinitionsList` [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts#L493) and it might be the place to re-render the header menu. If you have time to submit a PR that would be great

**Comment by mdkamrul** [comment]
Thanks for you quick response and this is very useful grid that I found.

Great job!!!

**Comment by ghiscoding** [comment]
I got it working but I don't have time to finish the PR now, will go back at it later. By the way, the filter does work in the Editor example, however I had to remove a piece of code that wasn't supposed to be there when creating the column dynamically. So you mention 2 things in your issue but I see only 1 problem not 2 (the filter is ok)

**Comment by ghiscoding** [comment]
I merged the fix but I won't release a new version until at least another week. I got something in the pipeline, I'll comment back when it's released

**Comment by ghiscoding** [comment]
@mdkamrul this is now released, see latest release [2.26.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.26.0)

Enjoying the lib? Make sure to upvote ⭐ and if you already have... well then thank you 😺 
Cheers
