### ISSUE TITLE
updateItemById refresh all the grid 

### ISSUE THREAD

**Issue by bzhjack** [ghiscoding/Angular-Slickgrid#715]
## I'm submitting a Bug report
using dataView.onRowsOrCountChanged instead of dataView.onRowCountChanged to refresh metrics this refreshes the whole grid in the case of an updateItemById.

### Your Environment
| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  |8.3        | 
| Angular-Slickgrid   |2.26.1   | 
| TypeScript              | 3.5.3    | 

### Describe the Bug
before
```
     this._eventHandler.subscribe(dataView.onRowCountChanged, (_e: Event, args: any) => {
```
now
```
      this._eventHandler.subscribe(dataView.onRowsOrCountChanged, (_e: Event, args: any) => {
```

### Steps to Reproduce
i noticed this using updateItemById to in a sgOnCellChange
```
onCellChanged(e, args) {
    const metadata = this.angularGrid.gridService.getColumnFromEventArguments(args);
    if (metadata.columnDef.id === 'quantity') {
      const goodRec = findTabLinesById(this.tabLines, metadata.dataContext.id);
      if (goodRec) {
       goodRec.disable = true;
         this.angularGrid.gridService.updateItemById(goodRec.id, goodRec);
      }
    }
}
```

### Expected Behavior
Refresh only the current line involve by the updateItemById 

### Current Behavior
the whole grid is refreshed and this leads to the exit of the edition of the next cell

**Comment by ghiscoding** [comment]
@bzhjack 
This is now released with a few other new features, refer to the new [release](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.27.0)
