### ISSUE TITLE
"useEditor is not a constructor" when using setColumns

### ISSUE THREAD

**Issue by LeoDupont** [ghiscoding/Angular-Slickgrid#74]
**I'm submitting a bug report**

* **Library Version:**
4.5.2

* **Language:**
TypeScript 2.7.2

**Current behavior:**
When enabling edition in the grid's options and setting editors for each column definitions, I get the following error when I try to edit a cell:
```
ERROR TypeError: useEditor is not a constructor
    at makeActiveCellEditable (slick.grid.js:3137)
    at setActiveCellInternal (slick.grid.js:3028)
    at gotoCell (slick.grid.js:3758)
    at HTMLDivElement.handleDblClick (slick.grid.js:2834)
    at HTMLDivElement.dispatch (jquery.js:5183)
    at HTMLDivElement.$event.dispatch (jquery.event.drag-2.3.0.js:382)
    at HTMLDivElement.push.../../node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js.$event.dispatch (jquery.event.drag-2.3.0.js:382)
    at HTMLDivElement.elemData.handle (jquery.js:4991)
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4053)
```

Here are my `gridOptions` and `columnDefinitions` objects:
```typescript
this.gridOptions = {
	editable: true,
	autoEdit: false,
	autoCommitEdit: false,
	enableCellNavigation: true,
	enableHeaderMenu: true,
};

this.columnDefinitions = [
	{
		id: 'col1_id', name: 'Column 1', field: 'col1',
		type: FieldType.string,
		editor: { model: Editors.text },
	},
	{
		id: 'col2_id', name: 'Column 2', field: 'col2',
		type: FieldType.string,
		editor: { model: Editors.text },
	},
];

// Then I fetch data from a back-end and add a column depending on the data received:
this.columnDefinitions.push({
	{
		id: 'colX_id', name: 'Column X', field: 'colX',
		type: FieldType.string,
		editor: { model: Editors.text },
	},
});

// And I update the grid's columns definitions:
// (this.angularGrid comes from the `onAngularGridCreated` event)
this.angularGrid.slickGrid.setColumns(this.columnDefinitions);
```

Before adding the "Column X", the editing works as expected.
But once it's added, each cell throws the mentioned error.

What should I do to add columns dynamically without breaking the cell editing feature?

**Comment by ghiscoding** [comment]
Dynamically adding new Column to the definition is little more complicate and Angular-Slickgrid was modified to work with that. However you must know that just doing a `push` to an array probably doesn't trigger a change (dirty checking), if you use `slice` it will though. 

You can see the [demo](https://ghiscoding.github.io/Angular-Slickgrid/#/localization) with the button "Dynamically Duplicate Column" and here's the [usage](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-localization.component.ts#L151), notice the `slice`

**Comment by LeoDupont** [comment]
Ok, I changed my `setColumns` for a `slice` and now it works:
```typescript
this.columnDefinitions = this.columnDefinitions.slice();
// instead of:
// this.angularGrid.slickGrid.setColumns(this.columnDefinitions);
```

Thanks!
