### ISSUE TITLE
Angular Slickgrid Select Dropdown keeps opening if we focus out for descendent dropdown

### ISSUE THREAD

**Issue by johnsdy779** [ghiscoding/Angular-Slickgrid#749]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 8.x.x        | 
| Angular-Slickgrid   | 2.27.x        | 
| TypeScript              | 3.x.x       | 

### Describe the Bug
Angular Slickgrid Select Dropdown keeps opening for descendent dropdown if we focus out 

### Steps to Reproduce
1. Click on select drop down
2. Focus out without selection it will open the dropdown for descendent row,

### Expected Behavior
Should Not open the dropdown for descendent row

### Current Behavior
Angular Slickgrid Select Dropdown keeps opening if we focus out for descendent dropdown

### Possible Solution
If we add autoCommitEdit: true it works but after this sometimes dropdown selection does not persists.

### Code Sample
gridOptions = {
      enableAutoResize: true, 
      enableCellNavigation: true,
      editable: true,
      autoEdit: true,
     // autoCommitEdit: true, // If we add this then it works but creates some other issues for dropdown selection
      enableColumnPicker: true
}
cellChange(){
 var ele={}
 grid.updateItem(ele);
}

Is there any other configuration that we missed?

**Comment by ghiscoding** [comment]
That is the default behavior of SlickGrid (core), you can use `autoCommitEdit: true` grid option to avoid that.
