### ISSUE TITLE
ERROR TypeError: using the flatpickr plugin v 4.2.3, Cli

### ISSUE THREAD

**Issue by sabeurch** [ghiscoding/Angular-Slickgrid#8]
This issue occurres when using the date editor as a colum editor, eg: Editors.date
Also happens when trying to use a custom date editor using "flatpickr".
**Error stack:**
```
ERROR TypeError: Fonction attendue
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Fonction attendue",
      message: "Fonction attendue",
      name: "TypeError",
      number: -2146823286,
      stack: "TypeError: Fonction attendue
   at DateEditor.prototype.init (eval code:49:9)
   at DateEditor (eval code:21:9)
   at makeActiveCellEditable (eval code:30449:13)
....
```

Deeper investigations in the issue: 
An instance of the flatpickr should be created as:
```
 //this.flatInstance = flatpickr(this.$input[0], pickerOptions);
 this.flatInstance = this.$input[0].flatpickr(pickerOptions);
```
Reference: [https://chmln.github.io/flatpickr/instance-methods-properties-elements/#retrieving-the-flatpickr-instance]

Would you please reassess sources on:
`angular-slickgrid\editors\dateEditor.ts , line 46 [...this.flatInstance = flatpickr(this.$input[0], pickerOptions);]`

Versions: es2017,  "@angular/cli": "1.6.0",  "flatpickr": "^4.2.3",  "@angular/core": "^5.1.0".

When I did the amendment:  `this.flatInstance = this.$input[0].flatpickr(pickerOptions); `
all now works fine.

**Comment by ghiscoding** [comment]
I don't think that I've seen this problem, however I see that you are using an earlier version than mine. Mine is set to `"flatpickr": "^4.0.6"`, are you on the latest and did the instance creation changed with that newer version?

**Comment by sabeurch** [comment]
Well, I am on the latest version of flatpickr.
I am not sure that they "flatpickr" changed the way of instanciation.
I'll try to go back to a previous version of "flatpickr": "^4.0.6" to see if issue comes from it.

**Comment by ghiscoding** [comment]
It works with your change, so I don't mind changing the code. Is it just this [1 line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/editors/dateEditor.ts#L46) of code? Do you want to make a PR or you rather have me do the change?

**Comment by sabeurch** [comment]
Please update the sources 👍

**Comment by ghiscoding** [comment]
Ok I'll do that, I'll assume that this is not an rush, right? I would rather include more commits in a version push, so probably near the end of this week if that is ok.

**Comment by sabeurch** [comment]
Please take your time, it is not so rush.
I confirm: When switched back into version  "flatpickr": "^4.0.6", the old way of instanciation works fine.
With lastest version "flatpickr": "^4.2.3", the above amendment is required.

**Comment by ghiscoding** [comment]
Thanks for the confirmation and code, your code change works with both versions so I'll use it. Your feedback is greatly appreciated and it is the reason why we open sourced this lib :)

**Comment by ghiscoding** [comment]
This is now fixed, I made an error in my commit message so it didn't reference it. Here's the [commit](https://github.com/ghiscoding/Angular-Slickgrid/pull/3).

Since I was in the `dateEditor` I also saw that I could use `ngx-translate` (if you use it) to get `currentLang` and apply the current locale to the Flatpickr, so it works dynamically now :) ... if you aren't really using `ngx-translate` fear not, it will use English by default.

This new [version 0.8.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v0.8.0) ended being huge, there's a lot of everything (fixes, new features, lot of refactoring). You should look at the list of [changes](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v0.8.0)

**Comment by sabeurch** [comment]
Great, thanks Ghislain.
