### ISSUE TITLE
ERROR TypeError: this._dataView.getItems is not a function

### ISSUE THREAD

**Issue by Mad4emno** [ghiscoding/Angular-Slickgrid#806]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 11.2.12        | 
| Angular-Slickgrid   | 2.30.2       | 
| TypeScript              | 4.1      | 

### Describe the Bug
I have a qute simple Grid which is showing some data from my own database. Before I updated Angular-slickgrid last week from 2.18.7 to the current Version 2.30.2, it worked fine. 
but after this very update I got an error message in the browser debugger:
"ERROR TypeError: this._dataView.getItems is not a function"

### Steps to Reproduce
Use Angular-Slickgrid Version 2.30.2 and a simple grid with data caught from a backend db. In addition get the current settings of filters/sorting/order of rows for the current user before loading the data. Some settings/code: see below.

### Expected Behavior
Data from DB show up automatically when app is started.

### Current Behavior
Error message "ERROR TypeError: this._dataView.getItems is not a function" and data do not show up. There no option to force them to show.

### Possible Solution
Found a wordaround because I have seen in the lib that although this_dataview should be set, it is not in this very position: line 9531 of angular-slickgrid.js, so method "getItems()" is not known:

      refreshTreeDataFilters(items) {
              var _a, _b;
              const inputItems = (_a = items !== null && items !== void 0 ? items : **this._dataView.getItems()**) !== null && _a !== void 0 ? _a : [];
              if (this._dataView && ((_b = this._gridOptions) === null || _b === void 0 ? void 0 : _b.enableTreeData) && inputItems.length > 0) {
                  this._tmpPreFilteredData = this.preFilterTreeData(inputItems, this._columnFilters);
                  this._dataView.refresh(); // and finally this refresh() is what triggers a DataView filtering check
              }

my fix is:

        let gridState = JSON.parse(data[0].Value);
        gridState.filters = null; // workaroud since Angular-Version 2.30.2 
        this.gridOptions.presets = gridState;

With this fix my data are shown again...
But actually I am thinking this should be fixed in the lib itself. 
Possible simple solution might be: if there are no filters (undefined), just set it as null like I did. I guess in method populateColumnFilterSearchTermPresets, but not sure anymore since I fixed this two days before...

### Code Sample
A simple Grid, no Tree:

        gridOptions: GridOption = {
            enableTreeData: false
          }

To load the current settings of the user:

        let gridState = JSON.parse(data[0].Value);
        this.gridOptions.presets = gridState;

All relevant (I guess so)code is:

    ngAfterViewInit(): void {
        this._stateSettingsService.getStateSettingsByKey(this.Settings_Id).then(
          (data) => {
            if (data != undefined && data.length > 0 && data[0].Value != undefined) {
              let gridState = JSON.parse(data[0].Value);
              // gridState.filters = null; // workaroud since Angular-Version 2.30.2 
              this.gridOptions.presets = gridState;
            }
            this.IsLoaded = true;
          })
          .catch((err) => { console.error(err) })
          .finally(() => {
            this.loadData();
          });

    if (this.HasTimer) {
      this._timer = timer(0, this.Timer);
      this._timer.subscribe(val => {
        this.loadData();
        if (this.HasPages && this.IsPagingAktiv) {
          this.goToNextPage();
        }
      });
    }
  }

    ngOnInit(): void {
      window.onbeforeunload = () => {
        this.IsLoaded = false;
      }
      if (this.HasPages) {
        this.gridOptions = {
          enablePagination: true,
          enableFiltering: true,
          pagination: {
            pageSize: 10,
            pageSizes: [10, 15, 20, 25, 30, 40, 50, 100]
          },
          rowHeight: 50
        };
      }
    }

**Comment by ghiscoding** [comment]
You have a racing condition, you're doing something too early, for example what is `this._stateSettingsService`, is that the Angular-Slickgrid GridState Service? If so then that is not the correct way to load it and it's also too early, it shouldn't be accessed in `ngAfterViewInit`, it should be access through the `(onAngularGridCreated)` and that was created exactly for that reason to make sure you do it After the grid is ready

**Comment by ghiscoding** [comment]
I'll put in a quick fix to only execute that when the Tree Data is actually enabled and make sure the DataView object is filled before using it. I'm about to release the next `major` version, probably this week, and I won't be doing fixes much longer and so if that doesn't work you better hurry in saying something because I won't be supporting version 2.x much longer. However, I still think you have a racing condition in your code as pointed out in my previous post

**Comment by Mad4emno** [comment]
Thanks for ur help :-)
About ur first point: no this Service is my own since I wanna save and load user settings for the grid from my own db.
I just use this.gridOptions.presets of ur lib for setting them.

With my own fix I am fine, just thought others might have the same problem. So I opened this issue ^^
I am looking foward to the new major version :-)

**Comment by ghiscoding** [comment]
closed by #807

**Comment by ghiscoding** [comment]
Thanks for the feedback, it's now released under a new patch version `2.30.3` so you should be able to remove the hack you had (after updating that is). The fix was also applied on the new Slickgrid-Universal repo for the next major version (it might not be available on day 1 but it will in couple weeks). Thanks
