### ISSUE TITLE
CompoundInputText filter stopped working for StartsWith and EndsWIth

### ISSUE THREAD

**Issue by JerryFlood** [ghiscoding/Angular-Slickgrid#811]
## General Topic
CompoundInputText filter stopped working for StartsWith and EndsWIth

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 10.1       | 
| Angular-Slickgrid | 2.30        | 
| TypeScript        | 4.0.7        | 
| Operating System  | 10.15.7       | 
| NPM/Node/Yarn     | 7.8.0      | 

### Context
CompoundInputText filter StartsWith and EndsWith not functioning.

### Expected Behavior
Results to filter as text is entered

### Current Behavior
Behaves as if no filter is being applied.

### Possible Solution
Observed when entering testStringCondition (stringFilterCondition.ts?), that the operator is 'a*' or '*z' for StartsWIth and EndsWith respectively. 

The code below would work if the operator provided was 'StartsWith' or 'EndsWith' respectively or the code below could support both forms of the operator.

function testStringCondition(operator: OperatorType | OperatorString, cellValue: string, searchValue: string, searchInputLastChar?: string): boolean {
  if (operator === '*' || operator === OperatorType.endsWith) {
    return cellValue.endsWith(searchValue);
  } else if ((operator === '' && searchInputLastChar === '*') || operator === OperatorType.startsWith) {
    return cellValue.startsWith(searchValue);

**Comment by ghiscoding** [comment]
@JerryFlood 
hey I did a quick fix and version release because I'm expecting to release the next `major` on Monday/Tuesday of next week, so just update to `2,30.4` and you should be good to go (see [Release](https://github.com/ghiscoding/Angular-Slickgrid/tree/v2.30.4). 

Also note, there won't be more releases under 2.x after I'm releasing 3.x

**Comment by JerryFlood** [comment]
Tried fix and it works. Thanks

Jerry
