### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by Ulrar** [ghiscoding/Angular-Slickgrid#819]
Hi,

Just noticed a small leftover from the 2.x doc in `Grid Auto Resize`, it says `containerId` instead of the new `container` name.

Thanks

**Comment by ghiscoding** [comment]
Just resuming after vacations... Thanks, I just fixed the [Grid Auto-Resize - Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-Auto-Resize)
