### ISSUE TITLE
GridOption as `autoFitColumnOnFirstLoad:true` breaks 

### ISSUE THREAD

**Issue by winghei** [ghiscoding/Angular-Slickgrid#826]
| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 12.2.4        | 
| Angular-Slickgrid   | 3.0.5        | 
| TypeScript              | 4.3.5       | 

### Describe the Bug
returns ERROR on console. 

### Steps to Reproduce
app.component.ts 

```
import { Component } from '@angular/core';
import { GridOption } from 'angular-slickgrid';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Angular';
  dataset = [];
  columnDefinitions = [
    {
      id: 'id',
      width: 50,
      name: 'ID'
    },
    {
      id: 'name',
      width: 60,
      minWidth: 60,
      name: 'Name'
    }
  ];
  gridOptions = {
    autoFitColumnsOnFirstLoad: true //<---- this option returns an ERROR
  };
}

```

app.component.html

```
<angular-slickgrid
gridId="gridId"
[columnDefinitions]="columnDefinitions"
[gridOptions]="gridOptions"
[dataset]="dataset"
>
</angular-slickgrid>
```

### Expected Behavior
should auto-fit  columns (woks as is though)

### Current Behavior
core.js:6479 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'autosizeColumns' of undefined
TypeError: Cannot read property 'autosizeColumns' of undefined
    at AngularSlickgridComponent.set dataset [as dataset] (angular-slickgrid.js:1361)
    at setInputsForProperty (core.js:10960)
    at elementPropertyInternal (core.js:10004)
    at ɵɵproperty (core.js:14787)
    at ProductDashboardPerfTblComponent_div_24_Template (product-dashboard-perf-tbl.component.html:159)
    at executeTemplate (core.js:9599)
    at refreshView (core.js:9465)
    at refreshEmbeddedViews (core.js:10590)
    at refreshView (core.js:9489)
    at refreshComponent (core.js:10636)
    at resolvePromise (zone.js:1213)
    at zone.js:1283
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28659)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)

### Possible Solution
adding setTimeout or probably moving the autosizeColumns after slickgrid is initialized

**Comment by ghiscoding** [comment]
There no information (no code) or no way to replicate this issue so I'm not sure I can do anything here.

**Comment by winghei** [comment]
> There no information (no code) or no way to replicate this issue so I'm not sure I can do anything here.

Added some more info on code. It's actually the just the gridOption.autoFitColumnsOnFirstLoad = true that returns an error. Many thanks for this awesome project 👍

**Comment by ghiscoding** [comment]
Thanks but that still doesn't really help, I didn't run anything yet (I don't have time right now) but what I can is that this flag is already set to True in the global grid options so there's no need to re-enable it. The error seems to be coming from the SlickGrid object not being created yet, that could happen if you're not following the regular way of creating the grid (the View must be loaded before the column definitions and grid options).. oh wait that is exactly the problem you have, you can't assign grid options in the class root it's too early, you can only assign grid options in the `ngOnInit`

**Comment by winghei** [comment]
Thanks for your time checking into this :). I tried moving the gridOptions and dataset on `ngOnInit` but it still doesn't remove the error. It works though on `ngAfterViewInit`.

**Comment by ghiscoding** [comment]
You have racing conditions and it's in your code, you should follow the Angular-Slickgrid-Demo to get started. The correct lifecycle should be to create the column definition first then the grid options inside an `ngOnInit` (or `ngAfterViewInit` would probably work) and then only after all of that then assign the dataset
