### ISSUE TITLE
asyncPostRenderCleanup is never called

### ISSUE THREAD

**Issue by JE-DW** [ghiscoding/Angular-Slickgrid#828]
| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 12.0.3   | 
| Angular-Slickgrid   | 3.0.5     | 
| TypeScript              | 4.2.3     | 

### Describe the Bug
I'm generating a grid with dozens of columns and thousands of lines. All rendering perfectly... until I start using _asyncPostRender_ (no choice here, I have to interact in many ways with each cells). When scrolling through my data, I realised the more I scrolled, the more my website was lagging. After few searches, I realised my custom cells components' _ngOnDestroy()_ methods were never called.
I then found the _asyncPostRenderCleanup_ option, add it and put a log in the callback, but it was never called...
I'm pretty sure the performance issue comes from the number of angular components rendered and never destroyed.

### Expected Behavior
After scrolling, I expect _asyncPostRenderCleanup_ to be called.

### Current Behavior
Even scrolling down thousands of lines, _asyncPostRenderCleanup_ is never called.

### Code Sample
_gridOptions_:
>{
>    asyncPostRenderCleanupDelay: 0,
>    asyncPostRenderDelay: 0,
>    autoResize: {container: '#slickgridccd18f9b-8597-4418-ac4c-57b41cfdf869'},
>    createFooterRow: true,
>    createPreHeaderPanel: true,
>    editable: true,
>    enableAsyncPostRender: true,
>    enableAsyncPostRenderCleanup: true,
>    enableAutoResize: true,
>    enableAutoSizeColumns: true,
>    enableCellNavigation: true,
>    enableColumnPicker: false,
>    enableContextMenu: false,
>    enableFiltering: true,
>    enableGridMenu: false,
>    enableHeaderButton: true,
>    enableHeaderMenu: false,
>    enableMouseWheelScrollHandler: true,
>    enablePagination: false,
>    enableTreeData: true,
>    footerRowHeight: 21,
>    frozenColumn: 2,
>    gridContainerId: "slickGridContainer-forecast-grid",
>    gridId: "forecast-grid",
>    multiColumnSort: false,
>    preHeaderPanelHeight: 25,
>    showFooterRow: true
>}

_Configuration of one of the columns_:
> {
>     asyncPostRender: ƒ (),
>     asyncPostRenderCleanup: ƒ (),
>     columnGroup: "Quantity 2021 F",
>     editorType: "text",
>     field: "quantity_category_y",
>     formatter: ƒ (),
>     id: "quantity_category_y",
>     isEditable: true,
>     isSummable: true,
>     minWidth: 105,
>     name: "<label class=\"green\"> Category</label",
>     order: 111
> }

And finally, the two methods used to render and cleanup each cells:

    private _defineColumn(col: Column): void {
        if ('editorType' in col) {
            col.asyncPostRender = this._renderAngularComponent.bind(this);
            col.asyncPostRenderCleanup = this._cleanupAngularComponent.bind(this);
        }
    }
    
    private _renderAngularComponent(cellNode: HTMLElement, row: number, dataContext: any, colDef: Column, cleanupBeforeRender?: boolean): void {
        const componentOutput: AngularComponentOutput = this._angularUtilService.createAngularComponent(CustomCellComponent);

        Object.assign(componentOutput.componentRef.instance, {
            row: row,
            dataContext: dataContext,
            colDef: colDef
        });
        setTimeout(() => $(cellNode).empty().html(componentOutput.domElement));
    }
    
    private _cleanupAngularComponent(cellNode: HTMLElement, row: number, colDef: Column): void {
        console.log("Cleanup")
        $(cellNode).remove();
    }

**Comment by ghiscoding** [comment]
`asyncPostRenderCleanup` is all part of the core lib, not Angular-Slickgrid itself, and it's most probably related to this open [PR](https://github.com/6pac/SlickGrid/pull/495) that never got merged. You can comment on that other PR but I think we should close your issue

**Comment by JE-DW** [comment]
Thanks for your answer, I'll do that.

**Comment by JE-DW** [comment]
@ghiscoding I'm answering here as I'm using Slickgrid via Angular-Slickgrid.
So I replaced my slick.grid.js in `/node-modules/slickgrid/` with this one:  https://github.com/6pac/SlickGrid/blob/30df862a28877cbf13edff2bcf5ee2cad6a8c6a1/slick.grid.js
I know get the following errors, with the grid not rendering:
> vendor.js:21401 ERROR TypeError: Cannot read properties of undefined (reading 'subscribe')
>    at EventHandler.subscribe (vendor.js:216110)
>    at GridStateService.bindSlickGridOnSetOptionsEventToGridStateChange (vendor.js:108768)
>    at GridStateService.subscribeToAllGridChanges (vendor.js:108685)
>    at GridStateService.init (vendor.js:108358)
>    at AngularSlickgridComponent.registerResources (vendor.js:116488)
>    at AngularSlickgridComponent.initialization (vendor.js:115831)
>    at AngularSlickgridComponent.ngAfterViewInit (vendor.js:115670)
>    at callHook (vendor.js:17471)
>    at callHooks (vendor.js:17440)
>    at executeInitAndCheckHooks (vendor.js:17391)
I don't  know if it helps, please tell me if I can give you more infos.

**Comment by ghiscoding** [comment]
@JE-DW sorry I maybe didn't explain well, please take latest version of `slick.grid.js` right from `master` branch, not the older one like you did (that PR was never merged and will probably be deleted because 6pac pushed separate commits). There's a lot of changes since the old PR and 1 of the thing that got added was `onSetOptions` event handler which throws the error in your case because that old PR doesn't have that code... anyway long story short, take this [slick.grid.js](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js) from `master`

**Comment by JE-DW** [comment]
Oh sorry, I didn't understand it was the `master` one !
I'll try.

**Comment by JE-DW** [comment]
Ooooh @ghiscoding it's so better !
I got both logs from asyncPostRenderCleanup callback and from ngOnDestroy.
I scrolled a lot in my data and didn't see any more lag (comparing with initial rendering). 👍

**Comment by JE-DW** [comment]
Well to be more specific, following examples and calling `$(cellNode).remove();` wasn't enough to get the component destroyed. But after getting a way to get the component instance matching the cell, I was able to call its `destroy()` method. So everyhting's good now.

**Comment by ghiscoding** [comment]
@JE-DW can you provide more details, or even better update this [Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#using-angular-component-with-asyncpostrenderer)? I'd like to add that piece of code/info into the Wiki

**Comment by 6pac** [comment]
@JE-DW  yep that'd be great. I noticed that the row cache was changed to be jQuery objects during the Frozen Columns update - in the old version it was DOM objects, so the documentation might still assume the old way...

**Comment by JE-DW** [comment]
@ghiscoding I tried adding a PR from a branch, but it can't find the Branch menu on the Wiki repository (I'm used). I just push an update in the branch `asyncPostRenderCleanup-update`. I don't know if that's what you wanted.

**Comment by ghiscoding** [comment]
@JE-DW I always edit Wiki directly from the browser, can you try that? Oh wait, I had changed it to collaborator only at some point, I flipped it back to public now can you try again? I see the link is `https://github.com/ghiscoding/Angular-Slickgrid.wiki.git`

**Comment by JE-DW** [comment]
Ah yes, I can edit now !

**Comment by JE-DW** [comment]
@ghiscoding I added my changes in : [using-angular-component-with-asyncpostrenderer](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#using-angular-component-with-asyncpostrenderer).
Tell me if there's something wrong !

**Comment by ghiscoding** [comment]
@JE-DW thanks, would it be possible to also had a small piece of code demo? I think that is also what @6pac is interested to see

**Comment by JE-DW** [comment]
I have not a lot of time right now, but I'll try to add a piece of code tomorrow !

**Comment by JE-DW** [comment]
Sorry, I have a lot of work those days... I'll try add it this week. 🤞

**Comment by ghiscoding** [comment]
@jr01 
This is now available under new version `3.2.0` of Angular-Slickgrid and SlickGrid, check the [Release v3.2.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v3.2.0) section for the entire release and remember to update both Angular-Slickgrid & all Slickgrid-Universal packages.

I know you said you were busy and will update the Wiki later, but please don't forget to eventually do it 😉

**Comment by JE-DW** [comment]
I finally added a bit of code, tell me if it's good enough. 🙏

**Comment by ghiscoding** [comment]
awesome thanks for that 👍
