### ISSUE TITLE
How to dynamically set row height based on content

### ISSUE THREAD

**Issue by audrys** [ghiscoding/Angular-Slickgrid#86]
TypeScript X.X

Is there any method dynamically set row height based on content in the cells?
Thanks in advance

**Comment by ghiscoding** [comment]
Unfortunately no, SlickGrid uses `<div>` for all the rows and those are fixed height. You can change the height globally though, I've set them globally to 35 via the Global variable [rowHeight](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/global-grid-options.ts#L92) 

Also please know that Angular-Slickgrid is a wrapper of [SlickGrid](https://github.com/6pac/SlickGrid/) and when you want to know if something is doable, you can search with SlickGrid. Basically if it's doable with SlickGrid then it's most probably doable with Angular-Slickgrid and the inverse is also true.

**Comment by ghiscoding** [comment]
Closing as this is more of question, that is unfortunately not doable. You can search the net with `SlickGrid dynamic row height` and you will get possibly a lot of results, which possibly none of which really provide a working solution. See this [SO](https://stackoverflow.com/questions/2805094/is-variable-rowheight-a-possibility-in-slickgrid) for example.
