### ISSUE TITLE
Multiselect filter shows busy cursor on hover, if no items are selected

### ISSUE THREAD

**Issue by Andreas771** [ghiscoding/Angular-Slickgrid#877]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 12.2.3        | 
| Angular-Slickgrid   | 3.2.0        | 
| TypeScript              | 4.3.5        | 

### Describe the Bug

I don't think it's a behavior on purpose, so I consider it a small bug. If you have a filter, where you can select multiple items and just deselect all of them, then while hovering on the filter, there is no "hand" cursor anymore, but a "busy" cursor. Filter is still clickable though.

### Steps to Reproduce
Go to the example page: https://ghiscoding.github.io/Angular-Slickgrid/#/clientside
Two values (10, 98) are preselected for "Duration (days)". Deselect them. (Or click "SelectAll" twice to deselect all).

### Expected Behavior
If I hover over the filter field after these steps, the cursor will turn to a "hand".

### Current Behavior
If I hover over the filter field, the cursor is a "busy" cursor.

### Code Sample

https://ghiscoding.github.io/Angular-Slickgrid/#/clientside

**Comment by ghiscoding** [comment]
I see hand cursor everywhere...

![3yEHjL3SYP](https://user-images.githubusercontent.com/643976/152379660-77fe2eba-3efa-400a-b6a2-ac2d220ed6aa.gif)

**Comment by Andreas771** [comment]
Sorry, maybe I was not completely clear.

You have to deselect all filters. Remove the preset 98 and 10, so that no more filters are selected. If you then hover across the filter box, there is a "busy" cursor.

**Comment by ghiscoding** [comment]
ok I see it but I have no clue where that comes from and even adding the pointer cursor in Chrome doesn't help, so I don't know what causes this

**Comment by Andreas771** [comment]
OK. For me it's a minor issue and I can live with it.

Thanks for having a look into it.

**Comment by ghiscoding** [comment]
seems to be coming from Bootstrap somehow because my other demo of Slickgrid-Universal [Example 12](https://ghiscoding.github.io/slickgrid-universal/#/example12) which uses Bulma instead of Bootstrap doesn't have that problem

**Comment by ChristianSteu** [comment]
Not sure if you want to reopen it, but the problem seems to be a nameclash with the Bootstrap class `placeholder`. If no elements are selected the span inside the button gets the class `placeholder`, and bootstrap applies (among other things) the style `cursor: wait`  to that class. See [Bootstrap documentation on `placeholder`](https://getbootstrap.com/docs/5.1/components/placeholders/#how-it-works)

**Comment by ghiscoding** [comment]
lol their implementation sux, why would they use placeholder without any namespace when that is such a common term, they were supposed to add `bs-x` prefix to all their classes, they probably forgot that one. 

I would suggest you guys add this SASS code (or CSS equivalent)
```scss
.slickgrid-container {
  .ms-filter {
    .placeholder {
      cursor: pointer;
    }
  }
}
```
I can add a PR for that in Slickgrid-Universal but I won't do a release just for that, so you should probably add the SASS patch.

Thanks for the finding @ChristianSteu
