### ISSUE TITLE
Read only Dataset issue 

### ISSUE THREAD

**Issue by avenger1003** [ghiscoding/Angular-Slickgrid#89]
**I'm submitting a bug report
Everything is fine but im getting this error.

![image](https://user-images.githubusercontent.com/7066838/50222925-c62d3880-03bf-11e9-82d5-fb5728755f9b.png)
**

* **Library Version:**
I am using Angular 7,

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript X.X

**Current behavior:**

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by ghiscoding** [comment]
You need to provide more details than that and some piece of code to reproduce.
Also Angular 7 support it not official yet, I work on that yesterday and pushed version `2.0.0` but under a `Beta` tag, so you need to specify it in your `package.json`. So which version are you running? Is your `dataset` property a `private` property?

**Comment by ghiscoding** [comment]
I mentioned in my first reply that the support to Angular 7 is not official and that I pushed `2.0.0` as a `Beta` tag. You need to change it in your `package.json` or download it specifically through `npm i angular-slickgrid@2.0.0`. 

Note that I just found a problem with the date picker not working with new version after doing bundle prod build, I'm trying to resolve that.

**Comment by ghiscoding** [comment]
Closing as this problem was related to the use of the older version which didn't support Angular 7. 
The new version of the lib `2.0.1` addresses this

I can re-open if need be, cheers
