### ISSUE TITLE
Can we load column definitions from backend

### ISSUE THREAD

**Issue by avenger1003** [ghiscoding/Angular-Slickgrid#90]
I am doing something like this, im getting column definition error

 getProducts() {
 
    this.contentSvc.getDataSourcesByID(1).subscribe((data:any) => {
      this.columnDefinitions = Array.from( this.getColumns(data));

      for(let i = 0; i < data.currentpage.length; i++) {
          data.currentpage[i].id= i;
      }

      this.dataset = data.currentpage;
    });
  }

here is reference screenshot:

![image](https://user-images.githubusercontent.com/7066838/50293296-45426f80-0499-11e9-8b81-306a63262a11.png)

**Comment by ghiscoding** [comment]
Column Definitions must be created **before** the grid itself. So the answer is no, you cannot load column definitions from backend. However what you can do, and is what we do on our side, is to create the grid inside an `*ngIf` and display it in the View only after you have created the column definitions. 

```html
<div *ngIf="gridReady">
  <angular-slickgrid></angular-slickgrid>
</div>
```

**Comment by avenger1003** [comment]
yup makes sense , thanks you so much.

**Comment by audrys** [comment]
Hi,
How to create dynamic columns definition when is using backendServiceApi method to get data from server?
