### ISSUE TITLE
Event onAngularGridCreated is not emitted by any applicable directives nor by angular-slickgrid element 

### ISSUE THREAD

**Issue by jsEveryDay** [ghiscoding/Angular-Slickgrid#909]
### Describe the bug

Everything works as expected as far as compilation and runtime but latest IntelliJ throws this error.

![image](https://user-images.githubusercontent.com/16431055/168319767-f538f915-d787-458b-9da0-e38d8e811f3a.png)

### Reproduction

Upgrade to Angular 13 and SlickGrid 4

### Environment Info

```shell
"@angular/compiler-cli": "~13.3.6",
"typescript": "~4.6.4"
"@slickgrid-universal/common": "^1.2.6",
"angular-slickgrid": "^4.1.2",
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
I'm afraid there is nothing that I can do about this, all the events in Angular-Slickgrid are Custom Events (not Event Emitter) and Angular seems to dislike them a lot even though it's totally valid JavaScript code to use. See this [Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions/815)

**Comment by jsEveryDay** [comment]
It's cool, awesome work!
I see the resize issue I was having in V2 has been fixed too. No need for ResizeObserver anymore. Thank you!!

**Comment by ghiscoding** [comment]
Great to know you like the lib, you can also ⭐ if you haven't already 😉 
Cheers and happy coding
