### ISSUE TITLE
RealTime DataUpdates for Tree data.

### ISSUE THREAD

**Issue by kiranbangar5946** [ghiscoding/Angular-Slickgrid#974]
### Clear and concise description of the problem

Hi, i would like to ask if there is any realtime data update feature implemented for tree data , Example 28: Tree Data from slickgrid demo. we tried this,
 angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
    this.gridObj = angularGrid.slickGrid;
    this.dataViewObj = angularGrid.dataView;

    setInterval(() => {
      const newItem = {
        id: 1,
        parentId: null,
        title: `Task 1`,
        duration: '1 day',
        percentComplete: new Date().getSeconds(),
        start: new Date(),
        finish: new Date(),
        effortDriven: false
      };
      this.angularGrid.gridService.updateItem(newItem)
    }, 3000)
  }
  
Error - core.mjs:7640 ERROR Error: [Slickgrid-Universal] You must provide valid "treeDataOptions" in your Grid Options, however it seems that we could not find any tree level info on the current item datacontext row.

But shows some error can you please help. Thanks in advance.

### Suggested solution

RealTime DataUpdates for Tree data.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
I pushed new versions of both Slickgrid-Universal (v1.3.7) and Angular-Slickgrid [v4.2.7](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v4.2.7) that was to fix the small issue found in previous comment

> Also note that the item you're updating cannot be filtered out of the grid, it must be showing in the grid or it won't be able to update it. I encountered that problem as well while testing the update. I will probably fix that in a later version, we should be able to update without seeing it in the screen

this is no longer an issue with latest release, also note that the code shown in previous post works with older Angular-Slickgrid version as well
