### ISSUE TITLE
Copy contents from Custom Tooltip

### ISSUE THREAD

**Issue by crlsmsq** [ghiscoding/Angular-Slickgrid#993]
### Clear and concise description of the problem

Hello. I was looking for a feature that we could select and copy text from the custom tooltip. Right now its not possible, if it triggers the mouse exit event, the tooltip disappears. 

### Suggested solution

Hope we could have an option to make the tooltip disappear on exit

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
I understand your request but no I don't plan on adding that option, the Custom Tooltip is intended to be an extremely light and optional tooltip, I wrote it in pure JS code and the is here [slickCustomTooltip.ts](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/custom-tooltip-plugin/src/slickCustomTooltip.ts), adding the option that you're asking is probably going to double up the number of lines of code and I don't really want to (unless you know a simple way to keep it small, if so then propose a PR for the changes). 

However, another thing you could maybe look into is to use a dedicated tooltip library which have the option you're looking for. I used TipsyJS in the past and you'll have to manually subscribe to the grid mouse events yourself (like I did in `slickCustomTooltip.ts`) with an external tooltip lib.
