### ISSUE TITLE
Version 4.3.0 is not supported for Angular 13

### ISSUE THREAD

**Issue by jsmnfaye** [ghiscoding/Angular-Slickgrid#994]
### Describe the bug

Hello! I'm trying to upgrade to version 4.3.0 but it keeps asking me to upgrade to Angular 14. Based on your documentation, `4.x.x` should work fine with Angular 13, which I have installed in my machine.

### Reproduction

Have an Angular 13 project and try to install the latest Angular-Slickgrid library, which in this case is 4.3.0. You'll be notified that it requires Angular 14 to run.

### Environment Info

```shell
Angular 13
Angular-Slickgrid 4.2.1
TypeScript ~4.5.5
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Yeah it was brought up in this Discussion #987, I didn't think that upgrading the project itself to Angular 14 would also affect the minimal version for outside users but it did to my surprise. Unfortunately at this point I can't rollback, it's just too late, but you can use an older version `4.1.4` that was released before I upgraded internally to Angular 14 and it will work, you'll have to remove the `^` and also downgrade any Slickgrid-Universal packages to `1.2.6` if you have any installed

I think this should work, the OData is just an example, downgrade any Slickgrid-Universal to 1.2.6 if you have any
```js
"angular-slickgrid": "4.1.4",
"@slickgrid-universal/odata": "1.2.6"
```

**Comment by ghiscoding** [comment]
decided to downgrade it back to Angular 13, it should be fixed now. I'll upgrade back to 14 or 15 for the next major version which is currently in progress. see latest [v4.3.1](https://github.com/ghiscoding/Angular-Slickgrid/tree/v4.3.1) release

**Comment by jsmnfaye** [comment]
Thanks a lot! Appreciate the work that you do for this repository.
